### ISSUE TITLE
Cookie key change (SAPISID -> __Secure-3PAPISID)

### ISSUE THREAD

**Issue by xlorepdarkhelm** [sigma67/ytmusicapi#100]
When running ytmusicapi for the first time with the credentials I have generated following the YTMusic.setup() method, I was getting an error:

> ---------------------------------------------------------------------------
> KeyError                                  Traceback (most recent call last)
> <ipython-input-20-c5134c78bad4> in <module>
> ----> 1 ytmusic = ytmusicapi.YTMusic('headers_auth.json')
> 
> ~/.pyenv/versions/3.9.0/envs/ytm-playlist/lib/python3.9/site-packages/ytmusicapi/ytmusic.py in __init__(self, auth, user, proxies, language)
>      94         # verify authentication credentials work
>      95         if auth:
> ---> 96             self.sapisid = sapisid_from_cookie(self.headers['Cookie'])
>      97             response = self._send_request('guide', {})
>      98             if 'error' in response:
> 
> ~/.pyenv/versions/3.9.0/envs/ytm-playlist/lib/python3.9/site-packages/ytmusicapi/helpers.py in sapisid_from_cookie(raw_cookie)
>      41
>      42 # SAPISID Hash reverse engineered by
> ---> 43 # https://stackoverflow.com/a/32065323/5726546
>      44 def get_authorization(auth):
>      45     sha_1 = sha1()
> 
> KeyError: 'SAPISID'

Following this, I found that the line in error needs to be changed from:

`return cookie["SAPISID"].value`

to:

`return cookie["__Secure-3PAPISID"].value`

in ytmusicapi/helpers.py

This made the code work.

**Comment by sigma67** [comment]
I can't reproduce this, not even with a fresh session. I always have SAPISID in my cookies. 

- What POST request did you use to copy the headers? 
- Were you logged in at the time?
- What browser did you use?

**Comment by arusahni** [comment]
I encountered this issue yesterday, as well. The workaround in the OP fixed it for me.

* I used the `browse` POST request
* I was logged in at the time.
* I was using Chrome.

**Comment by sigma67** [comment]
I think the 3PAPISID is identical to the SAPISID in all cases for me, so nothing bad should come from implementing this. Unless there are some edge cases we are not aware of.
