### ISSUE TITLE
Removing duplicate playlists

### ISSUE THREAD

**Issue by MisesEnForce** [sigma67/ytmusicapi#106]
As I kept using google play music until the last minute before shutdown (youtube music being so lame because of the lack of essential functions), modyfing existing playlist etc, I transfered several times my google music library to youtube music. Of course song weren't duplicated, but playlists were. Hence, I have hundreds (yes ...) of playlists that have 6 copies on my youtube music account.

Is it possible, with your API, to do the following :

- getting the list of all playlists of my youtube music account
- for each name in the set of names of playlists, keep only one playlist with that name

?

**Comment by sigma67** [comment]
Yes, it's possible. Use 

- https://ytmusicapi.readthedocs.io/en/latest/reference.html#ytmusicapi.YTMusic.get_library_playlists
- do some Python logic to determine which one's you want to delete
- https://ytmusicapi.readthedocs.io/en/latest/reference.html#ytmusicapi.YTMusic.delete_playlist

Also, please use Gitter for questions to avoid cluttering the issues: https://gitter.im/sigma67/ytmusicapi
