### ISSUE TITLE
Enhancement - Add an option to remove duplicate songs from a playlist

### ISSUE THREAD

**Issue by sheenwins** [sigma67/ytmusicapi#107]
I like copying Spotify playlists over to YoutubeMusic and then adding that playlist to my main playlist in YoutubeMusic.  However, doing this causes songs to duplicate when they already exist.  I would love an option to automatically remove duplicate songs in any given playlist.  Seem doable?

**Comment by sigma67** [comment]
See here: https://ytmusicapi.readthedocs.io/en/latest/reference.html#ytmusicapi.YTMusic.add_playlist_items

You can choose to not add duplicates when using add_playlist_items.

>  I would love an option to automatically remove duplicate songs in any given playlist. Seem doable?

You can implement this yourself using get_playlist and remove_playlist_items.

**Comment by sheenwins** [comment]
Hi and thanks for the reply!
looking at spotifyplaylist_to_gmusic, it seems to be exactly what I want.
great job!
however, I'm still struggling with figuring out how to supply a destination
YTMusic playlist name/id.
what would the command line be to copy a spotify playlist to an already
existing YTMusic playlist?
im working on my python skills and I was able to successfully run the
ytmusicapi functions, but it's gonna take me a while to get a working
project together...so hoping you can help me out!

Thanks!
Jeff

**Comment by sigma67** [comment]
> what would the command line be to copy a spotify playlist to an already existing YTMusic playlist?

You can use the command line switch `--update`. You need to provide the correct name of the playlist you want to update. From the project description:
```
--update PLAYLIST_NAME
  Delete all entries in the provided Google Play Music playlist and update the playlist with entries from the Spotify playlist.
```
Despite the description, this switch also works with YouTube Music.

Hope that helps!

**Comment by sheenwins** [comment]
thank you, that worked!

I was confused with the arguments documentation:

-u UPDATE, --update UPDATE

might be better as:

-u <PLAYLIST_NAME>
or
-u *PLAYLIST*

Thanks!!

**Comment by sheenwins** [comment]
ok, I'm making some progress.  I'm able to copy a spotify playlist to a
youtubemusic playlist with it deleting all the songs in the destination
playlist first.  and im also able to use remove_playlist_items to remove
some songs from that playlist after.  however...

is there a way to use YouTube.py to copy a playlist from spotify to an
existing youttubemusic playlist without deleting all the tracks in that
destination playlist?  that way, i can manually add to that playlist and
not worry abt it getting deleted when it gets 'refreshed' from spotify.
 and if so, also have it not add duplicates?

thank you for your help!
Jeff

**Comment by sigma67** [comment]
Not yet, but feel free to fork and modify the code in spotifyplaylist_to_gmusic to your liking
