### ISSUE TITLE
Adding playlists [Question]

### ISSUE THREAD

**Issue by phirestalker** [sigma67/ytmusicapi#116]
When creating a playlist, will ytmusicapi inform me if the playlist already exists?
If not, what is the best way to check for an existing playlist before creating it. I could obviously use get_library_playlists and loop through, but there must be a more efficient way?

**Comment by sigma67** [comment]
There is no such thing as duplicate playlists. How would you determine that a new playlist is a duplicate? Based on the title? You can create two playlists with the same title, they would just have different playlist ids.
