### ISSUE TITLE
get_playlist playlist KeyError: 'contents'

### ISSUE THREAD

**Issue by KoljaWindeler** [sigma67/ytmusicapi#120]
hi, i'm using great api for this media_player: https://github.com/KoljaWindeler/ytube_music_player and it works great in general. a user hit the error below (https://github.com/KoljaWindeler/ytube_music_player/issues/20) any idea what happened here and how to prevent this?
thanks

`
in _update_playlists extra_info = self._api.get_playlist(playlistId=playlist['playlistId']) File "/usr/local/lib/python3.8/site-packages/ytmusicapi/mixins/playlists.py", line 100, in get_playlist playlist['tracks'].extend(parse_playlist_items(results['contents'])) KeyError: 'contents'`
`

**Comment by sigma67** [comment]
Can you provide the playlist id and make the playlist public?

**Comment by lowgoz** [comment]
hey @sigma67 - i was the user mentioned above so happy to help. 
playlist was a public one i added to my library - ID PLinS5uF49IBqWxVlkaqfOPF40NHTUeC87

@KoljaWindeler made some changes that he may be able to list, but that resolved my issue immediately

**Comment by KoljaWindeler** [comment]
Well my workaround is just to catch the exception and return 25 as default instead of the real number of tracks

**Comment by sigma67** [comment]
Thanks for the help, must be an issue with an entry in that specific playlist. I'll have a look.

**Comment by sigma67** [comment]
Strangely enough, it works flawlessly for me. II get 150 tracks returned, same as on YouTube Music  (using limit=300).

Do you get different results when you try multiple times? Can you reproduce it @KoljaWindeler ? Is it just the continuation that fails (>100 items)?

**Comment by lowgoz** [comment]
I've removed all playlists apart from a 50 song test playlist RDCLAK5uy_mGomJm2NAMa71JiNNJBZFNesgToAUUs6I

with the workaround that @KoljaWindeler implemented, i was able to get it working for today then suddenly it failed with a different error as below. I think this may be @KoljaWindeler's code but pasting the error below for you @sigma67 in case it helps pin down what's going on. 

It may be unrelated, but my youtube premium subscription was sourced internationally at a lower rate country. Might not impact the API but everything helps right?

New error:

`Traceback (most recent call last): File "/config/custom_components/ytube_music_player/media_player.py", line 396, in _update_playlists self._playlists = self._api.get_library_playlists(limit = 99) File "/usr/local/lib/python3.8/site-packages/ytmusicapi/mixins/library.py", line 29, in get_library_playlists results = find_object_by_key(nav(response, SINGLE_COLUMN_TAB + SECTION_LIST), File "/usr/local/lib/python3.8/site-packages/ytmusicapi/parsers/utils.py", line 148, in nav raise err File "/usr/local/lib/python3.8/site-packages/ytmusicapi/parsers/utils.py", line 142, in nav root = root[k] KeyError: 'contents'`

**Comment by KoljaWindeler** [comment]
Well to be honest .. I don't think that PLinS5uF49IBqWxVlkaqfOPF40NHTUeC87 is the correct ID.
For whatever reason there is always one Playlist (the playlist "music that I like") that has no count attribute.
https://github.com/KoljaWindeler/ytube_music_player/blob/8b22a6ec8af8cb6ef94b9d8e7f43df391d889721/custom_components/ytube_music_player/media_player.py#L405

I saw that I can call get_playlist() and get in the 'duration' field something like "110 Songs" .. so I parse that to 110.
https://github.com/KoljaWindeler/ytube_music_player/blob/8b22a6ec8af8cb6ef94b9d8e7f43df391d889721/custom_components/ytube_music_player/media_player.py#L407

For that reason I'd thing that we're talking about the ID "LM" .. I've added some extra debug output 
https://github.com/KoljaWindeler/ytube_music_player/blob/8b22a6ec8af8cb6ef94b9d8e7f43df391d889721/custom_components/ytube_music_player/media_player.py#L411
that will show some debug error and plot the ID that failed

@lowgz can you try ?
JKW

**Comment by sigma67** [comment]
> I saw that I can call get_playlist() and get in the 'duration' field something like "110 Songs" .. so I parse that to 110.

That is certainly a bug. I will have a look.

**Comment by lowgoz** [comment]
@KoljaWindeler  - i deleted playlist PLinS5uF49IBqWxVlkaqfOPF40NHTUeC87 as part of my fault checking so that's why it doesn't exist anymore!

The above new error looks to be cookie related - i've confirmed it remained in error state after restarts then pulled a new cookie which resolved the problem completely. 

weird bug, but looks to be fixed! Cheers!

**Comment by KoljaWindeler** [comment]
Sounds good. But it would still be nice if we could get a count field for the "LM" playlist ... If possible. That would streamline other code
