### ISSUE TITLE
Atoi with base 10 1,224

### ISSUE THREAD

**Issue by KoljaWindeler** [sigma67/ytmusicapi#125]
https://github.com/KoljaWindeler/ytube_music_player/issues/22#issue-769237617

Basically an atoi issue

extra_info = self._api.get_playlist(playlistId=playlist['playlistId'])
File "/usr/local/lib/python3.8/site-packages/ytmusicapi/mixins/playlists.py", line 91, in get_playlist
song_count = to_int(
File "/usr/local/lib/python3.8/site-packages/ytmusicapi/helpers.py", line 71, in to_int
return locale.atoi(number)
File "/usr/local/lib/python3.8/locale.py", line 330, in atoi
return int(delocalize(string))
ValueError: invalid literal for int() with base 10: '1,224'

Ps: is this the best way to raise bugs or should i redirect them straight to this respository?

**Comment by sigma67** [comment]
That issue would indicate that the locale is likely not set correctly. If the locale was set to English delocalize should work fine with that string (at least it does for me).

Regarding your other inquiry: It's probably better if you report the issues here yourself, since users of your project may not be familiar with the underlying API calls causing the issues.

**Comment by KoljaWindeler** [comment]
agreed .. but isn't that an issue with youtube? assuming that the locale is set to .. e.g. germany .. and the youtube api will still report the song count as "1,224" (which it does for me) then delocalize will fail due to the "," .. so either the youtube api need to be location aware and return "1224" or a better parse the number is needed. 

is this related to https://github.com/sigma67/ytmusicapi/commit/cf6596caedc8013f489ef2ae6f64bbb1253c7469 ? 
One idea could be to wrap that atoi in a try and try something like https://github.com/KoljaWindeler/ytube_music_player/blob/8b22a6ec8af8cb6ef94b9d8e7f43df391d889721/custom_components/ytube_music_player/media_player.py#L408 in the catch?

Kolja

**Comment by sigma67** [comment]
No, not related. If you look at the YTMusic initialization parameters you will notice that it already has a `language` parameter, which can be used to set the locale.

The `hl` parameter of all requests is set using that parameter:

https://github.com/sigma67/ytmusicapi/blob/822ad03a1fe3dafce94f6a9837d95529be4e8ac4/ytmusicapi/ytmusic.py#L70-L72

Then the locale is set based on the same language.

https://github.com/sigma67/ytmusicapi/blob/822ad03a1fe3dafce94f6a9837d95529be4e8ac4/ytmusicapi/ytmusic.py#L80-L82

The issue that can happen here is that the system rejects the provided locale (default is`en`) and then delocalize fails.

I like your suggestion of wrapping this exception. I would put a wrapper in the `to_int` function around `atoi` and try to replace the comma if atoi fails as a fallback. What do you think?

**Comment by KoljaWindeler** [comment]
Sounds perfect

**Comment by sigma67** [comment]
It's kind of sad it took me so long to catch this, but it was actually a scoping issue. The locale was being set in the `with` scope and therefore no longer valid when `atoi` is called later. Will be fixed in the next version
