### ISSUE TITLE
No /browse URL when looking for cookie for login

### ISSUE THREAD

**Issue by eroji** [sigma67/ytmusicapi#131]
I can't find any instance of `/browse` path for the requests generated during login. I've tried different machines, browser, incognito. Can someone clarify what exactly I'm missing?

![image](https://user-images.githubusercontent.com/13228540/102810699-05107300-4379-11eb-9b33-4adce519dd32.png)

**Comment by sigma67** [comment]
Did you try clicking around a bit in the library? There should be some relevant requests generated.

**Comment by sebastianklug** [comment]
Going to https://music.youtube.com/explore worked for me.

**Comment by eroji** [comment]
Browsing around the pages did seem to work. Thanks.
