### ISSUE TITLE
release year and genre information

### ISSUE THREAD

**Issue by phirestalker** [sigma67/ytmusicapi#133]
I noticed that YT music shows "moods" which correspond to genres and era music. Do they pass the genre or folksonomy of the songs somewhere where we can get at them? I see that the example has a date of some sort in the dict for library songs. Is that date the upload date or is it the release date of the song?

I am currently using MusicBrainz to get the release year and the genres of each song, but my script would speed up considerably if the data was already part of the song dict.

Let me know if it is possible, and how I can help.

**Comment by sigma67** [comment]
I'm afraid not. Usually what you can see in the frontend is all we get from the API, with a few exceptions like `get_album` (we can get the precise release date of an album as you can see in the docs). 

Personally I haven't seen any example of genres being returned, but I don't presume to have complete knowledge of the API. For example, the Discover tab has not been implemented at all yet.

> I see that the example has a date of some sort in the dict for library songs. Is that date the upload date or is it the release date of the song?

Not sure which example you're referring to.

**Comment by phirestalker** [comment]
Sorry, it was get_song. It has a key called release with a date in it. I was wondering if you know it to be the release date to YT music or the original release date of the song? Although if I have to get the genre from MB I might as well get the date there too.
