### ISSUE TITLE
NameError: name 'headers_auth' is not defined

### ISSUE THREAD

**Issue by mightymight88** [sigma67/ytmusicapi#135]
Trying to authenticate requests, but when doing `YTMusic.setup(filepath=headers_auth.json)`
I get
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'headers_auth' is not defined`
I apologize, I'm a newb and just trying to get https://github.com/KoljaWindeler/ytube_music_player to work. I'm using Python 3.9 (64bit).

Any help to point me in the right direction would be appreciated!

Thanks.

**Comment by harrytouche** [comment]
It looks to me like you're trying to pass `headers_auth.json` as a variable. Try wrapping it in some quotes to reference a string, and make sure the file is in your working directory

So
`YTMusic.setup(filepath=headers_auth.json)`
Becomes
`YTMusic.setup(filepath="headers_auth.json")`

**Comment by sigma67** [comment]
Yes, you need to wrap in quotes since the filepath is provided as a string. 

Please use Gitter for further questions if possible: https://gitter.im/sigma67/ytmusicapi/
