### ISSUE TITLE
Raise exception for authenticated calls on 403 response

### ISSUE THREAD

**Issue by harrytouche** [sigma67/ytmusicapi#136]
Starting on the 24th Dec, I am not able to retrieve my library playlists

Simply initialising and running `playlists = ytmusic.get_library_playlists()` returns the below error
![image](https://user-images.githubusercontent.com/28261887/103355026-16f2c400-4aa5-11eb-87b3-c7e67b0ea3b7.png)

Perhaps similar to the data structure change that caused #121?

**Comment by sigma67** [comment]
I don't think that endpoint was changed, since it continued to work fine for all tests during December (you said you're facing this since 12/04). 

This seems to be some issue with your account or credentials, since no data is returned at all. Can you try setting up your headers again from scratch?

**Comment by harrytouche** [comment]
Apologies, I meant to say 24th Dec, quite recently. I'll have another look

**Comment by harrytouche** [comment]
You're absolutely right, my cookie had expired!

**Comment by sigma67** [comment]
Good point, that error message is not ideal. I think that is the cause for quite a few issues recently

**Comment by alexandrechoske** [comment]
im having some erros on HA also.

![image](https://user-images.githubusercontent.com/47279355/103432514-bd7eb800-4bbe-11eb-9ea1-2347a6388a27.png)

**Comment by sigma67** [comment]
Don't think this is related to this issue or even ytmusicapi. Please check with the project maintainers

**Comment by alexandrechoske** [comment]
> 
> 
> Don't think this is related to this issue or even ytmusicapi. Please check with the project maintainers

Ahh, its weird because in the log tells to open a ticket here.
![image](https://user-images.githubusercontent.com/47279355/103443509-bc8d6b00-4c3e-11eb-85b7-345c37f3dd48.png)

Im sorry for the inconvenience.

**Comment by sigma67** [comment]
So I tried to reproduce a 403 error, but I'm getting 401 instead. Any error should be caught when YTMusic() is initalized anyway:

https://github.com/sigma67/ytmusicapi/blob/25ffe8fd07e7fca94ef224d1518dff7ca07366a7/ytmusicapi/ytmusic.py#L94-L101

I wonder why that didn't happen in your case. Do requests to `/guide` work fine with expired credentials? Could you provide the 403 response you received?

**Comment by harrytouche** [comment]
Unfortunately I can't replicate as I updated my creds and removed the old ones... My script runs overnight to update a playlist for me, and one day it just started throwing this error. The `ytmusicapi` object was initialised directly before, so I suppose it must have been working for `/guide`
If it happens again I'll come back with more detail
