### ISSUE TITLE
Limit parameter for get_library_upload_artist

### ISSUE THREAD

**Issue by KoljaWindeler** [sigma67/ytmusicapi#139]
Hi, currently get_library_upload_artist returns 25 tracks, is it possible to get more / all available tracks? 

Would it be possible to get the trackcount upfront? 
Thanks

**Comment by sigma67** [comment]
Adding a limit parameter and getting continuations is certainly possible. I don't see how you could get the track count upfront.

**Comment by KoljaWindeler** [comment]
Maybe the same for get_library_upload_album? I know that the number of cases are rare, but there are albums with over 25 tracks :D

**Comment by sigma67** [comment]
It's not needed there since all tracks are returned without pagination, just like regular albums. Perhaps I don't have albums big enough to reach the limit, so feel free to report back if you hit a limit somewhere.
