### ISSUE TITLE
[Feature Request] LastFM Integration / History API

### ISSUE THREAD

**Issue by akraus53** [sigma67/ytmusicapi#14]
### Hi All,
I would like to request a feature, which is actually something I've been trying to do with google play music for the last few weeks on and off but couldn't get to work. With Google [explaining how to switch to Youtube Music ](https://www.youtube.com/watch?v=gPWl7eKe6lY) recently, I might as well try getting it to work on YT-music. 

I want to log my listening history on LastFM, which is a platform to do exactly that, they call it "scrobbling". I'd be happy to write my own software to do the scrobbling part, but I think this could be a usefull tool for many. Scrobbling is mainly done by reading notifications or by native integration in a player, which is both impossible if you're using a Smart Home Speaker like Chromecast Audio or a Google Home Mini.

**Therefore, I'd prefer scrobbling the history from https://music.youtube.com/history**

So a feature like `ytmusic.get_history(someUnixTimestamp)` would be awesome and `ytmusic.autoScrobble()` would be even better. 

I might look into this myself, but hell, feel free to implement it yourself. 

Thanks a lot

**Comment by sigma67** [comment]
Hey, thanks for the interesting suggestions. Have you checked the [`get_history`](https://ytmusicapi.readthedocs.io/en/latest/reference.html?highlight=get_history#ytmusicapi.YTMusic.get_history) method? I think it should provide all the information you need. 

A valuable enhancement to that method could be adding a unix timestamp to each entry. Unfortunately YouTube does not provide the exact timestamp. Currently ytmusicapi is parsing the section headings you can see on the page. Those could be converted to the corresponding days at UTC+00 00:00. 

For scrobbling while playing, you can use the YTMusic integration of the [unofficial desktop player](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-). It scrobbles your YTMusic tracks while playing. 

I'm not sure how `autoScrobble()` would work. I guess you could retrieve the history page in regular intervals and scrobble new items to Last.FM. But I think that would be something a project using ytmusicapi as a dependency could implement.

**Comment by akraus53** [comment]
Thank you very much. I didn't see that that function already exists. This is the equivalent of calling tech support without trying to turn it off and on again...

**Comment by akraus53** [comment]
Feel free to reopen if you want to, I'm fine with this being fixed for now 🎧
