### ISSUE TITLE
Add maximum limit parameter to get_watch_playlist()

### ISSUE THREAD

**Issue by Donokami** [sigma67/ytmusicapi#142]
Hi,
The get_watch_playlist() function has a weird limit function, which only set a minimum limit of items to get. It would be great to implement a maximum limit function that works like other ytmusic functions, limiting the number of items to get.

**Comment by Donokami** [comment]
> No, that's not how it works. If you put limit=50 as a parameter, you will get at least 50 items returned, unless there is some error with YouTube's API. Can you provide the function call you used?

Sorry, maybe my issue wasn't clear. I don't have an issue with `limit=50`, it is just that it would be useful to also have a parameter to set a maximum of items to get when doing the request. For example, the parameter `max_limit=10` on `get_watch_playlist()` function to only get the 10 first results.

**Comment by sigma67** [comment]
Oh, but that's not how any of this API works. The YouTube Music API always provides a fixed set of results (in this case 25), and you can get more if you need more by setting a higher limit. This library will perform the corresponding calls to get them from the API. You can only do increments of 25, that's how the API works.

If you only want 10, you can easily subset the response in python:

```python
playlist = get_watch_playlist(videoId)
first_ten = playlist['tracks'][:10]
```
