### ISSUE TITLE
Question: ISRC and UPC code

### ISSUE THREAD

**Issue by pyropy** [sigma67/ytmusicapi#144]
Hi, is it possible to get ISRC and UPC codes in response?

**Comment by sigma67** [comment]
Are they available on the YouTube (Music) web interface somewhere? If not it's unlikely that they're available at all

**Comment by pyropy** [comment]
> Are they available on the YouTube (Music) web interface somewhere? If not it's unlikely that they're available at all for regular users

I haven't found it anywhere in response, but I'm not sure is there ISRC / UPC code in response actually. But I'm able to search by ISRC/UPC with `search` method.

**Comment by sigma67** [comment]
Oh interesting, that's good to know. Could you provide an example videoId with ISRC and UPC? I could check if it's contained in the response at all.

**Comment by pyropy** [comment]
Of course!

Here's example ISRC code of Michael Jackson's Earth song `USSM19500010`  and here's an example of UPC code for 21 Savage's album Savage Mode II `886448747697`.

Here's an example of how I use search with UPC/ISRC.

```python
from ytmusicapi import YTMusic
client = YTMusic()
isrc = "USSM19500010"
upc = "886448747697"

song_results  = client.search(isrc, filter='songs')  # this will hold song results, but only one result in arraya
album_results  = client.search(upc, filter='albums')  # this will hold album results, but only one result in array also
```

**Comment by sigma67** [comment]
Unfortunately no, seems it's only available in the backend for search. It was not contained in search or get_song response.
