### ISSUE TITLE
likeStatus for tracks in get_watch_playlist

### ISSUE THREAD

**Issue by KoljaWindeler** [sigma67/ytmusicapi#148]
Hi, i've just realized that get_song will not return a likeStatus.
Would you consider to add that ? 
Thanks Kolja 

Edit: same for get_watch_playlist() ...

**Comment by sigma67** [comment]
Not possible for `get_song`, `get_watch_playlist` should work

**Comment by sigma67** [comment]
Well for `get_playlist` it's only possible to know whether a song was liked, but not whether it was disliked or is indifferent. This could be determined based on the status of the menu toggle. Unfortunately no other information is provided as you can see in the web interface.

**Comment by sigma67** [comment]
@KoljaWindeler Do you think it's worthwhile implementing this if it can't report DISLIKE status? It could only state LIKE or NOT LIKED (either INDIFFERENT or DISLIKE, but we can't tell)

**Comment by KoljaWindeler** [comment]
Hi, absolutely .. I only use LIKE and "whatever" .. so that would help me absolutely !
