### ISSUE TITLE
Error when trying to browse albums (YTMusic.get_library_albums)

### ISSUE THREAD

**Issue by slipx06** [sigma67/ytmusicapi#151]
Hi. I'm using the yTube Music Player integration for home assistant. When using the api to try browse my Albums I get the error below. I can browse all other items (playlists, history etc). The author of that integration ( @KoljaWindeler ) suggested that I log an issue here. Please see the error message below:

Calling  https://ytmusicapi.readthedocs.io/en/latest/reference.html#ytmusicapi.YTMusic.get_library_albums results in the following error

```
File “/usr/local/lib/python3.8/concurrent/futures/thread.py”, line 57, in run
result = self.fn(*self.args, **self.kwargs)
File “/usr/local/lib/python3.8/site-packages/ytmusicapi/mixins/library.py”, line 140, in get_library_albums
get_continuations(results, ‘gridContinuation’, limit - len(albums), request_func,
File “/usr/local/lib/python3.8/site-packages/ytmusicapi/parsers/utils.py”, line 86, in get_continuations
contents = get_continuation_contents(results, parse_func)
File “/usr/local/lib/python3.8/site-packages/ytmusicapi/parsers/utils.py”, line 129, in get_continuation_contents
return parse_func(continuation[term])
File “/usr/local/lib/python3.8/site-packages/ytmusicapi/mixins/library.py”, line 138, in
parse_func = lambda contents: parse_albums(contents, False)
File “/usr/local/lib/python3.8/site-packages/ytmusicapi/parsers/library.py”, line 58, in parse_albums
album[‘year’] = nav(data, SUBTITLE3)
File “/usr/local/lib/python3.8/site-packages/ytmusicapi/parsers/utils.py”, line 167, in nav
raise err
File “/usr/local/lib/python3.8/site-packages/ytmusicapi/parsers/utils.py”, line 161, in nav
root = root[k]
IndexError: list index out of range
```

Thanks

**Comment by sigma67** [comment]
It seems there is an issue with a specific album. Could you check your library to see if there is any album that is missing the year? Could you link it here?

**Comment by KoljaWindeler** [comment]
FYI, I don't see the error and I don't have albums without year .. I know .. kind of obvious ..

**Comment by slipx06** [comment]
Found an album without a year 

https://music.youtube.com/playlist?list=OLAK5uy_kRmBpXs5-Yc7m3r-1zHzASvDhgug_mfg8

**Comment by KoljaWindeler** [comment]
thanks for the quick fix. look forward to the next release
