### ISSUE TITLE
results...

### ISSUE THREAD

**Issue by despoinamusica39** [sigma67/ytmusicapi#152]
hello and happy blessed year.tell me please as you know youtube music api permit very few albums and songs...do you know if there is some way to increase unlimited results?thanks a lot!

**Comment by sigma67** [comment]
What do you mean by "very few albums and songs"?

**Comment by despoinamusica39** [comment]
if you will search on app songs or albums you will get few results!but there are miles songs!!!

**Comment by sigma67** [comment]
Please contact [Google Support](https://support.google.com/), this is an unofficial project
