### ISSUE TITLE
Retrieve all songs from large library

### ISSUE THREAD

**Issue by b0wter** [sigma67/ytmusicapi#155]
I am currently trying to export my complete library form YT music. I've started by exporting all (216) liked songs and it worked perfectly :+1: 
Next step is to export all songs from my library. My library has more than 5000 tracks. I know that because I've started adding all of them to playlists of 1000 each and have 5 of them while still not being finished.

I am using:
```
yt.get_library_songs(limit=50000, validate_responses=False, order=None)
```
and get a total of ~1250 songs. With `validate_responses=True` I get 2210 songs. I've manually checkd and found songs in the webinterface that did not show in the output.
Is there something I am doing wrong? Or is it a technical limitation by YT Music?

And thanks for all the work you've put in! It's greatly appreciated :1st_place_medal:

**Comment by sigma67** [comment]
Unfortunately it is a YouTube Music limitation, that endpoint is very flaky. Not much we can do here. 

Have you tried using [Google Takeout](https://takeout.google.com/)?

**Comment by b0wter** [comment]
Thanks for the fast reply. I was dreading that response. I've tried the takeout but for reasons I do not understand it only contains all my uploads. Guess I'll go and make a support request at Google to get the other data as well.
