### ISSUE TITLE
AttributeError: 'YTMusic' object has no attribute 'headers'

### ISSUE THREAD

**Issue by essentialols** [sigma67/ytmusicapi#157]
After creating the auth json file, I'm trying to load the following:

```
from ytmusicapi import YTMusic
ytmusic = YTMusic('~/Downloads/headers_auth.json')

...
```

but I receive the error message 

`AttributeError: 'YTMusic' object has no attribute 'headers'`

**Comment by essentialols** [comment]
I tried whether it has to do with relative vs. absolute path

```
from ytmusicapi import YTMusic
ytmusic = YTMusic('/Users/[myname]/Downloads/headers_auth.json')

albums = YTMusic.get_library_upload_albums(100).values
YTMusic.delete_upload_entity(albums) 

```

This seems to have worked because now I get the following error:

Traceback (most recent call last):
  File "delete_all_albums.py", line 4, in <module>
    albums = YTMusic.get_library_upload_albums(100).values
  File "/Users/[myname]/Library/Python/3.8/lib/python/site-packages/ytmusicapi/mixins/uploads.py", line 67, in get_library_upload_albums
    self._check_auth()
AttributeError: 'int' object has no attribute '_check_auth'

**Comment by sigma67** [comment]
You need to use the instance, not the class you imported. That's why you're getting strange errors. Change YTMusic.get_library_upload_albums to ytmusic.get_library_upload_albums
