### ISSUE TITLE
Sessions and Persistent TCP connections

### ISSUE THREAD

**Issue by brayo-pip** [sigma67/ytmusicapi#159]
Hi, I'm using this module to fetch data about multiple songs at a go, I noticed that the script creates a new TCP connection for each request, which adds about 2 to 3 RTTs to each song requests, anyway, I would appreciate it if you would provide for the user the capability to pass a requests.session() to the YTMusicClient. Or find a way to keep a master session within the class for each new class. I would be down to help you with implementing it if it's a feature you will deem necessary

**Comment by sigma67** [comment]
Sounds like a good idea. We could initiate the session on instantiation and reuse it in _send_request. We can use the tests to measure before-after performance. 

I'd prefer to make it the default behavior if performance results are good. Feel free to make some suggestions of your own or start implementing if you'd like.

**Comment by brayo-pip** [comment]
That's exactly where I got the idea from

**Comment by sigma67** [comment]
Preliminary results are looking good, shaves off about 0.3s or 6% off the best case total test time when running `test_search`. Obviously many factors at play here, but it should be a great improvement for users with many calls per instance.

**Comment by sigma67** [comment]
Do you think the current implementation is satisfactory to close this issue @brayo-pip ?

**Comment by brayo-pip** [comment]
I was offline, sorry lemme review and ger back to you

**Comment by brayo-pip** [comment]
I think it's perfect, I like that there's the option to either pass a Session or simply use an in-class Session
