### ISSUE TITLE
Improper mapping while fetching artist_singles

### ISSUE THREAD

**Issue by bohrasankalp** [sigma67/ytmusicapi#163]
2 things I observed while  fetch artist singles `ytmusic.get_artist_albums(artist['singles']['browseId'], artist['singles']['params'])` 

1. The field year is mapped with Type, It was mapped earlier as singles.
2. While fetching `albums/singles` we are always getting artists as blank.

**Comment by sigma67** [comment]
The artists key should be missing instead. Good catch on the singles year field
