### ISSUE TITLE
Get_last_artist_index returns an incorrect index

### ISSUE THREAD

**Issue by bee395** [sigma67/ytmusicapi#164]
### Environment
- **System OS: Linux

- **Python Version: 3.9.1

- installed from master: 7cc054899e55aef316dade393862862e1e0baa4f

### Steps to Reproduce
1. Create a unit test with ``results = youtube.search("Yubin - PERFUME")', filter='videos')``

### Output
```
Traceback (most recent call last):
  File "/home/jasper/Applications/ytmusicapi/tests/test_2.py", line 24, in test_search
    youtube.search("Yubin - PERFUME", filter='videos')
  File "../ytmusicapi/mixins/browsing.py", line 176, in search
    search_results.extend(self.parser.parse_search_results(results, type))
  File "../ytmusicapi/helpers.py", line 83, in _impl
    return method(self, *method_args, **method_kwargs)
  File "../ytmusicapi/parsers/browsing.py", line 43, in parse_search_results
    search_result['artists'] = parse_song_artists_runs(
  File "../ytmusicapi/parsers/utils.py", line 16, in parse_song_artists_runs
    'name': runs[j * 2]['text'],
IndexError: list index out of range
```

### Other information
I think the problem lies in `parsers/utils.py:get_last_artist_index:23` since it returns a negative -2 index for [this song](https://music.youtube.com/watch?v=0XpE9jL36F4&feature=share) but I'm not sure what's special about this song.

**Comment by sigma67** [comment]
The video is missing the channel it belongs to, something I haven't seen yet.

**Comment by sigma67** [comment]
I think at this point it's better to switch to a regex based parsing of subtitles, the index stuff just isn't working out...

**Comment by sigma67** [comment]
I rewrote the song/video metadata parsing completely, please test if you can. 5cbbf73c502347b457f6a822a74b1ba048f1d9e0

**Comment by bee395** [comment]
Thanks for your quick response.

It looks like the duration is now `None` for videos of more than 1 hour.
I don't think that was the case before.

**Comment by sigma67** [comment]
Should be resolved now.

**Comment by bee395** [comment]
I just tested a few searches, and it seems to be working.

Thanks again for your quick fix :+1:
