### ISSUE TITLE
Limited records in playlist

### ISSUE THREAD

**Issue by bohrasankalp** [sigma67/ytmusicapi#166]
I have more than 20+ privately created playlists. When I tried calling for my own playlist with this `ytmusic.get_library_playlists(25)` It ends with only 3 playlist items.

**Comment by sigma67** [comment]
Make sure you're using the right account: https://ytmusicapi.readthedocs.io/en/latest/faq.html#my-library-results-are-empty-even-though-i-set-up-my-cookie-correctly
