### ISSUE TITLE
IndexError while searching anything

### ISSUE THREAD

**Issue by MRcoin2** [sigma67/ytmusicapi#172]
`query = "Martin Stig Andersen - Deteriation"`
`results = ytmusic.search(query, ignore_spelling=True)`

**gives:**

`Traceback (most recent call last):`
`  File "C:/Users/szymc/PycharmProjects/SpotifyToYouTubeSongPlaylist-master/SpotifyToYouTube.py", line 32, in <module>`
`    results = ytmusic.search(query, ignore_spelling=True)`
`  File "C:\Users\szymc\PycharmProjects\SpotifyToYouTubeSongPlaylist-master\venv\lib\site-packages\ytmusicapi\mixins\browsing.py", line 115, in search`
`    search_results.extend(self.parser.parse_search_results(results, type))`
`  File "C:\Users\szymc\PycharmProjects\SpotifyToYouTubeSongPlaylist-master\venv\lib\site-packages\ytmusicapi\helpers.py", line 78, in _impl`
`    return method(self, *method_args, **method_kwargs)`
`  File "C:\Users\szymc\PycharmProjects\SpotifyToYouTubeSongPlaylist-master\venv\lib\site-packages\ytmusicapi\parsers\browsing.py", line 52, in parse_search_results`
`    search_result['artists'] = parse_song_artists(data, 1 + default)`
`  File "C:\Users\szymc\PycharmProjects\SpotifyToYouTubeSongPlaylist-master\venv\lib\site-packages\ytmusicapi\parsers\utils.py", line 6, in parse_song_artists`
`    flex_item = get_flex_column_item(data, index)`
`  File "C:\Users\szymc\PycharmProjects\SpotifyToYouTubeSongPlaylist-master\venv\lib\site-packages\ytmusicapi\parsers\utils.py", line 96, in get_flex_column_item`
`    if 'text' not in item['flexColumns'][index]['musicResponsiveListItemFlexColumnRenderer'] or \`
`IndexError: list index out of range`

i'm using the newest version

**Comment by sigma67** [comment]
You definitely *aren't* using the latest version. In fact, the last version that contains the code in your error message is v0.11.0. Please update using `pip install ytmusicapi -U`.
