### ISSUE TITLE
After adding songs to a playlist: return the new setVideoId for each song

### ISSUE THREAD

**Issue by MattC8915** [sigma67/ytmusicapi#176]
The setVideoId is helpful information to have.

in `add_playlist_items` instead of just returning `response['status']` also include the `playlistEditResults`

I would be happy to submit a pull request if you would accept it. But this would break the pattern of only returning STATUS_SUCCEEDED for successful requests...is that acceptable?

**Comment by sigma67** [comment]
Good point, that could be useful. Feel free to submit a PR. Please also test with source_playlist parameter and multiple videoIds, as well as the dedupe option (duplicates parameter).

**Comment by sigma67** [comment]
Merged in #180
