### ISSUE TITLE
Ability to use different channels within an account

### ISSUE THREAD

**Issue by kaizersoje** [sigma67/ytmusicapi#177]
I have 2 channels setup within my account. Is there a way to choose the channel while setting up the api?

**Comment by sigma67** [comment]
Yes, the feature is called brand accounts. Further described [here](https://github.com/sigma67/ytmusicapi/issues/37#issuecomment-652950069).

**Comment by kaizersoje** [comment]
I was able to get the `onBehalfOfUser` value and add it to `header.json`. 

`"onBehalfOfUser": "123456789123456789123"`

However, it does not seem to be using the channel/brand account and is using the parent account instead.

**Comment by sigma67** [comment]
You're supposed to pass it to YTMusic(user=1234567). Not sure how that'd work with the project you're using.
