### ISSUE TITLE
 Command raised an exception: AttributeError: 'int' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by Keldraistaken** [sigma67/ytmusicapi#182]
get_playlist(str, int) 

AppData\Local\Programs\Python\Python39\lib\site-packages\ytmusicapi\mixins\playlists.py", line 63, in get_playlist
    browseId = "VL" + playlistId if not playlistId.startswith("VL") else playlistId

what am i supposed to do here? I've tried fixing it on my own but it didn't work? 
HELP

**Comment by sigma67** [comment]
Make sure you pass correct parameters

https://ytmusicapi.readthedocs.io/en/latest/reference.html#ytmusicapi.YTMusic.get_playlist

**Comment by Keldraistaken** [comment]
It doesn't matter what parameters I pass in, I even tried your test code and it did not work. Here's the trace; 

    playlist = youtube.get_playlist("PL6bPxvf5dW5clc3y9wAoslzqUrmkZ5c-u", 300)
AttributeError: 'Resource' object has no attribute 'get_playlist'
