### ISSUE TITLE
Error while playing a playlist

### ISSUE THREAD

**Issue by kaizersoje** [sigma67/ytmusicapi#185]
I am getting the following error when trying to play a playlist

`Traceback (most recent call last): File "/config/custom_components/ytube_music_player/media_player.py", line 1096, in play_media self._tracks = self._api.get_playlist(playlistId=media_id)['tracks'] File "/usr/local/lib/python3.8/site-packages/ytmusicapi/mixins/playlists.py", line 67, in get_playlist results = nav(response, File "/usr/local/lib/python3.8/site-packages/ytmusicapi/parsers/utils.py", line 146, in nav raise err File "/usr/local/lib/python3.8/site-packages/ytmusicapi/parsers/utils.py", line 140, in nav root = root[k] KeyError: 'contents'`

**Comment by sigma67** [comment]
Please state which playlist (playlistId)
