### ISSUE TITLE
Get resource from link

### ISSUE THREAD

**Issue by nickpwhite** [sigma67/ytmusicapi#186]
Hi there,

I have a use case that involves looking up information about a resource given it's "share" link (accessible from Share under the 3 dots menu). For songs this is easy, since their share link looks something like this: https://music.youtube.com/watch?v=noez-N3GwU8&feature=share and I can use the video ID (the value of the v query param) to look up the song using the get_song function.

On the other hand, albums have links that look like this: https://music.youtube.com/playlist?list=OLAK5uy_nu7bYOOPMVusryrM-q09vOKZzhVFlDICw&feature=share and the value of the list query param doesn't appear to be a browse id, and it doesn't work if I pass it into the get_album function. I also tried passing it to the get_playlist function and got a different error, I think the response coming back from the initial request is not the right shape.

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File ".../lib/python3.8/site-packages/ytmusicapi/mixins/playlists.py", line 68, in get_playlist
    results = nav(response,
  File ".../lib/python3.8/site-packages/ytmusicapi/parsers/utils.py", line 147, in nav
    raise err
  File ".../lib/python3.8/site-packages/ytmusicapi/parsers/utils.py", line 141, in nav
    root = root[k]
KeyError: 'contents'
```

the response looks like this:
```
{'responseContext': {'visitorData': 'CgtWaTB2WWRDeEFUYyih5J6DBg%3D%3D', 'serviceTrackingParams': [{'service': 'GFEEDBACK', 'params': [{'key': 'has_unlimited_entitlement', 'value': 'False'}, {'key': 'browse_id', 'value': 'VLOLAK5uy_lbawo5tQ-j0uMtDkTC0bRJR14fETLNgKA'}, {'key': 'logged_in', 'value': '0'}, {'key': 'e', 'value': '23857950,23804281,23918597,23987676,24020952,23946420,23744176,23974595,24014701,24022725,24007246,23934970,24011119,23891344,24016834,24013979,23891346,23882502,23884386,23966208,23976697,24017508,23990876,23969934,24016479,24022965,24010465,23944779,23983296,24011306,24022838,24014268,24012117,23968386,1714257,24006795,24005803,24001373,24022206,24010254,23999152'}]}, {'service': 'CSI', 'params': [{'key': 'c', 'value': 'WEB_REMIX'}, {'key': 'cver', 'value': '0.1'}, {'key': 'yt_li', 'value': '0'}, {'key': 'GetBrowsePlaylistDetailPage_rid', 'value': '0x0ea5ad5a16ec4358'}]}, {'service': 'ECATCHER', 'params': [{'key': 'client.version', 'value': '0.1'}, {'key': 'client.name', 'value': 'WEB_REMIX'}]}]}, 'trackingParams': 'CAAQhGciEwiQmKOu5ODvAhUwREwIHSdFAT8='}
```

This error and response are from the current master. I haven't been able to get this work on the latest release (0.15.0) either.

Does the package currently provide a way to accomplish my goal here? If not, do you think that it's doable and in scope for this package? I'm happy to contribute PRs if you're open to it.

**Comment by sigma67** [comment]
It seems like it's just the audioPlaylistId?

**Comment by nickpwhite** [comment]
That looks right, I was able to get a usable response using:
```python
YTMusic().get_watch_playlist(None, "OLAK5uy_nu7bYOOPMVusryrM-q09vOKZzhVFlDICw")
```

Using the list of tracks there I could pull the album browseId to get more information about the album through the get_album function.

Thanks for the help! I'll close this issue.

**Comment by sigma67** [comment]
I think it's actually possible to get the browseId from the audioPlaylistId with a single GET request. If you open the share link in the browser with the audioPlaylistId you get redirected to the correct page, since the request returns the browseId of the album. Could be implemented as a separate function in ytmusicapi.

**Comment by nickpwhite** [comment]
That's great, thank you! Here's an example of this function in action: https://github.com/nickpwhite/Beatnik/pull/28
