### ISSUE TITLE
ytm.search returns empty array "artists" field on some queries (Query example included)

### ISSUE THREAD

**Issue by totobest** [sigma67/ytmusicapi#187]
How to reproduce :

```
len(ytm.search(query='Dimitri Vegas, MOGUAI & Like Mike - Mammoth (Original Mix)', filter="songs")[2].artists) == 0
```
Actual result:
```
True
```

Expected result:
```
False
```

Same query in YTM GUI:
<img width="646" alt="2021-04-10 13_40_57-Stay (Steve James Remix) (feat  Dia Frampton) - YouTube Music" src="https://user-images.githubusercontent.com/11507846/114268650-6d579300-9a02-11eb-9c92-76b98c5d52dc.png">

ytmusicapi version : 0.15.1

**Comment by sigma67** [comment]
Let me know if the fix works for you!
