### ISSUE TITLE
get_artist_albums(channelId, params) returning KeyError: 'content'

### ISSUE THREAD

**Issue by Zombee0804** [sigma67/ytmusicapi#191]
I'm trying to fetch a list of artist albums for artists with more albums than can be displayed in the get_artist() results. Sometimes it works, but other times I get:
```
Exception has occurred: KeyError
'content'
  File "D:\Documents\Python\unfinished\bandThing\version4\scripts\ytmInteractor.py", line 50, in get_album_list
    albums = ytm.get_artist_albums(channelID, params)
  File "D:\Documents\Python\unfinished\bandThing\version4\scripts\ytmInteractor.py", line 120, in get_album_data
    albumList = get_album_list(artistData)
  File "D:\Documents\Python\unfinished\bandThing\version4\scripts\ytmInteractor.py", line 38, in get_artist_data
    albumData = get_album_data(albumName, artistBrowseID = artistBrowseID, defaultIncluded = defaultIncluded)
  File "D:\Documents\Python\unfinished\bandThing\version4\scripts\main.py", line 6, in load_artist_to_csv
    artistData = ytm.get_artist_data(artistName, defaultIncluded = defaultIncluded)
  File "D:\Documents\Python\unfinished\bandThing\version4\scripts\main.py", line 152, in <module>
    load_artist_to_csv(artist, defaultIncluded = di)
```

I have tried looking at the original code but it is far too advanced for me. I have tried comparing data and found that the params variable is changing each time that I get it from get_artist() results, but don't know what is causing the error on certain calls, but not others.

**Comment by sigma67** [comment]
Could you kindly provide the channelId?

**Comment by Zombee0804** [comment]
AC/DC: UCB0JSO6d5ysH2Mmqz5I9rIw
Anathema: UCD_YQdIsW1phqp5AqQwmKhg

get_artist_albums() is called in a function, called from a loop. It works if I try and do it on its own but it just breaks in the loop

**Comment by sigma67** [comment]
I can't replicate the error consistently either, but I see what you're referring to. I think it might be a timing issue, that get_artist_albums is being called too fast after get_artist and the server doesn't have the albums ready yet. Perhaps you can get more consistent results by adding a delay between the two calls?

But yea, it's just the server being flaky, not much we can do here on the ytmusicapi side imo.

**Comment by Zombee0804** [comment]
I tried a few different delays and still got the issue with 3 seconds. Seemed to work fine with 5-second delays. Might just be a good idea to take out the loop and find a more efficient solution for what I'm trying to do. Thank you for your help.

**Comment by sigma67** [comment]
To be honest this endpoint is quite awkward to work with, since it directly depends on another endpoint being called before. This clearly violates REST principles, where requests are supposed to be isolated, stateless and independent of each other.

But unfortunately it's all we have. Since there is no other way to access an official API, we have to work with it. Good luck in your endeavor.
