### ISSUE TITLE
Add_playlist_items() results in TypeError

### ISSUE THREAD

**Issue by gersp** [sigma67/ytmusicapi#192]
Hey guys,

noobie here on my second month learning python and first time creating an issue on GitHub...
Somehow I get this error when trying to add items to a playlist:

`TypeError: add_playlist_items() missing 1 required positional argument: 'videoIds'`

My highly complicated code:

> playlistid = 'PLUenIw9z1qHoO7Zx7t-ypSG0Q6MzoGRYH'
     videoids = ["38YpUIcSaks","nYq18j1pd1g"]
    YTMusic.add_playlist_items(playlistid, videoids)

The auth works fine as I was able to create a playlist with code.
Thanks!

**Comment by sigma67** [comment]
Did you create an instance of YTMusic()? 


https://ytmusicapi.readthedocs.io/en/latest/usage.html

**Comment by gersp** [comment]
@sigma67  Yes, I have the json authentification all set and working as I was able to create a playlist in my YouTube music account.

**Comment by sigma67** [comment]
Then your code should work as you posted it above.

Please continue this discussion on gitter as it's clearly not an issue with the API: 
https://gitter.im/sigma67/ytmusicapi
