### ISSUE TITLE
Is get_streaming_data still working? 

### ISSUE THREAD

**Issue by KoljaWindeler** [sigma67/ytmusicapi#196]
Hi, this is one of those "some user have a problem but not all" things.

Original issue:  
https://github.com/KoljaWindeler/ytube_music_player/issues/97
I can't reproduce the issue myself but quite a few user suddenly lost the ability to listen to music.

My code would call get_streaming_data but (according to the logs) would only get an empty response {}.

As of now I use a backup method for those users but wonder why get_streaming_data isn't working anymore for so many users.

This is the interesting part:
2021-05-17 12:46:11 ERROR (MainThread) [custom_components.ytube_music_player.media_player] No adaptiveFormat and no formats found
2021-05-17 12:46:11 ERROR (MainThread) [custom_components.ytube_music_player.media_player] get_streaming_data(SQyu9vfW9Bk)
2021-05-17 12:46:11 ERROR (MainThread) [custom_components.ytube_music_player.media_player] {}

https://github.com/KoljaWindeler/ytube_music_player/blob/dc06c8b1c37c6cc0fc01769f7d9854f11a4a4f26/custom_components/ytube_music_player/media_player.py#L1118

**Comment by sigma67** [comment]
It might be related to the x-goog-visitor-id. Can you have your users try again with the latest version? Perhaps that already fixed the issues.

**Comment by KoljaWindeler** [comment]
hah, interesting .. now I have the same issue with 17.0  ... what can i do to get you the needed infos?

**Comment by sigma67** [comment]
Thanks for being persistent, it seems the flow has changed on the YouTube side. There is now a YouTube Music specific endpoint, it no longer uses the YouTube get_video_info.

The new endpoint is `https://music.youtube.com/youtubei/v1/player`. Besides `streamingData `it also returns some other things like `videoDetails`, `playerConfig`, `storyboards` and an `attestation`, to prevent  bots. 

I propose we replace the existing call with that one, but keep the method name.

**Comment by KoljaWindeler** [comment]
I can totally adopt as the current result is empty anyway ;)

**Comment by sigma67** [comment]
I pushed a simple implementation, feel free to try and provide feedback :)

The method is now `get_song `only which also provides the streaming data.

**Comment by KoljaWindeler** [comment]
hmm get_song is also {} .. nothing got returned .. strange, right?

**Comment by KoljaWindeler** [comment]
hmm I'm not sure if I'm doing it right .. usually I've cloned your resposity into my code root (well, copied the ytmusicapi folder of it into my code root) and replaced `import ytmusicapi` with `from .ytmusicapi.ytmusic import *` ... I thought that would switch all calls from the package to the local version, but I've just modified the get_song routine to return a simple 'hallo' but still it only returns `{}`

is there a simple way to use the local version?

**Comment by KoljaWindeler** [comment]
hmm ok .. i was able to install the latest version from github and test the get_song interface. It look fine but I can't decode a link from these data anymore .. so the format or the way how the data was coded seems to have changed .. damn ..

**Comment by sigma67** [comment]
I think the url is right there in the adaptiveFormats, signatureCipher.  If you plug the string into urldecode you get this

> s=dcLlHhJluwGqgZe4fddhrjW6fy2K1QHBjmuWAWJ0L7FICMV9p4bJjJA9_jxa-Y2tvfwl6Uqf4roC2Y1ihHI17N8UgIARw8JQ0qOAqOA&sp=sig&url=https://r3---sn-h0jeenle.googlevideo.com/videoplayback?expire=1621373519&ei=792jYMbzLqWwx_AP4qOJ4AI&ip=2a02%3A810d%3A8cbf%3Aa817%3A5004%3Ab644%3Aad94%3A719a&id=o-ABfCybNbVrK3L1_nDyI0d-ZaQEwvMZdtYXy5vyH1s1DT&itag=140&source=youtube&requiressl=yes&mh=XB&mm=31%2C26&mn=sn-h0jeenle%2Csn-4g5ednly&ms=au%2Conr&mv=m&mvi=3&pl=40&ctier=A&pfa=5&gcr=de&initcwndbps=1760000&hightc=yes&vprv=1&mime=audio%2Fmp4&ns=wRU5itKblG1tOvwJoHjS3A4F&gir=yes&clen=1502464&dur=92.689&lmt=1605029384415344&mt=1621351513&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=WEB_REMIX&txp=2311222&n=UhcecUePl1RsmzHMY&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cctier%2Cpfa%2Cgcr%2Chightc%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgPyDw3RgGAf5TCkvx_E5opT7cIz40or9giuGCFLv8BLACIDW7315PGxNdD2F2V-vAUWrkQ6AsCToKGfe2OnygI5bY

But I have no idea how your code works so I might be missing something.

**Comment by KoljaWindeler** [comment]
ok this is really a problem for me .. i used to load your api and the pytube lib (https://pytube.io/en/latest/).
Your code provided the streaming data (ciphered_signature + url) and the pytube.cipher.get_signature() methode decoded the ciphered_signature. Joining them together resulted in the direct streaming link that I'd forward to the various players. It turns out that those links aren't valid any more. So I'd assume that the cipher for YouTube.music and YouTube now differ. Bummer.
Any idea how I could get the direct streaming link now? 

https://github.com/KoljaWindeler/ytube_music_player/blob/8aea65d2c5a7ed0ef22677428ca001ce927578ca/custom_components/ytube_music_player/media_player.py#L1164

**Comment by KoljaWindeler** [comment]
some more info... the cipher of youtube and youtube music are indeed identical ... so even if I point Pytube to the Youtube music js i get the same decoding schema ... and the same decoded signature ... and the same error ... so it feels like something is of with the data that get_song returns .. any clue?

**Comment by sigma67** [comment]
`get_song` is currently simply passing on the response that is being returned by the `player` endpoint without modification. You can verify easily by using the response data from the `player `request in your browser instead. As mentioned above, have you tried running `urllib.parse.unquote` on the cipher before passing it to the other library?

**Comment by KoljaWindeler** [comment]
Hi, yep I unquote the url. The s parameter isn't quoted or at least wouldn't change (tested ;))

**Comment by KoljaWindeler** [comment]
good morning, I got some news .. there is definitely some off :D 
I've searched for 'player' in the network tab and found the strreamingData. I've copied those data to a simple script and decoded the url without issues (horray) 

after that grabbed the data for the same videoId via ytmusicapi and failed. so something is happening between browser and ytmusicapi. The issue is that the url is almost completely of .. so it's hard to tell where the issue is .. 

here is the script (I guess both links won't work for you as they are mapped to my IP but the way should be fairly clear)
 https://pastebin.com/qH0Z8Zh6

what can I do to help?

**Comment by sigma67** [comment]
Thanks for the script, I tried it and it worked fine for me. No errors and both URLs get printed at the end. Can you point out where you're getting errors with the script?

The POST data of the two in-browser requests differs only with regard to the `isPrefetch` flag, which is true for the first one. So I think we can ignore that.

Other things that are missing in the ytmusicapi request POST data are the following (disregarding the context key, which shouldn't matter as it's used in all requests):

```json
{ 
  "cpn": "gPcYTcHt2gharuC3",
  "playbackContext": {
    "contentPlaybackContext": {
      "autoCaptionsDefaultOn": false,
      "autonavState": "STATE_OFF",
      "html5Preference": "HTML5_PREF_WANTS",
      "lactMilliseconds": "3021",
      "liveContext": {
        "startWalltime": "0"
      },
      "mdxContext": {},
      "referer": "https://music.youtube.com/search?q=oasis+wonderwall",
      "signatureTimestamp": 18765,
      "vis": 1
    }
  }
}
```

CPN is a nonce computed clientside for debug purposes (Client Playback Nonce). Not sure if the playbackContext is required, but seems not as your script was working for me.

**Comment by KoljaWindeler** [comment]
So both urls printed at the end work for you? The non_browser url Always results in a error 403 for me

**Comment by sigma67** [comment]
Yes. There might be something wrong with your headers as 403 is returned if you're not authorized. Can you access your library with those headers?

**Comment by KoljaWindeler** [comment]
Library works 100% correct

**Comment by KoljaWindeler** [comment]
Would it help if I send you my header file via email?

**Comment by sigma67** [comment]
You could try doing another setup run, as the setup procedure as changed in the latest release. If that doesn't work you can send it to ytmusicapi@gmail.com

**Comment by KoljaWindeler** [comment]
still didn't work .. email is on the way .. lets see if that works for you

**Comment by sigma67** [comment]
No errors at all using your code and headers. Not sure what I should be looking for. I literally copy pasted the file in your email and ran it. I only changed the filepath to a file in the local directory (not /tmp/).

**Comment by sigma67** [comment]
Oh I think there's a misunderstanding. You're doing another step by calling the googlevideo.com URL and getting 403 on that?

**Comment by KoljaWindeler** [comment]
Exactly .. I open the resulting googlemusic url .. one leads to .. well the MP4 the other to a 403.
The 31.18. ... Is my ip

**Comment by sigma67** [comment]
Sorry I got a bit confused in your script there...

It seems it's indeed related to the missing POST data I included above. Will commit a fix shortly

**Comment by sigma67** [comment]
Unfortunately I'm not sure what the `signatureTimestamp `is based on, but it was always `18766` for me, even when not signed in.

**Comment by KoljaWindeler** [comment]
So the additional information fixes the issue for you? In other words: 
Can you open the generated link and will it play music for you? Will test right after dinner!!

**Comment by sigma67** [comment]
Yes, I verified that now :)

**Comment by KoljaWindeler** [comment]
here as well .. great. could you publish a new version so we can roll this out to all others?
Thanks a thousand times! great work!

**Comment by sigma67** [comment]
Closed in 8c4b857

**Comment by simu** [comment]
Playback (I'm using ytmusicapi via mopidy_ytmusic) broke again for me today (song URLs result in 403), and inspecting the requests on the web app showed that `signatureTimestamp` has changed to `18767` for me now. Adjusting the timestamp in the code fixes playback.

**Comment by KoljaWindeler** [comment]
Same here

**Comment by sigma67** [comment]
Incrementing by one after a day seems very suspicious. Turns out it is derived from the UNIX datestamp! The datestamp is the number of days since 01-01-1970, which is currently `18768`. If you decrement that by one you get the `signatureTimestamp` `18767` that's currently being used. 

Strangely enough, about 43 hours ago (time of my commit), the timestamp was `18766`, so that would imply that the timestamp had just incremented in the 5 hours before that time. That would mean that the increment time is not UTC midnight, as it would be if it was derived from the UNIX timestamp. Perhaps we can monitor in the coming hours when the `signatureTimestamp `changes, so we can avoid similar issues in the future.

**Comment by simu** [comment]
> Turns out it is derived from the UNIX datestamp! The datestamp is the number of days since 01-01-1970, which is currently 18768. If you decrement that by one you get the signatureTimestamp 18767 that's currently being used.

I figured this out in the mean time as well, but I haven't been able to pinpoint the increment time yet

**Comment by KoljaWindeler** [comment]
still 18767

**Comment by impliedchaos** [comment]
I'm not sure how viable of a strategy it is to do it based on time.  The signatureTimestamp is set in the base.js version.  This doesn't change at the same time everyday.   My application tries to fetch the base.js url every 15 minutes:
```
2021-05-18 19:22:34,717 player URL /s/player/08244190/player_ias.vflset/en_US/base.js
2021-05-18 19:37:36,302 player URL /s/player/ae091644/player_ias.vflset/en_US/base.js

2021-05-19 07:08:48,142 player URL /s/player/ae091644/player_ias.vflset/en_US/base.js
2021-05-19 07:23:49,798 player URL /s/player/fba90263/player_ias.vflset/en_US/base.js

2021-05-20 19:14:43,799 player URL /s/player/fba90263/player_ias.vflset/en_US/base.js
2021-05-20 19:29:45,302 player URL /s/player/3d0175c7/player_ias.vflset/en_US/base.js
```
(times are UTC+4)

**Comment by sigma67** [comment]
Seems it isn't a fixed interval but instead depends on when the server script gets updated. 

The `signatureTimestamp` value is hardcoded (probably dynamically generated by the server) in the base.js player script retrieved from music.youtube.com.  Looking at other apps like YoutubeExplode they get the `signatureTimestamp` by parsing the player script retrieved from the watch page. That's at least two additional requests though, one to get the page with the URL of the player script, another to get the player script, from which you can then retrieve the `signatureTimestamp`. 

Another alternative could be to try the `datestamp - 1` method by default and fall back to `datestamp` if it fails. Then we'd need a way to verify the correctness though.

This is under the assumption that the server will only accept the `signatureTimestamp` in the most current player script, which seems to be the case from what we've seen.

**Comment by KoljaWindeler** [comment]
Well .. grabbing the signatureTimestamp wouldn't be necessary every single time. One could grab it, set it, decode the url, check the header and refetch if the header returns a 403 ...

**Comment by impliedchaos** [comment]
> Or make `signatureTimestamp` an optional parameter to `get_song`.

This would be my personal preference.  And if the parameter isn't passed, then use the `datestamp - 1` logic.

**Comment by KoljaWindeler** [comment]
jep, something like this https://pastebin.com/sxbwa8Ee just with 37 instead of 38

**Comment by sigma67** [comment]
I've added a quick fix along the lines of what was suggested above. I'd gladly accept a PR for a `get_signatureTimestamp` helper method since you guys seem to know more about that part than me

**Comment by KoljaWindeler** [comment]
the current change totally works for me .. just tested .. i guess adding the lookup into the library wouldn't really help because it would heavily slow down the function .. would you consider to release this change?

**Comment by sigma67** [comment]
Published a new release. 

> i guess adding the lookup into the library wouldn't really help because it would heavily slow down the function

I was thinking more of making a separate method that can be called to get the signatureTimestamp, so others don't have to reimplement that part

**Comment by KoljaWindeler** [comment]
Fair enough. Will push a PR based on my stuff tomorrow

**Comment by KoljaWindeler** [comment]
works just perfect here .. I guess we can close this once more
Thanks a lot guys!
