### ISSUE TITLE
get_album() fails with a KeyError on 'frameworkUpdates'

### ISSUE THREAD

**Issue by beville** [sigma67/ytmusicapi#20]
This one is a bit obscure to me.  

Simple code:
```
albums = ytmusic.get_library_upload_albums(limit=10)
albuminfo = ytmusic.get_album(albums[0]['browseId'])
```
Results in:
```
Traceback (most recent call last):
  File "./ytmusic.py", line 155, in <module>
    main()
  File "./ytmusic.py", line 145, in main
    track_ids = get_random_album_tracks(ytmusic, 2)
  File "./ytmusic.py", line 73, in get_random_album_tracks
    albuminfo = ytmusic.get_album(albums[0]['browseId'])
  File "/usr/local/lib/python3.8/dist-packages/ytmusicapi/ytmusic.py", line 373, in get_album
    data = nav(response, FRAMEWORK_MUTATIONS)
  File "/usr/local/lib/python3.8/dist-packages/ytmusicapi/parsers.py", line 284, in nav
    root = root[k]
KeyError: 'frameworkUpdates'
```
I dumped the response text from library ytmusic.py:373, and attached.
[resp.txt](https://github.com/sigma67/ytmusicapi/files/4639082/resp.txt)

**Comment by sigma67** [comment]
Uploaded albums don't work yet with `get_album `. The uploaded album pages are processed differently from the uploaded albums.

Same for uploaded artists, the pages are different from the regular artists. I'll work on this soon.

**Comment by sigma67** [comment]
Hey, I added two new methods for this purpose. The endpoints where quite different from get_album and get_artist, so that's why I added new ones.

Let me know if these methods work for you!

**Comment by beville** [comment]
I tried out get_library_upload_album() and it worked for me.

Thanks again doing this project!
