### ISSUE TITLE
AttributeError: 'int' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by LittleBigOwI** [sigma67/ytmusicapi#204]
I execute this :
```
from ytmusicapi import YTMusic
playlist = YTMusic.get_playlist("PL6bPxvf5dW5clc3y9wAoslzqUrmkZ5c-u", 300)
print(playlist)
```

and get this :
```
browseId = "VL" + playlistId if not playlistId.startswith("VL") else playlistId
AttributeError: 'int' object has no attribute 'startswith'
```

idk what's wrong, any help pls?

**Comment by sigma67** [comment]
Are you sure that's what you executed? The error says you passed an int as first parameter (playlistId). You can try specifying parameters manually like this to be absolutely sure, although it shouldn't be needed:

```python
playlist = YTMusic.get_playlist(playlistId="PL6bPxvf5dW5clc3y9wAoslzqUrmkZ5c-u", limit=300)
```

The playlist works fine for me.

**Comment by LittleBigOwI** [comment]
> Are you sure that's what you executed? The error says you passed an int as first parameter (playlistId). You can try specifying parameters manually like this to be absolutely sure, although it shouldn't be needed:
> 
> ```python
> playlist = YTMusic.get_playlist(playlistId="PL6bPxvf5dW5clc3y9wAoslzqUrmkZ5c-u", limit=300)
> ```
> 
> The playlist works fine for me.

This (for me) results in :
```
TypeError: get_playlist() missing 1 required positional argument: 'self'
```
Again, i know what's wrong but idk how to fix it. sorry for the trouble.

**Comment by sigma67** [comment]
Oh. Please read the docs.

https://ytmusicapi.readthedocs.io/en/latest/usage.html

**Comment by LittleBigOwI** [comment]
> Oh. Please read the docs. You need to create a class instance first.
> 
> https://ytmusicapi.readthedocs.io/en/latest/usage.html

This worked perfectly Thanks !
