### ISSUE TITLE
Play music on local device instead of Chromecast?

### ISSUE THREAD

**Issue by myopenflixr** [sigma67/ytmusicapi#206]
Hello,

I have a wall mounted android tablet running Home Assistant in my basement/gameroom. The tablet's audio is connected to a Stereo receiver via bluetooth, which is connected to ceiling speakers. This allows me to use the same tablet to play music through the ceiling speakers with Plexamp, Pandora, etc.

Would it be possible to have the option of this ytmusic player to play audio through the device's speakers instead of having to select a Chromecast device?

I'm ultimately trying to use this integration to play You Tube Music through my ceiling speakers instead of having to launch the You Tube Music app on the tablet.

Thanks,
Mike

**Comment by sigma67** [comment]
This is an unofficial project, please contact Google Support: https://support.google.com/
