### ISSUE TITLE
Trying to get random song playlist of Album, Artist and Existing Playlist

### ISSUE THREAD

**Issue by GopiRaghavendraNath** [sigma67/ytmusicapi#207]
I tried taking the shuffleId but it does not seem to work and always gives the same playlist for the Artist and Album name. For example

```
ytmusic = YTMusic()
search_results = ytmusic.search('One Direction', 'artists')
```

would always give me same id no matter what, is there anything I can do to solve this?

**Comment by sigma67** [comment]
https://ytmusicapi.readthedocs.io/en/latest/faq.html#how-can-i-get-the-shuffle-playlist-for-a-playlist-or-album
