### ISSUE TITLE
Is there any way to get album art of a song?

### ISSUE THREAD

**Issue by srevinsaju** [sigma67/ytmusicapi#208]

**Comment by sigma67** [comment]
`get_song` returns a thumbnails property.

https://ytmusicapi.readthedocs.io/en/latest/reference.html#ytmusicapi.YTMusic.get_song

**Comment by srevinsaju** [comment]
Ah, but it looks a bit different from the ones used in youtube music. In youtube music, the covert art is `1:1`, but here it's mostly landscape :thinking:. 

Anyway, thanks!

**Comment by sigma67** [comment]
There should be different sizes offered, it's an array. Did you check all of them? Normally the right one should be part of the response as it's the same request that's used by the web app.

**Comment by srevinsaju** [comment]
Yes, all of them are landscape in the request, for example: even in the example provided by the [documentation](https://ytmusicapi.readthedocs.io/en/latest/reference.html#ytmusicapi.YTMusic.get_song).

In the web app, I am not sure how they do it exactly :thinking:, I cant see any images which match the album art shown on youtube music web app.

**Comment by srevinsaju** [comment]
nvm, I had to use the headers. Thanks again. Sorry for taking your time
