### ISSUE TITLE
*unauthenticated* access to public playlists?

### ISSUE THREAD

**Issue by natumbri** [sigma67/ytmusicapi#211]
Hi,

Is it possible to use ytmusicapi to get access to public playlists *without* authentication?  

For example, this channel `https://music.youtube.com/channel/UCZtGOj7FTHPd2txgnbJS2kQ` has 3 public playlists:
- `PLJD13y84Bd029ENixIHEpDqeWcjiogsFi`
- `PLJD13y84Bd01Q8b8ONfwNMLD3pVBcqwMq` 
- `PLJD13y84Bd032qVrq7CHBLEfKZZtp-u1j`

Is it possible to retrieve a list of those *public* playlists (perhaps by using `YTMusic.get_user_playlists`), without being authenticated?

**Comment by sigma67** [comment]
Yes, of course. Anything you can open in your web browser without logging in works in ytmusicapi as well. You have the right approach with `YTMusic.get_user_playlists` for this channel, then just use `get_playlist` on each of the IDs.

**Comment by natumbri** [comment]
Thanks - I keep getting an error telling me I need to authenticate. I'll keep trying.

**Comment by sigma67** [comment]
That seems strange, can you comment the relevant parts of your code here and the error message? I just tried with your channel id and it works fine.

Might be related to an outdated ytmusicapi version or bad headers you're providing.

**Comment by sigma67** [comment]
Also small correction to my prior comment, you first need to call `YTMusic.get_user`. `YTMusic.get_user_playlists` only applies afterwards when a user has many playlists and you need all of them
