### ISSUE TITLE
Playing music using the api

### ISSUE THREAD

**Issue by Jaiming724** [sigma67/ytmusicapi#212]
Is there a way to play music or skip the current track using the library? I couldn't find anything in the documentations.

**Comment by sigma67** [comment]
It's not the goal of this library, but other people have done it based on this library: https://github.com/KoljaWindeler/ytube_music_player/

The most relevant function for playing tracks is `get_song`, which returns the relevant `streamingData`. https://ytmusicapi.readthedocs.io/en/latest/reference.html?highlight=get_song#ytmusicapi.YTMusic.get_song

Also, please use gitter for questions: https://gitter.im/sigma67/ytmusicapi
