### ISSUE TITLE
How to get the charts data from https://charts.youtube.com/

### ISSUE THREAD

**Issue by YashMakan** [sigma67/ytmusicapi#213]
is it possible to get charts data using this library from https://charts.youtube.com/. I read [this](https://stackoverflow.com/a/44615847/10566556) answer on StackOverflow which is similar to what I want to achieve but it's not working for me. can anyone help?
Thanks

**Comment by sigma67** [comment]
In YouTube Music they're here https://music.youtube.com/charts, but you're right, this is not yet implemented

**Comment by sigma67** [comment]
Feel free to test with the new `get_charts` method

**Comment by YashMakan** [comment]
Thank you so much... Now I can successfully get charts by country. You are amazing... can you also tell me how can I get the specific data from the artist profile like in [here](https://charts.youtube.com/artist/%2Fm%2F06w2sn5) we can get where people are listening and total play graph? Thanks...

**Comment by sigma67** [comment]
That is a cool page but unfortunately it uses a different API endpoint (charts.youtube.com, not music.youtube.com). Therefore I would consider it out of scope for this project. 

Feel free to experiment on your own though, perhaps it can work by modifying the headers a bit. Overall request structure looks fairly similar

**Comment by YashMakan** [comment]
alright, thanks for your time & help. 👍
