### ISSUE TITLE
Cannot find authentications headers

### ISSUE THREAD

**Issue by Lasauce6** [sigma67/ytmusicapi#217]
When i do the steps to get the headers for auth, i cant get any  /browse POST request as shown
![Capture d’écran de 2021-08-10 18-42-33](https://user-images.githubusercontent.com/61377616/128899709-2f39250c-a6e2-4909-9c1a-28ea1adf07da.png)
How can i get the headers or can i get this by cookies and how ?

**Comment by AndreasWidmer** [comment]
@Lasauce6 did you reload / switched the site, after you opened the console?

**Comment by Lasauce6** [comment]
Yeah I've tried reload the page and start from a new tab and it didn't work

**Comment by sigma67** [comment]
Try clicking around a bit on the homepage or in the Explore section while watching the Network tab in the developer tools. It should show up pretty quickly
