### ISSUE TITLE
KeyError: 'watchEndpoint' when using get_library_upload_album()

### ISSUE THREAD

**Issue by Zombee0804** [sigma67/ytmusicapi#219]
Relatively new to using API's so I'm not entirely sure if this is an issue with my code, the API, or youtube. But whenever I use get_library_upload_album() with a browse ID from get_library_upload_albums(), I get a key error that just says 'watchEndpoint'. I have no idea what is causing this. Any help would be appreciated.

**Comment by sigma67** [comment]
I can't reproduce this, can you provide the full error message?
