### ISSUE TITLE
Python 3.5 doesn't seem to be supported

### ISSUE THREAD

**Issue by spidru** [sigma67/ytmusicapi#225]
Hi there,

I'd like to report that I get the following error when trying to use Python 3.5:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/venv/lib/python3.5/site-packages/ytmusicapi/__init__.py", line 2, in <module>
    from ytmusicapi.ytmusic import YTMusic
  File "/home/venv/lib/python3.5/site-packages/ytmusicapi/ytmusic.py", line 10, in <module>
    from ytmusicapi.mixins.browsing import BrowsingMixin
  File "/home/venv/lib/python3.5/site-packages/ytmusicapi/mixins/browsing.py", line 278
    raise ValueError(f"The YouTube Channel {channelId} has no music content.")
                                                                            ^
SyntaxError: invalid syntax
```

My understanding is that f-strings were only introduced in Python 3.6, causing this syntax error. So I guess the README should be updated to "3.6 or higher" rather than "3.5 or higher"?

**Comment by sigma67** [comment]
Hm it seems that one snuck in unnoticed during a recent PR. But Python 3.5 has reached end-of-life, so we should instead up version in the README as you suggested.

https://www.python.org/downloads/

**Comment by spidru** [comment]
Agreed. Let me know if you'd rather I create a PR for this.
