### ISSUE TITLE
Find Subscribed Artists

### ISSUE THREAD

**Issue by sir01g** [sigma67/ytmusicapi#226]
How can I get my subscribed artist. The get_library_artists() doesn't do that.
If I use get_library_artists() it give me fantom 'artists' which isn't exists but at least on song in my library has that as the artist. For example it gives '50 & 50 Brothers' because in my library (from the old Google Play library I guess) there's a song with this fantom artist.
When I apply get_artist() for this '50 & 50 Brothers' I get an error. If I search this 'artist' on Youtube Music I find the sing I have in my library, but not the artist, so it does not exist indeed.

What I want is the list of the artist I subscribed. Then I can search throu these artist for new releases with get_artist()...
Which method I can use for it instead of get_library_artists()?

**Comment by sir01g** [comment]
Answer to myself: get_subscriptions(limit, order) will do it instead of get_library_artists()
I didn't find this method in the documentation at https://ytmusicapi.readthedocs.io/en/latest/reference.html

**Comment by sigma67** [comment]
You're right, `get_library_subscriptions` is missing in the docs. Will fix right away
