### ISSUE TITLE
It's not possible to remove items from collaborative playlists

### ISSUE THREAD

**Issue by nforro** [sigma67/ytmusicapi#23]
As a collaborator, I'd like to be able to remove items from a collaborative playlist.
I'm able to do that with this [change](https://github.com/sigma67/ytmusicapi/commit/c86d4de6621ef91dc0e1098a722151c951255bff), but perhaps there is a better way?

**Comment by sigma67** [comment]
I personally don't use collaborative playlists, but this seems like a sensible change so I'll gladly accept it. Can you submit a pull request so I can test it?

And if I may ask, how did you create a commit on this repo without opening a pull request? Didn't know that was possible.

**Comment by nforro** [comment]
> Can you submit a pull request so I can test it?

Sure, will do.

> And if I may ask, how did you create a commit on this repo without opening a pull request? Didn't know that was possible.

That surprised me too, I forked the repo and pushed a commit to a branch in the fork, and it seems the commit is accessible through the original repo as well. For convenience I suppose.
