### ISSUE TITLE
Asynchronous requests

### ISSUE THREAD

**Issue by georgetian3** [sigma67/ytmusicapi#230]
I've implemented (a very hacky) implementation of ytmusicapi using `aiohttp`, where performing 6 search queries decreased from 6 seconds without async, to 1 second with async.

The speed improvements are great, but I understand some users may not wish to use async in their programs. With this in mind, would you be open to implementing async in the main ytmusic repository? Furthermore, letting the user choose between synchronous and async requests be an option?

**Comment by sigma67** [comment]
This is similar to parallelizing requests, which is something I would prefer to avoid as it might draw unwanted attention from Google (high server load due to much larger amount of requests in a short time window). However, feel free to publish your fork and link it here
