### ISSUE TITLE
sporadic affects

### ISSUE THREAD

**Issue by grimm26** [sigma67/ytmusicapi#232]
I wrote https://github.com/grimm26/ytm_dislike_artist back in January 2021, leveraging ytmusicapi, and it worked fine. It would add a dislike to every song that an artist has. Now it seems to only do so spradically across the artist's catalog. The response from `rate_song()` indicates that it worked, for instance
```
{'responseContext': {'serviceTrackingParams': [{'service': 'CSI', 'params': [{'key': 'c', 'value': 'WEB_REMIX'}, {'key': 'cver', 'value': '0.1'}, {'key': 'yt_li', 'value': '1'}, {'key': 'Dislike_rid', 'value': '0xee88702b06e2a476'}]}, {'service': 'GFEEDBACK', 'params': [{'key': 'logged_in', 'value': '1'}, {'key': 'e', 'value': '24116772,24082662,1714244,23975058,23944779,24049820,23983296,24056274,24100822,24118644,23827039,24080738,23968386,24116744,24106839,24002022,24094773,23934970,24007790,24064555,24034168,23998056,23884386,24118970,23946420,24110902,24118410,23918597,24119172,24085811,23990875,24004644,24077241,24007246,23804281,24036947,24119152,23966208,24094667,24001373,24106921,23744176,23857949,24077266,24110109,24003542,24002025,24101841,24028143,23882503'}]}, {'service': 'ECATCHER', 'params': [{'key': 'client.version', 'value': '0.1'}, {'key': 'client.name', 'value': 'WEB_REMIX'}]}]}, 'actions': [{'clickTrackingParams': 'IhMIu_fYzOXk8wIVh1TtCh0FeAMx', 'addToToastAction': {'item': {'notificationTextRenderer': {'successResponseText': {'runs': [{'text': "Got it, we'll tune your recommendations"}]}, 'trackingParams': 'CAAQyscDIhMIu_fYzOXk8wIVh1TtCh0FeAMx'}}}}]}
```

but checking song one finds that it is not marked with a thumbsdown. It seems to get the first 5 of an album, and then no more, but maybe a couple on the next album. If I manually mark the next one on an album disliked, then it may mark a couple more.

So, either ytmusicapi or the youtube API itself is lying :). Any insights or a way to further dig into this issue?

**Comment by sigma67** [comment]
I'll jot this down as a temporary server-side issue
