### ISSUE TITLE
Error when using YTMusic.get_charts with authenticated user

### ISSUE THREAD

**Issue by BruceZhang1993** [sigma67/ytmusicapi#236]
Step to reproduce
```python
api = YTMusic(HEADER_FILE)
api.get_charts('US')
```

Error info:

Traceback (most recent call last):
  File "/home/bruce/Projects/Python/feeluown-ytmusic/feeluown_ytmusic/service.py", line 84, in <module>
    print(json.dumps(service.get_charts()))
  File "/home/bruce/Projects/Python/feeluown-ytmusic/feeluown_ytmusic/service.py", line 77, in get_charts
    return self.api.get_charts(country)
  File "/home/bruce/Projects/Python/feeluown-ytmusic/.venv/lib/python3.9/site-packages/ytmusicapi/mixins/explore.py", line 235, in get_charts
    'playlist': nav(results[1 + i], CAROUSEL + CAROUSEL_TITLE + NAVIGATION_BROWSE_ID,
IndexError: list index out of range

**Comment by sigma67** [comment]
Hm, the same call works fine for me. I'm suspecting some kind of YouTube update. Can you go to the charts page and screenshot it for me to compare? Or even better, provide a JSON of the response after navigating to the US filtered page? See screenshot.

![image](https://user-images.githubusercontent.com/16363825/143771586-5b878e73-0da5-4160-99ee-7ee9cc91dff6.png)

**Comment by BruceZhang1993** [comment]
@sigma67

**Comment by BruceZhang1993** [comment]
Here is full JSON from the result of _send_request
https://fars.ee/DTCT

Here is full JSON from YouTube Music webpage
http://r.fars.ee/smbj

**Comment by sigma67** [comment]
You are missing the "Top songs" category, which is very unusual. Do you have any idea why that is missing for you?

**Comment by BruceZhang1993** [comment]
totally have no idea why. is it only for my youtube account ?

**Comment by sigma67** [comment]
Not sure, what happens when you access the site while logged out? This is what you should see normally:

![image](https://user-images.githubusercontent.com/16363825/144209606-9afffa61-c76d-463e-8e93-1b42c20b12a4.png)

**Comment by BruceZhang1993** [comment]
@sigma67  I am using youtube music from unsupported regions with vpn. any chance this could be the reason ?

**Comment by sigma67** [comment]
That is most likely the reason. Not sure if it's worth implementing a workaround for this niche case

**Comment by BruceZhang1993** [comment]
> That is most likely the reason. Not sure if it's worth implementing a workaround for this niche case

Thanks a lot anyway, i'll try to find a workaround in my project.
