### ISSUE TITLE
Can't authenticate

### ISSUE THREAD

**Issue by vanth0me** [sigma67/ytmusicapi#239]
Hello all, 

I'm trying to like all songs in a playlist but I keep getting a 403 error. Tried it with Chrome and Firefox headers. 
I assume the playlist id is the part after /playlist?list=

Here is my code, hopefully you guys can help me.

`from ytmusicapi.ytmusic import YTMusic

YTMusic.setup(filepath='headers_auth.json')
ytmusic = YTMusic('headers_auth.json')
ytmusic.rate_playlist(playlistId='PL_5iVIEaUI3-mEdwiXDm7e_OTrIIBSo13', rating='LIKE')`

This is the error: 
Exception: Server returned HTTP 403: Forbidden.
The caller does not have permission

PS. I don't have a lot of Python experience.

**Comment by sigma67** [comment]
The code is fine, 403 means that there is an issue with your credentials. Do you have multiple YouTube Music accounts (brand accounts)? If you want me to debug for you, send your `headers_auth.json` to ytmusicapi@gmail.com

**Comment by vanth0me** [comment]
Thanks, I will send you an email with the json file. As far as I can see there I don't have a brand account.

**Comment by sigma67** [comment]
Oh, well now it's obvious. You're trying to add your own playlist to your library, which is obviously impossible. `rate_playlist` is meant for adding others' playlists to your library.

Your credentials are working fine :) Feel free to log out and log back in to invalidate the credentials you sent me.

**Comment by vanth0me** [comment]
Ah thanks, I thought it was used for rating the whole play list liked (so every song). Do you have an idea for that?

**Comment by sigma67** [comment]
```python
playlist = ytmusic.get_playlist("PL_5iVIEaUI3-mEdwiXDm7e_OTrIIBSo13")
for track in playlist['tracks']:
  ytmusic.rate_song(track['videoId'], 'LIKE')

**Comment by vanth0me** [comment]
Thanks! Had to run it about 20 times but all songs are liked now!
