### ISSUE TITLE
albums with >200 songs

### ISSUE THREAD

**Issue by quantenschaum** [sigma67/ytmusicapi#246]
First, many thanks for this library!

I just discovered that albums with more than 200 songs only list the first 200 entries. ([example](https://music.youtube.com/playlist?list=OLAK5uy_ln_o1YXFqK4nfiNuTfhJK2XcRNCxml0fY))

The official webui also shows only the first 200 songs, but playback in the browser does continue, but the playlist is capped at 200.

The official YTM app does only show the first 200 songs of an album, too. But playback also continues and all songs are shown in the current playlist (not int he album though).

So, what can be done to fix this?

**Comment by sigma67** [comment]
I suppose you can use `get_watch_playlist` in that case to get the full album? Since that API call is responsible for getting the watch playlist contents.

**Comment by quantenschaum** [comment]
I tried this this way 

```python
a=ytm.get_album("some_browse_id")
c=a["trackCount"] # this is the actual number of tracks >200, a["tracks"] is limited to 200
p=ytm.get_watch_playlist(playlistId=a["audioPlaylistId"], limit=c)
```

but this results in

```
Traceback (most recent call last):
  File "./ytmdl", line 385, in <module>
    main()
  File "./ytmdl", line 298, in main
    playlist = ytm.get_watch_playlist(
  File "/home/al/.local/lib/python3.8/site-packages/ytmusicapi/mixins/watch.py", line 95, in get_watch_playlist
    get_continuations(results, 'playlistPanelContinuation', limit - len(tracks),
  File "/home/al/.local/lib/python3.8/site-packages/ytmusicapi/parsers/utils.py", line 58, in get_continuations
    additionalParams = get_continuation_params(results, ctoken_path)
  File "/home/al/.local/lib/python3.8/site-packages/ytmusicapi/parsers/utils.py", line 101, in get_continuation_params
    ctoken = nav(results,
  File "/home/al/.local/lib/python3.8/site-packages/ytmusicapi/parsers/utils.py", line 155, in nav
    raise err
  File "/home/al/.local/lib/python3.8/site-packages/ytmusicapi/parsers/utils.py", line 149, in nav
    root = root[k]
KeyError: 'nextRadioContinuationData'
```

**Comment by quantenschaum** [comment]
When I set the parameter `limit=100`, the same error occurs. When I set `limit=25` or leave it unset, I get 50 tracks in the returned structure.

**Comment by quantenschaum** [comment]
FYI - passing the `audioPlaylistId` to `youtube-dl` causes it to download the playlist, but is limited to the first 100 entries.

**Comment by sigma67** [comment]
Good catch, that's a bug. I didn't consider audio playlists as possible inputs for the playlistId parameter. Will fix soon.

**Comment by quantenschaum** [comment]
Cool, seems to work.
