### ISSUE TITLE
Cannot access uploaded songs from ytmusicapi

### ISSUE THREAD

**Issue by strotta93** [sigma67/ytmusicapi#249]
Hi,
as written in the title, I cannot manage to access my uploaded songs from ytmusicapi.
In my account, that was fresh created some days ago (so no Google Play Music old stuff), there are 9 songs uploaded from my PC, coming from an album that really exists (and that I legally own since I bought the digital copy)... but that for some reason is not present in the YouTube Music catalog.
When I try to access the songs from Mopidy (with the Mopidy-YTMusic plugin, that I'm quite sure is not the problem, but I'm reporting for sake of clearness), a 400 Bad Request error is returned, with the only explanation - in the response body - that "Request contains an invalid argument".
During my various attempts to solve the problem, I also faced the same error when trying to go to the album's artist screen on YouTube Music and recording the network traffic by Inspect Element, but when I invalidated the cache and reconnected to YTM (on my browser I have like three Google accounts linked) the issue went away... on the browser.
When calling the API, instead, there is no hope that the API call gives a 200 OK. The same request, now, even when called via cURL after that I recorded it again by Inspect Element, is successful... but with the API I have no success.

Feel free to ask any question you want or to request any detail you might think is needed to troubleshoot the problem.

Thanks,
Silvio

**Comment by sigma67** [comment]
This is most likely an issue with your headers. I suggest redoing the setup procedure in Mopidy to create a new set of headers. The ytmusicapi call is working fine, as I just verified. If you're still having issue, please raise an issue with the project you're using (Mopidy).
