### ISSUE TITLE
get_playlist with over 1,000 songs valueerror exception

### ISSUE THREAD

**Issue by hibby50** [sigma67/ytmusicapi#25]
Hey, thanks for this awesome API, I'm using it to write some simple scripts for my library. I ran into an issue when I tried to run get_playlist() on a pl with >1,000 songs. Looks like the comma needs to be stripped out of the song count.

Traceback (most recent call last):
  File "simple-playlist-maker.py", line 38, in <module>
    pl_tracks = ytmusic.get_playlist(playlist, 9999)["tracks"]
  File "/home/hibby/.local/lib/python3.8/site-packages/ytmusicapi/ytmusic.py", line 732, in get_playlist
    song_count = int(header['secondSubtitle']['runs'][0]['text'].split(' ')[0])
ValueError: invalid literal for int() with base 10: '1,149'

**Comment by sigma67** [comment]
Good catch! And simple to fix as well as you pointed out.
