### ISSUE TITLE
`browseId` is null and `params` is missing from `get_artist()` for albums

### ISSUE THREAD

**Issue by DevonHope** [sigma67/ytmusicapi#253]
`get_artist_albums()` requires a `channelId` or `browseId` and a `params` string in order to serve the albums from a selected artist, but when I query the `get_artist()` function in order to get the `params` string for the albums section, the `params` variable is missing from the dictionary. I tried using the singles `params` variable, but when i call `get_artist_albums()` with the singles `params` variable, it returns the singles for the artist. This is to be expected but why are the `browseId` and `params` strings not available in the dictionary that is returned by `get_artist()`. 

Dump of dictionary for artist Kevin Morby shows the `browseId` field is null and the `params` field is non existent.
`"albums": {`  
        `"browseId": null,`  
        `"results": [...]`  
            `}`

Please let me know if anyone else is having this issue or if I'm using the API wrong. Thanks!

[artists_dump.txt](https://github.com/sigma67/ytmusicapi/files/7917647/artits_dump.txt)

**Comment by sigma67** [comment]
YouTube Music only provides a `browseId` if an artist has more than 10 singles/albums. You can check the web app to find that Kevin Morby has only 8 albums, hence no `browseId`. These 8 albums should be returned by `get_artist` without any additional calls.
