### ISSUE TITLE
Search limit

### ISSUE THREAD

**Issue by Drimkaa** [sigma67/ytmusicapi#269]
Hi, can you explain how the search works with setting a limit? (I'm just trying to do something similar to node.js)

**Comment by sigma67** [comment]
Limit only works if you have some kind of filter (i.e. `songs`). The default number of songs being returned is 20. If you set the limit value to a value higher than that, ytmusicapi will keep asking the server for continuations until your limit parameter is reached. So say you put `limit=50`, it will return 60 song results.

You can check the code below. `get_continuations` is a generic function that's being used by all methods that have continuation logic, so check that if you want to know how continuations work in general.
https://github.com/sigma67/ytmusicapi/blob/1d30910e23f24a77755a46c59f14382bebb32eb5/ytmusicapi/mixins/browsing.py#L289-L298

**Comment by Drimkaa** [comment]
Thanks, it helped.
