### ISSUE TITLE
Return thumbnails in search results parser

### ISSUE THREAD

**Issue by dajwill** [sigma67/ytmusicapi#27]
It looks like a `thumbnail` property is available in the response of the search endpoint. Kind of a selfish request for a personal project, but it would be nice/help to verify songs you are adding to a playlist.

![image](https://user-images.githubusercontent.com/8634751/82964354-42ec1b00-9f93-11ea-8c63-03dc8070e1d4.png)

**Comment by sigma67** [comment]
I think this would be a great addition to many methods. The data is always included in the response (unless the song is unavailable), so it just needs to be included in the return value.

Feel free to submit a pull request if you have time to work on it. Might be a few days or weeks until I get around to it
