### ISSUE TITLE
Authentication Errors: Headers not present in /browse

### ISSUE THREAD

**Issue by Zaedus** [sigma67/ytmusicapi#270]
I'm not sure if this is a new change to the Youtube Music api, but I can't seem to reauthenticate myself. When I copy the headers from the `/browse` request, I end up with this
```
Exception: The following entries are missing in your headers: x-goog-authuser. Please try a different request (such as /browse) and make sure you are logged in.
```

I'm not sure if I'm just doing something wrong, or if this is a change to how Youtube handles authentication.

**Comment by cyperdark** [comment]
```json
{
  "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0",
  "Accept": "*/*",
  "Accept-Language": "en-US,en;q=0.5",
  "Content-Type": "application/json",
  "X-Goog-AuthUser": "1",
  "x-origin": "https://music.youtube.com",
  "Cookie": ""
}
```

copy cookie value and paste it

**Comment by sigma67** [comment]
Normally your request headers should include a value "x-goog-authuser" to indicate which of your Google brand accounts you're signed in to.  For some reason yours doesn't, but you can just manually create a new entry in your copied headers with the value "0" and it should work.

Do you have any other brand accounts on your Google account? You can tell by clicking your user icon, then Switch Accounts.

**Comment by Zaedus** [comment]
So sorry for the late response. Do I need a google account for this or can I access it as a guest?

**Comment by Zaedus** [comment]
Oh. My. God. I am so sorry! I thought it was necessary to get the headers for both unauthenticated and authenticated requests! That is 100% my bad. Enjoy the rest of your day and thank you for sticking with me here :)
