### ISSUE TITLE
Unable to get all singles for artist

### ISSUE THREAD

**Issue by fabi321** [sigma67/ytmusicapi#274]
I am unable to get all singles for an artist. I only get the first few, and the call to `get_artist_albums` fails.
```python
from ytmusicapi import YTMusic
yt = YTMusic()
artist = yt.get_artist('UCNms80n59AltHVQuPgGrKkg')
len(artist['singles']['results']) # -> 10
singles = yt.get_artist_albums(artist['channelId'], artist['singles']['params'])
type(singles) # -> <class 'NoneType'>
```

**Comment by sigma67** [comment]
Works flawlessly for me. It's normal that `get_artist` only returns the first few. You need to fix your call to `get_artist_albums`:

```python
yt.get_artist_albums(artist['singles']['browseId'], artist['singles']['params'])
```

See tests here: https://github.com/sigma67/ytmusicapi/blob/7e5697596ce54ce229b245e685252f92081481d8/tests/test.py#L108-L111
