### ISSUE TITLE
Add call to retrieve all of your playlists

### ISSUE THREAD

**Issue by Auzzy** [sigma67/ytmusicapi#275]
Currently, to get all of your playlists if you don't know how many you have, you have to iterate guessing and seeing if the count returned is less than you asked for. It would be a nice convenience for ytmusicapi to accept a limit of `None` to indicate this.

**Comment by sigma67** [comment]
This is definitely a useful feature, but should be implemented consistently for all endpoints that have a finite amount of continuations. Others I can think of

- `get_library_songs`
- `get_library_albums`
- `get_library_artists`
- `get_library_subscriptions`
- `get_liked_songs`
- `search` - filter categories only, and could potentially run for a very long time depending on the search term
