### ISSUE TITLE
Is it possible to access alternate versions of albums?

### ISSUE THREAD

**Issue by Zombee8424** [sigma67/ytmusicapi#279]
YouTube Music is very inconsistent with how it distinguishes standard and deluxe albums:
* Sometimes the deluxe and standard versions of an album are separate
* Sometimes the standard version is the default, and the deluxe version is listed under 'Other Versions' (e.g Nicolas Jaar, Sirens)
* Sometimes the deluxe version is the default, and the standard version is listed under 'Other Versions' (e.g Black Country, New Road, Ants From Up There)

I didn't know if it was possible to access the 'Other Versions' with the API, in the second two cases? If I search for the Nicolas Jaar album listed above, filtering by albums, only the standard version of the album is in the search results. However, I understand that may be out of your hands entirely if the information is not provided by the other YouTube API.

**Comment by sigma67** [comment]
The "other versions" must be a recent addition, I wasn't aware of that before. It can be parsed by ytmusicapi, just needs to be implemented.

Links for reference:
https://music.youtube.com/playlist?list=OLAK5uy_nB4imMaxSWGlcpkM6iIHOtwy5_S6iQyJA
https://music.youtube.com/playlist?list=OLAK5uy_nIXd09Yl0sIiYiuo71Up4P6VAImh35CkY
