### ISSUE TITLE
please i want to know authenticated request 

### ISSUE THREAD

**Issue by kidmil** [sigma67/ytmusicapi#28]
hi i'm interested in this api
but, i don't understand below word

Go to the developer tools (Ctrl-Shift-I) and find an authenticated POST request. You can filter for /browse to easily find a suitable request.

i open ytm in firefox. then input ctrl+shift+i. 
how can i find an authenticated POST request...?
and this step is before login ytm or  after login ytm?

**Comment by sigma67** [comment]
First you log in to YouTube Music, then you press Ctrl-Shift-I and click on the library tab. Copy the request headers as shown in the screenshot (Network tab):

![image](https://user-images.githubusercontent.com/16363825/83436559-5b9a7c00-a43e-11ea-84b6-2855ef0c9272.png)

**Comment by Devam153** [comment]
Hi @sigma67,
I'm currently working on a project that focuses on synchronizing data across various music applications. and I've run into a bit of a roadblock when it comes to authenticating with YouTube Music via the ytmusicapi.
I did my best to follow the steps provided on the website, but I seem to be stuck at the point where I need to find the URL as mentioned. It's been a bit of a puzzle, and I was wondering if you could offer some guidance or share any insights you might have on this matter.

**Comment by sigma67** [comment]
Hi @Devam153 , please ask in Discussions Q&A section. I think the screenshot is pretty clear, just click around a bit and filter by browse

**Comment by Devam153** [comment]
Sorry for asking you here @sigma67 ,
I really appreciate your assistance.
Thanks to your help, everything is now working perfectly fine.
Thank you so much!
