### ISSUE TITLE
Add audio quality control

### ISSUE THREAD

**Issue by max5354** [sigma67/ytmusicapi#280]
I don't know is this possible or not but i am just asking. Will you add "audio quality" option. So user can change audio quality like 128kbps, 164kbps and 256kbps. So if i implement this audio quality option than user can listen songs at 256kbps for free.

**Comment by sigma67** [comment]
https://ytmusicapi.readthedocs.io/en/latest/reference.html?highlight=get_song#ytmusicapi.YTMusic.get_song

The bitrate of the adaptive formats differs based on the authentication credentials you're using. So no, it's not possible to listen to higher quality streams without a subscription.
