### ISSUE TITLE
Choosing to get album tracks in "song mode"

### ISSUE THREAD

**Issue by SubjunctiveQuaver** [sigma67/ytmusicapi#281]
By default, YouTube Music puts albums in "video mode", so it plays music video versions when available. These versions are shown in the album details when requested by the API.

But there is also a "song mode" which always keeps album tracks, which I would prefer for a project I am working on (and it removes the need to re-search for song versions; sometimes the track titles change etc.), if it can be implemented into the API somehow? Or is there a way to access these from the existing output of the `get_album` function?

**Comment by sigma67** [comment]
I believe this depends on whether you are signed into a premium account or not. Non-premium accounts are served videos whereas premium accounts are served songs by default.

**Comment by SubjunctiveQuaver** [comment]
That's annoying! So I suppose you would need an authenticated account? (Also not sure since it's definitely a setting in YT music premium, not sure if it will by default return song mode...)

**Comment by sigma67** [comment]
I'm not aware of a setting to show videos instead of songs, please point it out?

If you are authenticated doesn't matter, only if you have premium or not.
