### ISSUE TITLE
Document X-Goog-PageId

### ISSUE THREAD

**Issue by desttinghim** [sigma67/ytmusicapi#283]
Context: I am setting up mopidy-ytmusic on NixOS. There isn't access to mopidyctl for some reason, so I've had to manually fill out the `auth.json`

I was having a strange issue where authentication was succeeding, but I wasn't getting back the correct data for my account. I think the problem is that I've accidentally been using a brand account for my music. I attempted to follow the ytmusicapi [FAQ](https://ytmusicapi.readthedocs.io/en/latest/faq.html) to resolve this, but changing the AuthUser just made authentication fail. However, I noticed the `X-Goog-PageId` had the same value as my brand id, so I went back to my previous `auth.json` and added the `X-Goog-PageId` field. Everything seems to work now! 

I haven't seen any info on this particular scenario, so I'm creating this issue to have the X-Goog-PageId field documented.

**Comment by sigma67** [comment]
I don't think the `X-Goog-PageId` field is even required, for my requests from brand accounts it works just fine without. 

Do you think it is needed?
