### ISSUE TITLE
Not all channels have a 'musicImmersiveHeaderRenderer'

### ISSUE THREAD

**Issue by Yamboy1** [sigma67/ytmusicapi#284]
Running
```py
from ytmusicapi import YTMusic
ytmusic = YTMusic("headers_auth.json")
ytmusic.get_artist("UChTTUKuugGqU4F0UblZF5Kw")
```

causes this KeyError
```py
Traceback (most recent call last):
  File "app.py", line 12, in <module>
    ytmusic.get_artist("UChTTUKuugGqU4F0UblZF5Kw")
  File "/home/user/project/venv/lib/python3.8/site-packages/ytmusicapi/mixins/browsing.py", line 213, in get_artist
    header = response['header']['musicImmersiveHeaderRenderer']
KeyError: 'musicImmersiveHeaderRenderer'
```

It appears that channels which only have videos, and not songs, have a less featureful 'musicVisualHeaderRenderer' instead of the normal 'musicImmersiveHeaderRenderer', without shuffle, radio and subscribe buttons. I was hoping this would be a quick fix, but the channel id is obtained from the subscribe button for some reason, which seems to complicate things slightly.
![image](https://user-images.githubusercontent.com/37413895/181432558-22c7083f-b192-4e2d-9c15-f435112fa9ae.png)

**Comment by sigma67** [comment]
It's because this is not an artist, it's a user. You need to use [`get_user`](https://ytmusicapi.readthedocs.io/en/latest/reference.html?highlight=get_user#ytmusicapi.YTMusic.get_user).
