### ISSUE TITLE
Uploads search not working

### ISSUE THREAD

**Issue by jskills** [sigma67/ytmusicapi#285]
Running this one line works only when removing the "scope" parameter.  If I want to limit my search to files I have uploaded, it fails.

`results = ytm.search(query='love', filter='songs', scope='uploads', limit=20)`

```
Traceback (most recent call last):
  File "simple.py", line 5, in <module>
    results = ytm.search(query='love', filter='songs', scope='uploads', limit=20)
  File "/home/jskills/.local/lib/python3.6/site-packages/ytmusicapi/mixins/search.py", line 157, in search
    results = nav(results, SECTION_LIST)
  File "/home/jskills/.local/lib/python3.6/site-packages/ytmusicapi/navigation.py", line 72, in nav
    raise err
  File "/home/jskills/.local/lib/python3.6/site-packages/ytmusicapi/navigation.py", line 66, in nav
    root = root[k]
KeyError: 'contents'
```

**Comment by jskills** [comment]
This had been working just fine, but stopped a few months ago - presumably to a change on Youtube's end ... ?

**Comment by sigma67** [comment]
This query can't work because there are no filters for upload search (see web interface). If you remove  the filter param it will work fine. Though I guess we could add some sort of exception if filters are used in combination with the "uploads" scope.

**Comment by jskills** [comment]
Thanks for the reply.  

I have a set of processes that I have written that locate files I have uploaded to YTMusic to automate playlist building.  This same query used to work just fine, so I assume YT changed something on their side.

Anyway, if I wanted to query uploads only, are you saying if I used "scope=uploads" I have to pull them all down (since I cannot filter) and then do any queries locally?

**Comment by sigma67** [comment]
Of course you can filter with a text query, but you cannot filter by the `filter` param. So while your query may have worked in the past, the filter=songs argument never did anything. I suspect that as a result of some changes to ytmusicapi or YouTube Music the faulty query no longer works. So just leave out filter=songs and you're good.

**Comment by jskills** [comment]
Hey this is super helpful.  Thank you very much,  You do are great job as owner of this repo BTW :)

**Comment by sigma67** [comment]
Thanks! Added a little exception as well.
