### ISSUE TITLE
Correcting errors in Instructions

### ISSUE THREAD

**Issue by Nelliosis** [sigma67/ytmusicapi#286]
In the Edge/Chromium section of 'copy authentication headers' of the Docs:
- set **Type** to `fetch` instead of `xhr`. 
Rationale: fetch is what appears in Edge as of 103.0.1264.71 (Official build) (x86_64)

In the 'macOS Special Pasting Instructions' of the Docs:
- 2nd bullet is incorrect. When followed as instructed, the command will become `pbpaste | python Setup.py youtube` and the terminal will return nothing and the program will end. However, when the command is suffixed, it works as intended. See command below. Propose to replace *prefixing* to *suffixing*. Match wordings accordingly. 
- Propose example code for pbpaste such as:
`python Setup.py youtube | pbpaste`
Rationale: Easier to understand with example

In Setup.py 
- Instruction to use `ctrl + d` returns `BrokenPipeError: [Errno 32] Broken pipe`. Upon checking the code and using `ctrl + z` code worked as intended.  

I can provide screenshots and recreate the errors if requested.

My Environment: 
macOS 11.6.8
Edge 103.0.1264.71 (Official build) (x86_64)
Terminal version 2.11 (440) 
Bash version 5.1.16(1)-release (x86_64-apple-darwin20.6.0)

Also, thank you for this utility, I found it incredibly useful :)

**Comment by sigma67** [comment]
The type of the request is irrelevant, so yes, that can be removed.

The macOS instructions were added in #150, and pbpaste _prefixing_ is correct - data flows from left to right in Unix instructions. However, I agree that an example would be helpful.

Ctrl (or cmd on Mac) + D sends EOF in the MacOS terminal, which is what's needed here. Did you press Enter after pasting? For me it only works when Ctrl-D is pressed on an empty line. That could also be added to instructions.
