### ISSUE TITLE
create_playlist() missing 1 required positional argument: 'self'

### ISSUE THREAD

**Issue by chuyanku** [sigma67/ytmusicapi#287]
Hi, I use this API for making playlists automatically.
using Google Colaboratory.

I have a problem with creating a playlist. 

After succeeded in `YTMusic.setup(filepath="headers_auth.json")`, 
I tried these codes; 
```
YTMusic.create_playlist(title='API TEST 1', description = "description for API TEST 1")
```

It has Error; 
```
TypeError                                 Traceback (most recent call last)
[<ipython-input-21-48e5eff91149>](https://localhost:8080/#) in <module>()
----> 1 YTMusic.create_playlist(title='API TEST 1', description = "description for API TEST 1")

TypeError: create_playlist() missing 1 required positional argument: 'self'
```
What should I assign the value `self` ?

Please tell me how to avoid this problem.

Thank you

**Comment by sigma67** [comment]
It seems you are new to Python. Please follow the instructions step by step.

https://ytmusicapi.readthedocs.io/en/latest/usage.html
