### ISSUE TITLE
Ability to request a range of songs in a playlist

### ISSUE THREAD

**Issue by AntonBogun** [sigma67/ytmusicapi#288]
I have just started using this API and it looks like there is no way to only request a specific range of songs in a playlist rather than all the songs from `0` to `n*100` (rounded up `limit/100` in `get_playlist` from my initial testing).
From what I understand the functionality in youtube's actual API should be there as the songs load in batches of 100s in large playlists, and I am assuming the previously loaded songs are not discarded in the process.

**Comment by sigma67** [comment]
You can only load the playlist incrementally starting from the first entry, as in the web interface. Getting a subset of the loaded items is as simple as using Python array slicing syntax `[:]`
