### ISSUE TITLE
The title of some videos are different than how they are displayed in YT Music.

### ISSUE THREAD

**Issue by CompuGenius** [sigma67/ytmusicapi#290]
The title of some videos are different than how they are displayed in YT Music.

For example: [Danza Kuduro](https://music.youtube.com/watch?v=BbWY-avjDto)
In YT Music, the title is `Danza Kuduro (feat. Lucenzo)`, however in the data that ytmusicapi gets in `ytmusic.get_song()`, the title is `Danza Kuduro`.

Now, obviously that's not a major difference, I'm just curious what's the reasoning for the discrepancy and how I can fix it?

**Comment by sigma67** [comment]
So to explain the difference you need to understand how the web interface works.

When you click Play on a video, two POST requests happen to the main YouTube Music  API (disregarding all the image/video/log requests). 

- The first request is to the `player` endpoint, which is represented by `get_song` in ytmusicapi. This is mainly used to get streaming information, but provides a bunch of other metadata as well
- The second request is to the `next` endpoint, which has the main purpose of fetching the watch playlist - i.e. the next videos to be played in order. This request is represented by `get_watch_playlist`. This playlist also contains the metadata for the original song which is shown in the UI at the end

Perhaps the documentation should be a little more clear on this point, but for your case you should instead use `get_watch_playlist`.

**Comment by CompuGenius** [comment]
Thank you! I will check whether your suggested function is appropriate for my use case, otherwise a small discrepancy should be fine.

**Comment by sigma67** [comment]
Otherwise you can always use both requests in parallel, it's what happens in the web interface anyway.
