### ISSUE TITLE
Breaking value in Chrome cookie for auth

### ISSUE THREAD

**Issue by scrimshander** [sigma67/ytmusicapi#294]
Just had to refresh my auth headers after many many months, and kept getting a missing key bug in the cookie, pasted from Chrome/developer tools.

Turns out this key/value: 

`YT_CL={\"loctok\":\"APLXd64Le9G-vJVqzKjy-OsOVBh6NfU2xKnD6awbKB9lJUXzvHGMuNBmjOpK5q_K xVqxgIRcjI_FC27tj-wmyhvUgW8g4A\"};`

Was breaking the cookie parser (perhaps because of the quotes or the embedded dict). Removing it from the headers text fixed the issue.

**Comment by sigma67** [comment]
This seems strange, your cookie value is not escaped properly. Can you please paste the original `YT_CL` headers from Chrome? Excluding the identifying `Cookie` entry and any private information in there, it's not relevant here.

**Comment by JohnHKoh** [comment]
Same issue here - in the Chrome DevTools, the cookie looks like:

```
YT_CL={"loctok":"stringofchars"};
```

Before, I was receiving the error: "Exception: Your cookie is missing the required value __Secure-3PAPISID". But after removing the "YT_CL" cookie, it started to work again.
