### ISSUE TITLE
YTMusic.subscribe_artists() does not subscribe, but only adds it to the subscriptions list

### ISSUE THREAD

**Issue by shuyec** [sigma67/ytmusicapi#297]
I'm trying to use `YTMusic.subscribe_artists(["UC5OrDvL9DscpcAstz7JnQGA"])`, but I've noticed that it only adds the artist to the subscriptions list. It shows up correctly with `YTMusic.get_library_subscriptions`, but the actual webpage looks like this:
![Screenshot 2022-09-20 150208](https://user-images.githubusercontent.com/76391491/191265526-32b8db08-08b6-4431-8b30-e93e5c0905d8.jpg)

It is in the list but not actually subscribed. You can also see this with `YTMusic.get_artist` because the "subscribed" key is false.

**Comment by sigma67** [comment]
Not to discredit your observation, but this endpoint has been working and unchanged for a very long time. In my tests right now there were no issues.

Are you sure you're using the same account for all your tests? You might be subscribing with an unauthenticated account and checking subscriptions with a different instance. Your syntax also seems odd, as you're using the `YTMusic` class, not an instance. Alternatively, please provide more of your code.

**Comment by shuyec** [comment]
I'm sorry, I found the mistake and it was my bad. I was actually subscribing using the `browseId` "UCoIOOL7QKuBhQHVKL8y7BEQ" from the search results and not the `channelId` "UC5OrDvL9DscpcAstz7JnQGA". 
They are not interchangeable. If I subscribe with the `browseId` I can't unsubscribe with `channelId`

Subscribing using the `browseId` adds it to the subscriptions but does not subscribe.
``` python
ytmusic = YTMusic('headers_auth.json')
# ytmusic.subscribe_artists(["UCoIOOL7QKuBhQHVKL8y7BEQ"])     # BAD
ytmusic.subscribe_artists(["UC5OrDvL9DscpcAstz7JnQGA"])     # GOOD
```
Thanks for the reply.

**Comment by sigma67** [comment]
It's an interesting case because you can access the page with either ID under `music.youtube.com/channel/ID`. Where did you find the other `channelId`? I.e. the one not from the search results.

**Comment by shuyec** [comment]
``` python
ytmusic.search(query="michael jackson", filter="artists")
```
This returns "UCoIOOL7QKuBhQHVKL8y7BEQ" as a browseId.

``` python
ytmusic.get_artist("UCoIOOL7QKuBhQHVKL8y7BEQ")
ytmusic.get_artist("UC5OrDvL9DscpcAstz7JnQGA")
```
Both of these two return the artist, but the first has some missing informations like `shuffleId` and `radioId` which are null.
If I use the website, it navigates me to "https://music.youtube.com/channel/UCoIOOL7QKuBhQHVKL8y7BEQ" so it uses the search browseId.

**Comment by sigma67** [comment]
Right, but where did you get this one? `UC5OrDvL9DscpcAstz7JnQGA`

**Comment by shuyec** [comment]
``` python
ytmusic.get_artist("UCoIOOL7QKuBhQHVKL8y7BEQ")
ytmusic.get_artist("UC5OrDvL9DscpcAstz7JnQGA")
```
From here, they both have "UC5OrDvL9DscpcAstz7JnQGA" as channelId

**Comment by sigma67** [comment]
Ah, it seems each channel indeed has two IDs of the same format. Just a bit confusing that they are in the same format, despite being used for different purposes
