### ISSUE TITLE
get_history() fails

### ISSUE THREAD

**Issue by atlasrule** [sigma67/ytmusicapi#298]
Function get_history() started returning empty array, while history is not empty. No authentication problems.

Program raises this:
Item 2: 'overlay'
Item 3: 'overlay'
Item 2: 'overlay'
Item 3: 'overlay'
.
.

**Comment by sigma67** [comment]
I'm not seeing this issue on my end. Has the response format changed?

**Comment by atlasrule** [comment]
Hi @sigma67, first thing came to my mind was response format change, haven't checked the code for weeks prompted that my authentication has expired, probably due to logout. Faced the issue after I renewed my credentials. But I can't say if there's any format change.

**Comment by sigma67** [comment]
merged in 7de7ecf
