### ISSUE TITLE
The repository needs contributing guidelines

### ISSUE THREAD

**Issue by hematogender** [sigma67/ytmusicapi#3]
Hey! Thanks for this project, searched for YTM API a while ago and couldn't find anything.

I needed some API actions for my use case, so I successfully reverse-engineered the following YTM functionality:
- retrieving added albums from library,
- adding an album,
- removing an album,
- getting album info,
- getting top N songs from an artist page

and two functions for getting playlistIds from browseIds for artists and albums, which are respectively needed for retrieving artist page and manipulating albums in library.

---

So, given that, we need to write the rules/info on **how should the perfect PR look**:
- what Python formatter to use,
- how to write documentation (also formatter?),
- the need for adding tests for new functions,
- where to put helper functions (such as those two I mentioned above),
- how to name functions etc.

Once again thank you 😄

**Comment by hematogender** [comment]
If you don't mind, my suggestion would be to use [black](https://github.com/psf/black) as a Python formatter. It would play nice in this project, especially, because of the need to specify numerous JSON keys in every API call. Black would make it much easier to go through such parts in code, while also improving the spacing.

Despite the formatter we choose, it would be really nice to add an action hook (or what would you call it?) to check/format all PRs automatically. If you know how to do it, of course, because I don't 😃

**Comment by sigma67** [comment]
Hey, great to hear that you've been working on the artist and album pages. I've actually made an outline myself for function calls the library should offer. To not clutter this thread, I created a separate Issue: #4 
I suggest we continue the discussion there. Feel free to submit a pull request with your existing work when you think it's ready.

As for the contributing guidelines:
-    **Python formatter:** I'll follow your suggestion regarding black, since I haven't worked with any formatters beyond the code formatting intellij offers. I'll agree that it's kind of a mess right now with the JSON parsing, since the YT Music API isn't really meant to be used like this. I assume this means reformatting existing code as well? For pull request formatting there's this: https://github.com/lgeiger/black-action. I've set up an action for PyPi so I should be able to figure that out
-    **Documentation:** I suggest to use the current documentation as guidance. It's built using Sphinx and readthedocs. When you add a new method you should also add a corresponding entry in the reference and describe the returned data structure (or link to another method if it's similar)
-    **Tests**: Like with documentation, when a new function is added there should be a corresponding unit test in test.py
-    **Helper functions**: Currently just use helpers.py. As the project grows there might be a need to create more files, but right now I think it's fine
-    **Function naming**: I'm trying to model the function names after gmusicapi, since lots of gmusicapi devs are likely to migrate here once Google Music shuts down. Although I think the naming is pretty straightforward when you look at what's already in the library

**Comment by sigma67** [comment]
So I've tried black and I'm not sure I like what it does. 

It seems like the formatting of the dictionary entries is pretty random, and it's more readable before formatting with black.

Before:
![image](https://user-images.githubusercontent.com/16363825/78540200-1407c300-77f4-11ea-832a-c6d701ccbf36.png)

After:
![image](https://user-images.githubusercontent.com/16363825/78540139-f9cde500-77f3-11ea-8a9d-56c3343e2c42.png)

**Comment by hematogender** [comment]
Sorry for the silent treatment :D I won't have much time now, sadly, but I still have some code you have not implemented yet, so I would like to make a contribution.

The problem is, I use VS Code and it doesn't have the default formatter you are talking about. I have to choose between autopep8, yapf and black. Yapf looks good, shall we use it? I can make a PR now with yapf formatted code.

**Comment by sigma67** [comment]
No problem. Yes, I think yapf is fine. Could you give a quick overview (like function signatures) here on what you plan to contribute? Maybe I can give some feedback in advance.

As for sphinx, there's a little bit of setup involved. You need to `pip install sphinx sphinx-rtd-theme`, then run `sphinx-quickstart` in the docs folder. With that you can create a batch or makefile depending on your system. Afterwards you can run `make.bat html` (Windows) to generate the html docs. The actual readthedocs documentation is generated directly from the master branch on Github.

**Comment by hematogender** [comment]
Okay, so I checked the newest release again, and turns out you implemented everything I had for the API 😆 Good job, appreciate it! Anyways, I think we saved some time this way, because some parts of my implementation would have required a few rounds of refactoring with your feedback.

Now, as of sphinx... I made some research and here's the problem: I had to execute ``sphinx-quickstart`` to make a batch file (``Makefile`` is in the repo, but I'm on Windows). So I launched that, and turns out it won't create the ``make.bat``, because the ``conf.py`` is already present. There are two solutions: either to delete the file and set up everything by yourself (imagine every contributor would need to do that), or to figure out how to launch the ``sphinx-apidoc``/``sphinx-build`` properly to build everything as needed for this project (I couldn't).

And I still want to clarify a few parts in the documentations, so I once again would ask for your help: either to include the ``.bat`` file in the repo, or to set up automatic docs generation action.

As of the latter, I found two ways of doing it:
- [google-music API](https://github.com/thebigmunch/google-music/runs/637199373?check_suite_focus=true) project, which uses nox to lint and to generate docs automatically.
- alternatively, there is a neat [pre-commit framework](https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/).

I obviously find the second option (to set up automatic docs generation, I mean) more appealing, because it could resolve many problems we currently have: the need to use linter, formatter and docs generator (flake8, yapf, sphinx+rtd respectively). It would be a huge weight off the potential contributor's shoulders, which means they will only have to change the actual code/functions comments, and not to think about all the other stuff going on.

Docs generation could be set up with nox (or maybe there are other ways), and flake8+yapf could be set up with pre-commit. Also, nox could be used to automate the testing process, which would be nice, too.

I mean, this is a vast amount of work to do, and it is totally up to you to make the decision. It may aswell be an overkill for this project at the current stage, I just found this practices during my research on the topic, and figured I will share my thoughts with you. Let me know what you think, I am willing to help you all I can.

**Comment by hematogender** [comment]
I see you are working on more serious improvements, so I will try to take care of the stuff I mentioned here (except testing, I'm not experienced enough for it). It is not that hard eventually, I already implemented the documentation part, without nox even, which turned out much faster. I am going to work on the linting/formatting part on the following days.

**Comment by sigma67** [comment]
Thanks for your efforts! I've faced the problem as well that you need to run "pip install" on the project every time before building documentation. Let me know if you find a way around this, it's a small annoyance.

**Comment by hematogender** [comment]
So, #12 added three dependencies for the development environment: ``pre-commit``, ``yapf`` and ``flake8``.

As I understand, it is considered a standard to keep dependencies for users in ``requirements.txt`` and for developers in ``requirements-dev.txt``, so that they could be installed with a simple ``pip install -r requirements[-dev].txt``. Could you do that, please? I planned to write a few sentences for this issue (The repository needs contributing guidelines) in README, but I already spent much more time on GitHub than I could allow myself to 😢 ``requirements-dev.txt`` would solve this problem for now.

As of the problem you described in your last message, I don't know, really. Maybe you could you elaborate on it a little?

**Comment by sigma67** [comment]
Hey, I used setup.py to avoid cluttering the root with even more files (see [here](https://stackoverflow.com/a/28842733/5726546)). Hope that's alright for you

**Comment by hematogender** [comment]
Amazing, thank you! The way you did it is even better :)
