### ISSUE TITLE
get_library_playlists(), get_library_songs() and other get_library functions failing

### ISSUE THREAD

**Issue by jake-g** [sigma67/ytmusicapi#301]
Hi, I'm running into an issue specific to the get_library functions and struggling to find a workaround

Ive tried many other 'get_*' i.e., get_song() get_history() api calls and they all seem to work. It is the get_library functions that are failing.

Ive updated the py packages, regenerated my creds and the code im using has worked fine in the past...
Im guessing something changed on the youtube music side
(my last issue was https://github.com/sigma67/ytmusicapi/issues/173, my account seems to get early updates)

Example
```
from ytmusicapi import YTMusic
yt = YTMusic('../headers_auth.json')
yt.get_library_playlists()
```

results in the following error trace: 
(other get_library commands end in a similar TypeError: `'NoneType' object is not subscriptable

```
File /usr/local/lib/python3.9/site-packages/ytmusicapi/mixins/library.py:31, in LibraryMixin.get_library_playlists(self, limit)
     27 response = self._send_request(endpoint, body)
     29 results = find_object_by_key(nav(response, SINGLE_COLUMN_TAB + SECTION_LIST),
     30                              'itemSectionRenderer')
---> 31 results = nav(results, ITEM_SECTION + GRID)
     32 playlists = parse_content_list(results['items'][1:], parse_playlist)
     34 if 'continuations' in results:

File /usr/local/lib/python3.9/site-packages/ytmusicapi/navigation.py:72, in nav(root, items, none_if_absent)
     70     return None
     71 else:
---> 72     raise err

File /usr/local/lib/python3.9/site-packages/ytmusicapi/navigation.py:66, in nav(root, items, none_if_absent)
     64 try:
     65     for k in items:
---> 66         root = root[k]
     67     return root
     68 except Exception as err:

TypeError: 'NoneType' object is not subscriptable
```

Let me know if there is anything i can try or provide from my end!

**Comment by sigma67** [comment]
Did you get a new library interface on the web? Seems like something changed on the YouTube end again as you said.

If you'd like I can reproduce the issue with your credentials again as we did last time (ytmusicapi@gmail.com) to develop a fix.

**Comment by jake-g** [comment]
yes the web ui looks different now that i think about it. library and other tabs.

Ill send you the creds

**Comment by sigma67** [comment]
I fixed it in a backwards compatible way. Can you verify that it works for you?

**Comment by jake-g** [comment]
Awesome, just got back from vacation so I'll try later today.

**Comment by jake-g** [comment]
yuuup, looks like this is resolved when i use the latest commit, i.e.:

`pip3 install git+https://github.com/sigma67/ytmusicapi.git@master`

thanks for jumping on this!
