### ISSUE TITLE
weird playlist format not being parsed correctly

### ISSUE THREAD

**Issue by oxcug** [sigma67/ytmusicapi#302]
Hey folks, I am trying to get the track list for the playlist with the ID: OLAK5uy_mo0wJh-LjbaTD5NsVO--RzKkToBnonkUw and noticed it has a different response than the one in the tests and is failing to be parsed. Not entirely sure what's the issue here but figured I'd raise it. Attached is a [sample-response.txt](https://github.com/sigma67/ytmusicapi/files/9692877/sample-response.txt) with the json.

**Comment by sigma67** [comment]
The ID you linked is in fact an album (Avicii - TIM). The proper way to get that page with ytmusicapi is to use 

```python
browseId = ytm.get_album_browse_id(playlistId)
ytm.get_album(browseId)
