### ISSUE TITLE
Proposal: return playlistIds in get_library_albums

### ISSUE THREAD

**Issue by zarkdav** [sigma67/ytmusicapi#303]
Hi,

I wanted to merge the content of a brand account into the main and tried to use `get_library_albums` with `rate_playlist`, unfortunately the first method was not returning `playlistId` as part of the album dict and the second method was not recognizing the `browseId`.

I have written two small modifications to `navigation.py` and `parsers/library.py` which seem to solve this. Should I go ahead and open a pull request?

**Comment by sigma67** [comment]
That seems quite reasonable to implement, thanks for the suggestion. Feel free to submit a PR! 

Will need to update the docstrings for the affected functions as well.
