### ISSUE TITLE
Getting the album name of a certain song

### ISSUE THREAD

**Issue by JuanFran928** [sigma67/ytmusicapi#308]
Hello, Is it posible to get the album name from a song if you pass any parameters like the youtube url of the song or the song name that belongs to that album?

I realized that if you filter by album like that `search_results = yt.search(query="Song Name", filter="albums")`
And in the mayority of the cases the album name is in `song_result[0]['title'])`

But I don't know if is there a better way to achieve this.

**Comment by sigma67** [comment]
If you have the videoId you can use [`get_watch_playlist`](https://ytmusicapi.readthedocs.io/en/stable/reference.html#ytmusicapi.YTMusic.get_watch_playlist). The first result will contain all the details of the song.
