### ISSUE TITLE
Remove songs in history

### ISSUE THREAD

**Issue by allanin** [sigma67/ytmusicapi#31]
According to Google songs played change the recommendation:

https://support.google.com/youtubemusic/thread/160722?hl=en

Would it be possible adding a delete_song_history() function?

**Comment by sigma67** [comment]
Good suggestion. I implemented this feature locally (it uses the 'feedback' endpoint and it works fine.

However, I found that removing items from the history does not seem to be persisted. For example, try removing a watched item in your browser on music.youtube.com/history. It will disappear, but after reloading it will reappear again.

**Comment by sigma67** [comment]
Regarding my previous comment, the persistence bug still exists. However, I discovered that it only occurs on brand accounts. It works fine on normal accounts.
