### ISSUE TITLE
Api is looking for "Your cookie is missing the required value __Secure-3PAPISID"

### ISSUE THREAD

**Issue by burakuren101** [sigma67/ytmusicapi#312]
But the problem is, a valid yt music cookie is not containing a key like this.
"    "Cookie": "VISITOR_INFO1_LIVE=zZOMhJo7fg0; PREF=f6=40000080&tz=Europe.Istanbul&autoplay=true&library_tab_browse_id=FEmusic_liked_playlists&f5=20000; SID=PQj2IwQb1fmlTq6utGi3pvwGjI6NfO4kylziU2NsFnD6FGri1if_PEDzcu0nbTr1GUYdNw.; __Secure-1PSID=PQj2IwQb1fmlTq6utGi3pvwGjI6NfO4kylziU2NsFnD6FGrirhK5KyftJQoXEB_SUOwRGw.; __Secure-3PSID=PQj2IwQb1fmlTq6utGi3pvwGjI6NfO4kylziU2NsFnD6FGriJdV0ghOLqitX_5gLjrGjwg.; HSID=A3KkQE4St-b1XQoss; SSID=AhFsCT7LZZSpsre6m; APISID=bdPTlAGmgNLFggmc/A8OVXXaXgq3Go3F1T; SAPISID=7MbfLwAbesR2lUHR/AAie-…oNzBVWk1wb21VVkhjMVhuYWJweEJlUjZOckdacEJ3cHI1MnZBQWVlUGhJNnRZMUIyU0JxVFBsRGdVV1BTeXhuUUZmcTVqMDNwd0JEMDMyTklrR0pPd1E3cUtYV25jOVQzOFk5M1Z0N2FfZ1F0NTl2VmpzY3FWdGFZQVFaUTFSYm45MjRhZzFR; SIDCC=AIKkIs1gY38UEC_lti0vwJ9PDkDAL3t9W5Hz59i0auL42CWX1boa75uVFRxxYwG2z_Mopu30h6s; __Secure-1PSIDCC=AIKkIs3mzd6LFi6cg8bgDN8l6xTibBf_r4TstBeaKWkrWsjzZz0XKECTH0YhxlWAVYtc0jNEwqc; __Secure-3PSIDCC=AIKkIs1LH7nYgSGa8S359VAfIMPTkgyvswswpEfiXDTLaRf6qlvcvRokpsZTbPhn797kt83lZhI; _gcl_au=1.1.615587751.1665490687; YSC=QeAconmTKcs; wide=1",
"

**Comment by sigma67** [comment]
Is this cookie from a signed-in account? 

Is this something that's recently changed, i.e. the value was there previously?
