### ISSUE TITLE
[Documentation] Package ytmusicapi with pyinstaller

### ISSUE THREAD

**Issue by acantepie** [sigma67/ytmusicapi#315]
Hi,

If you want to package `ytmusicapi` with `pyinstaller`,
you have to manually include `locales` directory on your build with option `--add-data` :
```
pyinstaller foo.py [...] --add-data "venv/lib/python3.10/site-packages/ytmusicapi/locales:ytmusicapi/locales
```
Else your build with throw this error
```
Traceback (most recent call last):
  File "ytmusicapi/ytmusic.py", line 105, in __init__
StopIteration
[95748] Failed to execute script 'youtube-dl' due to unhandled exception!
```

It should be usefull to add a section (or a FAQ) for this on documentation.

**Comment by sigma67** [comment]
Others have suggested to use `collect-all` option, that seems simpler? But I agree with adding a FAQ section.

https://github.com/sigma67/ytmusicapi/issues/250#issuecomment-1152984658
