### ISSUE TITLE
[Question] Ready to use CLI client?

### ISSUE THREAD

**Issue by cprn** [sigma67/ytmusicapi#317]
Hello. Anyone aware of projects using this API? Preferably a CLI client with simple commands (e.g. `ytm play`, `ytm next`, `ytm list playlists`, `ytm select <song|artist|playlist>`, etc) so these could be called somewhere higher in the system, e.g. from launchers (like `dmenu` or `rofi`) or by events like pressing multimedia keys or custom keyboard shortcuts.

I'm looking for a lightweight alternative to those electron wrapped websites that claim to be "desktop players".

**Comment by map7** [comment]
There is https://github.com/cfangmeier/tuijam but I cannot get it to work

**Comment by cprn** [comment]
> There is https://github.com/cfangmeier/tuijam but I cannot get it to work
Yeah, I used to use it for Google Music but they finally made me switch to YTM last week.

> https://mopidy.com/ext/ytmusic/ - works
Thanks, didn't know about `mopidy`, looks promissing - seems like it might work with something like `ncmpcpp`. If so, you've solved my issue. Thank you very much!
