### ISSUE TITLE
Add favourite artist to taste

### ISSUE THREAD

**Issue by allanin** [sigma67/ytmusicapi#32]
You can choose your favourite artist with this url: https://music.youtube.com/tasteprofile

According to Google it changes to recommendations.

Please add a way to add artists to this list via your api.

**Comment by sigma67** [comment]
This requires two new methods `get_tasteprofile` and `set_tasteprofile`, both using the browse endpoint. 

The get uses the browseId `FEmusic_tastebuilder`, while the set uses `FEmusic_home `and takes selected and impression values from the get method as arguments.

**Comment by YashMakan** [comment]
any improvement in this issue? I want to implement this feature.

**Comment by sigma67** [comment]
Feel free, I don't think anyone else is working on it

**Comment by sigma67** [comment]
Contributed by @adrinu in #289
