### ISSUE TITLE
get_charts returns incomplete list of tracks

### ISSUE THREAD

**Issue by shoegazerstella** [sigma67/ytmusicapi#322]
Hi all,

the `get_charts()` method only returns the first 40 items instead of the complite list. 
Is there a way to add the missing ones? 

thank you

**Comment by sigma67** [comment]
The web app only provides 40 tracks, so that's all there is.

**Comment by sigma67** [comment]
You can use the following code (assuming your instance is called yt_auth)

```python
charts = yt_auth.get_charts()
charts_100_songs = yt_auth.get_playlist(charts['songs']['playlist'])
charts_100_videos = yt_auth.get_playlist(charts['videos']['playlist'])
```
