### ISSUE TITLE
[Request] An async version of the client that uses aiohttp instead of requests

### ISSUE THREAD

**Issue by Om1609** [sigma67/ytmusicapi#325]
It will be great to have an async version of this library that can be used in asynchronous projects. I needed one for a discord bot and couldn't use the blocking version. 

I did manage to make a [fork](https://github.com/Om1609/async-ytmusicapi)  and get it working but it becomes out of date with the main library pretty quickly (shoutout to the devs who are very active). Don't judge my code. It was a edit I did to have it working

**Comment by sigma67** [comment]
It's nice that you got this working, but I don't see a way to integrate this into the main project right now. Perhaps it's possible to wrap library functionality in async threads to avoid having to maintain a separate version of the library.

**Comment by Om1609** [comment]
One way would be having the main working in an async version of the client, and the sync client just called methods on the async client using `asyncio.create_task`, but this doesn't make any sense even to me.

As you said, async threads would be the best option (using `asyncio.to_thread`)

**Comment by sigma67** [comment]
Sorry, I'm going to go ahead and close this as Not Planned. None of the other Python music streaming service clients support async (i.e. spotipy, gmusicapi, python-tidal, etc.), and I don't think it's worth the effort to support. 

Another consideration is also the likelihood to run into more issues with rate limits, as parallel requests are even more suspicious than sequential ones.
