### ISSUE TITLE
YTMusic.get_album() songs lacks thumbnails

### ISSUE THREAD

**Issue by maaa101** [sigma67/ytmusicapi#326]
YTMusic.get_album() songs lacks thumbnails

![image](https://user-images.githubusercontent.com/85688939/206868394-26a6431e-153a-48e0-b52a-cb1c04400740.png)

**Comment by sigma67** [comment]
Yes, because there are no thumbnails on individual songs as you can see in the Web UI: https://music.youtube.com/playlist?list=OLAK5uy_nMr9h2VlS-2PULNz3M3XVXQj_P3C2bqaY

The album itself has a thumbnail which is included at the top level of the dictionary.
