### ISSUE TITLE
Question: Unclear if these are possible

### ISSUE THREAD

**Issue by rderidder-lda** [sigma67/ytmusicapi#329]
Interested in this library, but I'm having doubts Youtube actually allows what I'm interested in..
- pull a list of all my disliked songs (from uploaded library)
- delete those songs from my uploaded library
- create my own playlist made up of all liked songs (vs the automated one they create)
- pull a list / create a playlist of all my uploaded library songs that have not been rated yet

basic stuff to help reduce my massive uploaded library down to just liked songs, and find out which ones I need to rate still.
Thanks!

If you tube makes these things available in their API, I'd be willing to contribute to this project to make the above simpler to execute.
But again, i'm assuming they just don't support the filtering I'm looking for..
R

**Comment by sigma67** [comment]
- you can't get disliked songs only (this is not possible in the web UI)
- you can get all liked songs using `get_liked_songs` and add them to a playlist using `create_playlist`
- you can get all your uploaded songs and filter out those that have not been rated

**Comment by rderidder-lda** [comment]
thanks!  i suppose then I could get the whole uploaded library listing, remove the liked ones, remove the unrated ones, and I would be left with the disliked ones that I could remove from the online library...

**Comment by sigma67** [comment]
That is correct, for uploaded songs you can do it this way. Use [`get_library_upload_songs` with `limit=None`](https://ytmusicapi.readthedocs.io/en/stable/reference.html#ytmusicapi.YTMusic.get_library_upload_songs). 

`likeStatus` is what you're looking for.

**Comment by rderidder-lda** [comment]
Thanks for the help!  the library is easy to use so far (once i figured out the cookie pasting part)

One weird thing is that the get_liked_songs  function returned 8 songs when I set the limit to None... but when i grab the entire library and count the LIKED ones I get the proper count of > 1000.
Not sure if there is some other filter in place..  but no big deal for me - I'm just going to use the full library to get the liked ones.

**Comment by sigma67** [comment]
`get_liked_songs` returns the liked songs playlist here: https://music.youtube.com/playlist?list=LM

What's the count of that playlist for you? Are you sure you counted the number of tracks and not the number of keys in the dictionary?

**Comment by rderidder-lda** [comment]
you are exactly correct... was not counting the tracks item.  There are actually a few more in the liked playlist now, compared to counting the LIKED status on the full uploads... I'm guessing the liked playlist includes things that might not have been uploaded, so that makes sense.
Thanks!
