### ISSUE TITLE
using ytmusicapi  to get next album which youtube music algorithm recommend

### ISSUE THREAD

**Issue by YeiSimon** [sigma67/ytmusicapi#331]
Hello , I am new in this project.
Due to my personal preference on music quality, I need to get the music on other platform , However; Youtube music has the best **algorithm** on search engine and better _recommend song_ .Is there any possible way to get _recommend song_ on youtube music

**Comment by maaa101** [comment]
oh my god bruh

**Comment by sigma67** [comment]
You can get song recommendations using `get_watch_playlist` for a specific song, album or playlist.
