### ISSUE TITLE
liked songs

### ISSUE THREAD

**Issue by veber88** [sigma67/ytmusicapi#332]
Seems that liked playlist only has 5000 songs and next liked song will replace first from the list. But removed track still remain liked. How  can we get all liked songs when they arent in liked playlist?

**Comment by sigma67** [comment]
You can try to get all the songs in your library, the limit might be higher. And filter those you've liked.

**Comment by veber88** [comment]
How can i get all songs from library? Thanks for your answer.

**Comment by veber88** [comment]
@sigma67 pls answer the question about how i can get all songs from library. Thank you in advance!

**Comment by veber88** [comment]
@sigma67 also i have a problem to get songs that marked as isnt available. Is it possible get such songs from api?

**Comment by veber88** [comment]
@sigma67 waiting for your answer here please.

**Comment by sigma67** [comment]
Please, just use the reference. It's not rocket science.

https://ytmusicapi.readthedocs.io/en/stable/reference.html#ytmusicapi.YTMusic.get_library_songs

**Comment by veber88** [comment]
@sigma67 does it return all liked songs or 5000 most recent liked?

**Comment by sigma67** [comment]
It returns what's being returned in the web interface. Liked songs are limited to 5000 iirc
