### ISSUE TITLE
Country based results

### ISSUE THREAD

**Issue by sheikhhaziq** [sigma67/ytmusicapi#336]
`charts()` return country based result. But is there an way to obtain country based results in `get_home()` and in `search()`

**Comment by sigma67** [comment]
As you've noticed this is related to the localization feature (`language` parameter on init), therefore I'll close this.

**Comment by sheikhhaziq** [comment]
I'm not talking about language. When i set my language to german, I get result in german language but the result is based on global data not my country based

**Comment by sigma67** [comment]
Well, can you tell me how to achieve what you're looking for using the web interface?

That's the main purpose of this library, to emulate web functionality.
