### ISSUE TITLE
Image are small

### ISSUE THREAD

**Issue by sheikhhaziq** [sigma67/ytmusicapi#337]
Images fetched for songs in `home` and `search` are too small in size.

**Comment by sigma67** [comment]
Please be more specific. Are you referring to thumbnails?

**Comment by sheikhhaziq** [comment]
I am talking about thumbnails. When data is fetched using `get_home()`, thumbnails of song are smaller in size

**Comment by sigma67** [comment]
Yeah, that's what the server provides. If you look at the home page in YouTube Music web, the thumbnails for songs are smaller than other types of content.

Also, please try to ask simple questions on [gitter ](https://gitter.im/sigma67/ytmusicapi)to avoid cluttering the issue log.
