### ISSUE TITLE
musicTrackUserDetail may not be present

### ISSUE THREAD

**Issue by jdwoody** [sigma67/ytmusicapi#34]
Pulling album details may fail if musicTrackUserDetails aren't present

Possible fix [here](https://github.com/sigma67/ytmusicapi/blob/master/ytmusicapi/ytmusic.py#L446)
```python
track['likeStatus'] = likes.get(item['entityKey'], 'INDIFFERENT')
```

**Comment by sigma67** [comment]
The issues was that the data array was being subsetted (data[4:]) and therefore the likes were missing some tracks.

Fixed in 667a6edc81c53dcc79a882176253f26391914b60
