### ISSUE TITLE
How do I add a single from album to playlist?

### ISSUE THREAD

**Issue by Praful** [sigma67/ytmusicapi#343]
Hello, thank you for providing this excellent API and the brilliant documentation.

I came across a track that appears as `type` 'Single' on `resultType` 'album'. There is no `videoId`. There is a `browseId` but that can't be used to add the track to a playlist. You can add this via the web interface.

How could I add this to a playlist using your API?

Thanks

**Comment by sigma67** [comment]
You can get the `audioPlaylistId `using `get_album `and add the album to a playlist using the `source_playlist `parameter of `add_playlist_items`.

https://ytmusicapi.readthedocs.io/en/latest/reference.html

**Comment by Praful** [comment]
Thanks. In case others find it useful, I have implemented your suggestion here: https://github.com/Praful/music-playlist-export-import/blob/main/src/youtube_music_import.py. 

There are also scripts to export playlists from Spotify (using spotipy) and scraping playlists.
