### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by dsm-72** [sigma67/ytmusicapi#345]
I'm getting

```
Exception: The following entries are missing in your headers: cookie, x-goog-authuser. Please try a different request (such as /browse) and make sure you are logged in.
```

from the copy-pasted request headers and I am indeed logged in.

**Comment by sigma67** [comment]
Yes, it works. Did you do as instructed?

https://ytmusicapi.readthedocs.io/en/stable/setup.html

**Comment by dsm-72** [comment]
@sigma67 
Yes. 
1. go to music.youtube.com
2. login in
3. open inspector
4. click "explore" to get a POST request with `browse` (as there is no browse on landing page)
5.

```
domain | ".youtube.com"
Host music.youtube.com
Origin music.youtube.com
X-Goog-AuthUser 0
```

right click in request headers, click copy, copy all

paste into string and pass as `headers_raw`

> Exception: The following entries are missing in your headers: x-goog-authuser, cookie. Please try a different request (such as /browse) and make sure you are logged in.

**Comment by sigma67** [comment]
Not sure what you pasted in 5), but there's no cookie value, which is needed to authenticate. Are you trying to authenticate? Else there's no need for the whole process.

If you want me to debug this for you, send your copied header text to ytmusicapi@gmail.com. Else there's not much I can do to help.

**Comment by spm2600** [comment]
the header is only good for a day or two then it changes on me.  is this expected?

**Comment by sigma67** [comment]
No, I've used the same headers for months, even years, in the past. It might invalidate if you're signing out in the browser you got the credentials from.
