### ISSUE TITLE
get_playlist(..., limit=track_limit) doesn't return correct length?

### ISSUE THREAD

**Issue by dsm-72** [sigma67/ytmusicapi#347]
```python
# Get artist data to find their song browseId
artist = ytmusic.get_artist(channelId=YOUTUBE_MUSIC_ARTIST_ID)

# Try and get all song data
yt_songs = ytmusic.get_playlist(playlistId=artist['songs']['browseId'], limit=500, related=False, suggestions_limit=0)

yt_songs['trackCount'], len(yt_songs['tracks'])
# 134, 110
```

So trackCount isn't the same as len of tracks and there isn't a next page option?

**Comment by sigma67** [comment]
Normally this shouldn't happen but there's some edge case where it does. Again, please provide the artist id, else I can't reproduce.

**Comment by czifumasa** [comment]
It can occur If you fetch public or unlisted playlist where playlist owner added some uploaded tracks. You don't have access to his uploaded tracks, but they may still be considered for track count.

**Comment by dsm-72** [comment]
@sigma67 I think it was on id `UC4G-AJa7kn8oumI6TT2WXYw` during the loop

**Comment by sigma67** [comment]
@czifumasa this is an artist's songs playlist, so it can't be just some uploaded tracks. However, the artist may be able to set tracks to private, causing this issue. Unfortunately I have no insights on the artists' capabilities here.

https://music.youtube.com/playlist?list=OLAK5uy_lihhm8an0pBrQ_rMaHTryX6-tYH1OTuCQ
