### ISSUE TITLE
artist subscribe foiled by two channelids

### ISSUE THREAD

**Issue by thomasscovell** [sigma67/ytmusicapi#35]
Using the "Oasis" example given, search('Oasis','artists') returns a browseID of - UCmMUZbaYdNH0bEd1PAlAqsA
This appears correct as per using the web interface which returns - https://music.youtube.com/channel/UCmMUZbaYdNH0bEd1PAlAqsA

attempting to subscribe_artists to this browseId returns success but artist is not subscribed in web interface.

investigation shows that subscribing from the web interface submits a different channelD from what is displayed in the URL and returned in search - UCUDVBtnOQi4c7E8jebpjc9Q

subscribing to _this_ ID via API works, whether you view the artists at:
https://music.youtube.com/channel/UCmMUZbaYdNH0bEd1PAlAqsA
or
https://music.youtube.com/channel/UCUDVBtnOQi4c7E8jebpjc9Q

?!

Unable to find this second ID returned anywhere in search() or via web interface (though it must be somewhere for it to be available to web app to submit)

Have verified this problem with all artists I search for. 

<img width="702" alt="Screenshot 2020-06-27 at 23 43 22" src="https://user-images.githubusercontent.com/2206/85933721-6a0b7480-b8d2-11ea-8697-0e10716deec0.png">

<img width="394" alt="Screenshot 2020-06-27 at 23 43 49" src="https://user-images.githubusercontent.com/2206/85933734-92936e80-b8d2-11ea-855c-fbffe51df827.png">

<img width="771" alt="Screenshot 2020-06-27 at 23 44 32" src="https://user-images.githubusercontent.com/2206/85933735-97582280-b8d2-11ea-976e-fb5cbf6b1002.png">

**Comment by sigma67** [comment]
Good catch. Seems the channelId is different from the artist's browseId. I'll implement a fix shortly.

**Comment by basisvectors** [comment]
Hey im still facing this issue with the subscription, how can i find the alternate channel ids for an artist?
