### ISSUE TITLE
Is it possible to control playback from this?

### ISSUE THREAD

**Issue by tsbertalan** [sigma67/ytmusicapi#354]
It's not clear to me whether this is just for getting and changing data, or whether I can also control playback. It would be great if I didn't have to have a working sound system connected on the Python side, but instead could just control whatever authenticated player was currently active elsewhere, like phone app or a web player. That is, this library wouldn't handle actually streaming audio or video data, which I imagine will be much harder to add, but would just issue commands. Is this in scope?

**Comment by tsbertalan** [comment]
Really all I want is play/pause control. Something like this:

```python
from time import sleep
from ytmusicapi import YTMusic
yt = YTMusic('headers_auth.json')
yt.play()
sleep(5)
yt.pause()
```

**Comment by sigma67** [comment]
Short answer, no. You're looking for Spotify functionality. This is not Spotify.
