### ISSUE TITLE
Get timestamp in history

### ISSUE THREAD

**Issue by louis030195** [sigma67/ytmusicapi#355]
hey i'm developping a piece of code to sync my youtube music to last.fm (https://github.com/louis030195/ega/tree/main/functions/youtube_music_to_lastfm)

and i'd like to avoid adding duplicates by hashing artist + music + time listened

but in ytmusicapi there is just "played" "today" no timestamp, is it a bottleneck from youtube music api or it could be fixed here? happy to contribute if necessary

**Comment by sigma67** [comment]
I assume you're referring to the history page. Can only scrape what's there on music.youtube.com/history. As you can see it's only clustered by date without timestamp. Background data is rarely much more than what you can see on the frontend, in this case there is no timestamp. Nice project though.

**Comment by louis030195** [comment]
> I assume you're referring to the history page. Can only scrape what's there on https://music.youtube.com/history. As you can see it's only clustered by date without timestamp. Background data is rarely much more than what you can see on the frontend, in this case there is no timestamp. Nice project though.

Understandable
I just sent a feature request to YouTube music team
