### ISSUE TITLE
API is not returning any search results

### ISSUE THREAD

**Issue by Ijazweb** [sigma67/ytmusicapi#356]
is this working ?

**Comment by sigma67** [comment]
of course it is. provide more details

**Comment by Ijazweb** [comment]
```
from ytmusicapi import YTMusic

yt_client = YTMusic()

search_results = yt_client.search('abc', 'songs', ignore_spelling=True)

print(search_results)
```


its only return artists but when change to songs then return empty array

**Comment by sigma67** [comment]
Not sure why that's happening for you, but the exact same call is working 100% fine for me.
