### ISSUE TITLE
Inconsistency with Liked song video vs audio

### ISSUE THREAD

**Issue by trekk9** [sigma67/ytmusicapi#358]
First thank you @sigma67 for a great API. I've been using it for years and it's very stable and well made.

Now for the issue I'm experiencing:

I often see songs in public playlists that, unfortunately, default to the video version of songs. When I Like one of these songs, the Like will not apply to the audio version of the song unless the [videoType](https://github.com/sigma67/ytmusicapi/issues/353) is OMV.

I know that this is a Youtube issue, but this has created an inconsistent experience on the mobile app since I have the "Don't play music videos" option enabled.

Ideally, I'd like to iterate through playlist items and ensure the audio version of a liked video is also liked.

I was just wondering if anyone has solved this not so obvious design flaw (_again, with YouTube Music! Not your awesome API)_?

Thanks!

**Comment by sigma67** [comment]
Hi and thanks! First off, music videos should only be encountered when you're not logged in as a premium subscriber. In my experience, YT Music replaces premium-only content with public music videos when you're not logged in.

In addition, you can use [`get_watch_playlist`](https://ytmusicapi.readthedocs.io/en/stable/reference.html#ytmusicapi.YTMusic.get_watch_playlist) to get the song/video counterpart of each song. It's in the `counterpart` key of the dictionary.

**Comment by trekk9** [comment]
Bang! This is exaclty what I was looking for. Thanks!
