### ISSUE TITLE
'get_mood_playlists' 500 internal errors

### ISSUE THREAD

**Issue by police02** [sigma67/ytmusicapi#359]
I always use it well. Thank you.

500 errors are currently encountered in 'get_mood_playlists'.
This is
Occurs when 'params' in 'get_mood_categoriesd' > 'genres' > 'jpop' is set as a parameter.

**Comment by police02** [comment]
jpop params >> ggMPOg1uX1R6ZWQ0MTBwOUp5
get_mood_playlists(ggMPOg1uX1R6ZWQ0MTBwOUp5)

**Comment by sigma67** [comment]
It's working fine for me, must be an isolated issue with your account or region.
