### ISSUE TITLE
rate_song and rate_playlist not working

### ISSUE THREAD

**Issue by Appleweed564** [sigma67/ytmusicapi#362]
Nothing happens when I use both of those functions to add either songs or albums/playlist to favorites.

I have tried with different albums , and on some of them , the artist will correctly show up in the artists tab , but the album will not be in the Albums tab.

```
isrc = 'USCN17800055'
res = yt2.search(isrc,filter='songs')
res = yt2.rate_song(videoId=res[0]['videoId'],rating='LIKE')

```

```
res = yt2.search('thriller michael jackson',filter='albums')
res2 = yt2.get_album(browseId=res[0]['browseId'])
yt2.rate_playlist(playlistId=res2['audioPlaylistId'],rating='LIKE')

```

**Comment by sigma67** [comment]
Please follow the issue template.
