### ISSUE TITLE
Is there a way to extract full description of a music video?

### ISSUE THREAD

**Issue by ryq99** [sigma67/ytmusicapi#364]
I'm extracting music data with .get_song(), I'm able to see the video description under result['microformat']['microformatDataRenderer']['description']. However, I found it's just the shortened description not the full one. Take Sunflower (Spider-Man: Into the Spider-Verse) as an example, the video id is 'ApXoWvfEYVU', I have the description as follows: 

"description": "Own Spider-Man: Into the Spider-verse on Digital 2/26 and Blu-ray on 3/19 Blu-ray: http://sonypictures.us/ueaRau Digital: http://sonypictures.us/Wnbe3e \"S...".

I'm wondering if there is a way to get the full description like we can get on the page by expanding it?

**Comment by vixalien** [comment]
prettu sure that description is not exposed in youtube music, only in youtube

**Comment by ryq99** [comment]
Then I guess I will probably have to use the official Youtube API to get it, thanks!

**Comment by sigma67** [comment]
Yes, this is not under our control. There's actually very little parsing happening for `get_song`, the data is returned pretty much exactly as it is returned by the server:

https://github.com/sigma67/ytmusicapi/blob/19ad424e0e59b1908fcb767f8b85a83ecf5ecde2/ytmusicapi/mixins/browsing.py#L596-L615
