### ISSUE TITLE
Some playlists only returning 100 tracks, regardless of limit in get_playlist

### ISSUE THREAD

**Issue by scrimshander** [sigma67/ytmusicapi#366]
In the last few days, I have seen *some* of my playlists only returning 100 tracks via `get_playlist`, regardless of `limit`. The behavior is consistent per playlist, but I cannot find any systematic difference between the ones that seem limited to 100 and the others. I have tried setting public/private, etc. This is new behavior - I am constantly managing the same group of playlists with this call and have not changed anything in my code for some time. 

Copying a "bad" playlist to a new one results in good behavior from the new playlist.

Has anyone ever seen similar behavior? I will keep trying and see if it clears up.

**Comment by sigma67** [comment]
I believe this is related to issue #365.  Have you check with latest master?

**Comment by scrimshander** [comment]
Ah yes, those look to be the same thing. I have not tried the latest code,
only latest release. Will do!

**Comment by Blefish** [comment]
Fixed for me on latest release :+1:

**Comment by dataNerd23** [comment]
I still have this problem with my playlist.  I'm using python 3.11.4 and ytmusicapi 1.0.2.  I've tried setting the limit=None and limit=1000 with no avail.  My playlist size is 208.

Also, I get the same issue mentioned in [#365](https://github.com/sigma67/ytmusicapi/issues/365).

@sigma67 let me know if you want me to send you the playlist link privately.

**Comment by dataNerd23** [comment]
> I still have this problem with my playlist. I'm using python 3.11.4 and ytmusicapi 1.0.2. I've tried setting the limit=None and limit=1000 with no avail. My playlist size is 208.
> 
> Also, I get the same issue mentioned in [#365](https://github.com/sigma67/ytmusicapi/issues/365).
> 
> @sigma67 let me know if you want me to send you the playlist link privately.

I also found out that the duration has the track count, trackCount returns the first two digits of the views, and views returns nothing.  I think this is an off by one error.

**Comment by dataNerd23** [comment]
> > I still have this problem with my playlist. I'm using python 3.11.4 and ytmusicapi 1.0.2. I've tried setting the limit=None and limit=1000 with no avail. My playlist size is 208.
> > Also, I get the same issue mentioned in [#365](https://github.com/sigma67/ytmusicapi/issues/365).
> > @sigma67 let me know if you want me to send you the playlist link privately.
> 
> I also found out that the duration has the track count, trackCount returns the first two digits of the views, and views returns nothing. I think this is an off by one error.

I fixed the issue by pulling from the master, and I specifically noticed the difference in the following lines from playlist.py:

[https://github.com/sigma67/ytmusicapi/blob/master/ytmusicapi/mixins/playlists.py#L137-L143](https://github.com/sigma67/ytmusicapi/blob/master/ytmusicapi/mixins/playlists.py#L137-L143)

**Comment by sigma67** [comment]
Yes, I've been slacking on the release. Will push one today.
