### ISSUE TITLE
filtering search on albums is not filtered?

### ISSUE THREAD

**Issue by zeitmeister** [sigma67/ytmusicapi#374]
When performing a search with "albums" as filter i get a different response when i run my code locally compared to when i run it in a docker container.

The following search is perfomed: 
`ytmusic.search("Sepultura Arise", "albums")`

And the response from when I run it locally is:
```
[
   {
      "category":"Albums",
      "resultType":"album",
      "title":"Arise",
      "type":"Album",
      "duration":"None",
      "year":"1991",
      "artists":[
         {
            "name":"Sepultura",
            "id":"UCZDm-NPbTrtTGa69EC2dFGw"
         }
      ],
      "browseId":"MPREb_SXjncHxnAGz",
      ....
      }
]
```

The response from the same request made from within a docker container:
```
[{
	'category': 'Albums',
	'resultType': 'song',
	'title': 'Arise',
	'album': None,
	'feedbackTokens': {
		'add': None,
		'remove': None
	},
	'videoId': 'Ubgc-4MNunQ',
	....
	}
]
```
Note that the `resultType` is different and the absence of browseId (which breaks my whole app).
I discovered the issue when working on a "bigger" playlist app and decided to do a minimal test and the issue is still there. The minimal code for reproducing the error : 
```
from ytmusicapi import YTMusic
import time
import logging
from datetime import date


ytmusic = YTMusic('header-auth.json')


logging.basicConfig(filename="./logs/test-"+str(date.today())+".log",
                    format='%(asctime)s,%(msecs)d %(name)s %(levelname)s %(message)s',
                    datefmt='%H:%M:%S',
                    level=logging.INFO)

search_results = ytmusic.search("Sepultura Arise", "albums")
logging.info(search_results)
```
And the Dockerfile:
```
FROM python:3.10.6
RUN mkdir /code
RUN mkdir /code/logs/
WORKDIR /code
ADD dagensalbum.py /code/
ADD test.py /code/
ADD header-auth.json /code/
RUN pip3 install ytmusicapi requests schedule
CMD ["python3", "./test.py"]
```

This well might not be a problem with `ytmusicapi` but instead with docker networking somehow but then wouldn't it be no request at all? I'm trying to wrap my head around what is actually happening here but can't quite figure it out. I wouldn't be suprised if I missed something. Sorry about the long entry.

Thanks for a great service anyhow!

Kind regards
Simon

**Comment by zeitmeister** [comment]
Ok, I figured out that everytime I rebuild and run the docker container the newest version of ytmusicapi is installed (since the `pip install` line in the Dockerfile and that it's been a while since i did it locally. When i updated ytmusicapi locally (from 0.25.0 to 0.25.2 i got the same response as i did from the docker container. The problem still remains though, I am filtering on `"albums"` and I expect the response to be filtered like that. Is this a proper issue or is it still something I don't understand? : )

**Comment by sigma67** [comment]
It is indeed a bug. Something about the obscure filtering params used in search seems to have changed.

**Comment by sigma67** [comment]
It works for me with the change above. Did you notice any other oddities about search?

**Comment by zeitmeister** [comment]
All right! No, I'm actually just using album searching so I haven't noticed anything else with the search functionality. Is there anyway i could try these changes out?

**Comment by sigma67** [comment]
`pip install git+https://github.com/sigma67/ytmusicapi`

**Comment by zeitmeister** [comment]
Sorry but this command installs the package as `UNKNOWN` and I am too much of a python newbie to know how to make this work. `from UNKOWN import YTMusic` does not do the trick unfortunately.

**Comment by sigma67** [comment]
Not sure why, I get

``
Successfully installed ytmusicapi-0.25.3.dev19+ga1e4662
``

**Comment by zeitmeister** [comment]
Sorry for being a complete idiot. Upgrading pip solved this issue. fml...

**Comment by zeitmeister** [comment]
Yeah, I suppose. But even now when I'm using `ytmusicapi             0.25.3.dev19+ga1e4662` as stated when I'm running `pip list` i still get the same _none_ album response when filtering for albums. The `resultType` is all of the value `song`

**Comment by sigma67** [comment]
I have to apologize, that was an oversight on my part. It wasn't actually the parameter, the old one worked fine.

I added some more asserts as well to prevent this in the future.

**Comment by zeitmeister** [comment]
All right, no worries! It seems to be working now. Thank you so much for your quick responses!
