### ISSUE TITLE
setup oauth with function

### ISSUE THREAD

**Issue by MisileLab** [sigma67/ytmusicapi#378]
**Is your feature request related to a problem? Please describe.**
I want to setup oauth with function, but I can't it because setup_oauth function uses terminal.

**Describe the solution you'd like**
make a oauth function

**Describe alternatives you've considered**

**Additional context**

**Comment by sigma67** [comment]
How would that work? Someone still needs to access the site, log in and confirm the authorization. It's not possible to do this in a fully automated fashion without user interaction, unless you use the `browser` auth.

**Comment by sigma67** [comment]
I suppose it would be possible to move the input statement out of `get_code`, that would allow people to code their own oauth flows in say, Desktop apps.

You could then do:

```python
from ytmusicapi.auth.oauth import YTMusicOAuth

session = requests.Session()
oauth = YTMusicOAuth(session)

code = oauth.get_code()

# tell the user to finish the flow at code['verification_url']

token = oauth.get_token_from_code(code["device_code"])

# store the token in oauth.json
```

Is that what you intended?

**Comment by MisileLab** [comment]
Yes, thank you

**Comment by apastel** [comment]
For anyone reading, in the latest version of ytmusicapi (1.5.2 as of today), it would use the `OAuthCredentials` class and the `token_from_code()` function.

```
from ytmusicapi.auth.oauth import OAuthCredentials

session = requests.Session()
oauth = OAuthCredentials(session=session)

code = oauth.get_code()

# tell the user to finish the flow at code['verification_url']

token = oauth.token_from_code(code["device_code"])

# store the token in oauth.json
```

However even though `token_from_code` is documented to return a `RefreshableTokenDict`, the token it's returning is missing the `expires_at` property, which makes it invalid and results in a 401 Unauthorized when trying to use it. It has `expires_in` and `access_token` but no `expires_at`. I'm trying to figure out how to make it a proper refresh token -- wondering if I'm missing something.

**Comment by sigma67** [comment]
@apastel what you want is a `RefreshingToken`:

https://github.com/sigma67/ytmusicapi/blob/98e0bc749cb15873b23be3b73894c8931371d339/ytmusicapi/auth/oauth/token.py#L129-L131

Feel free to suggest/submit non-breaking usability changes or documentation if you find time :)

**Comment by apastel** [comment]
@sigma67 Thanks, I figured it had something to do with that but wasn't sure.

My updated code looks like this and is working:
```
from ytmusicapi.auth.oauth import OAuthCredentials, RefreshingToken

session = requests.Session()
oauth = OAuthCredentials(session=session)

code = oauth.get_code()

# tell the user to finish the flow at code['verification_url']

raw_token = oauth.token_from_code(code["device_code"])
ref_token = RefreshingToken(credentials=oauth, **raw_token)

# store the token in oauth.json
ref_token.store_token(<path_to_store_token>)
```
