### ISSUE TITLE
Docs for get_playlist wrong? 

### ISSUE THREAD

**Issue by dmwyatt** [sigma67/ytmusicapi#38]
The docstring for `get_playlist` says it returns a list of playlistItem dictionaries.

I'm only get a dictionary back...not wrapped in a list.  Is it possible for a `playlistId` to return multiple `playlistItem` dictionaries?  I don't have enough experience with the API yet to know if it'll ever return a list, but even if it sometimes returns a list and sometimes a dictionary the docstring seems to be incorrect.

**Comment by sigma67** [comment]
The `:returns` string is wrong, but the return type and example dictionary are correct. Will fix this soon
