### ISSUE TITLE
Open webbrowser on oauth

### ISSUE THREAD

**Issue by gaardhus** [sigma67/ytmusicapi#384]
**Is your feature request related to a problem? Please describe.**
Manually having to copy the url and open a webbrowser when using oauth setup

**Describe the solution you'd like**
Use pythons build-in `webbrowser.open` function to open a webbrowser with the verification url automatically

**Describe alternatives you've considered**

**Additional context**

**Comment by sigma67** [comment]
We can do something like gmusicapi where we make this behavior optional: https://github.com/simon-weber/gmusicapi/blob/5cb3aa3d17f6978e2e15220289daee2b0ceafe44/gmusicapi/clients/shared.py#L145
