### ISSUE TITLE
Albums And Singles Not Available On Artist Page

### ISSUE THREAD

**Issue by MarshallARoss** [sigma67/ytmusicapi#392]
**Describe the bug**
An update to youtube music has nested the albums and singles in a "Top Releases" row with a "see more" click through. 

**To Reproduce**
1. Go to any artist page (ex. https://music.youtube.com/channel/UCeKDV9JgivrXehVluw5bKFA)
2. See "Top Releases" where "Albums" used to be.
3. Click on "Top Releases" or "See More" and see the buttons to switch to "Albums" there

**Additional context**
Calling the "get_artist" function returns the Songs, Videos, and Related sections but not the "Top Releases"

**Comment by sigma67** [comment]
I don't have this update. Can you provide a screenshot?

**Comment by MarshallARoss** [comment]
Sure thing! Here's an example new artist page - with "Top Releases" instead of "Albums and Singles"

![music youtube com_channel_UClmXPfaYhXOYsNn_QUyheWQ](https://github.com/sigma67/ytmusicapi/assets/20109435/58a3b3df-20da-44c0-8359-0a220af9f2ec)

**Comment by MarshallARoss** [comment]
Clicking "more" brings you to: 

https://music.youtube.com/browse/MPADUClmXPfaYhXOYsNn_QUyheWQ

![music youtube com_channel_UClmXPfaYhXOYsNn_QUyheWQ (1)](https://github.com/sigma67/ytmusicapi/assets/20109435/bda659ff-16f7-4548-a722-baf3e281f03e)

**Comment by MarshallARoss** [comment]
Did some digging and for me it's only an issue if I authenticate.

**Comment by sigma67** [comment]
Yeah that would make sense, your account seems to be selected as part of their A/B testing. We'll have to wait for a broader rollout before we can implement it.

**Comment by MarshallARoss** [comment]
Thank you - I'll hack together auth & non-auth pieces on my end. Appreciate all your amazing work!

**Comment by sigma67** [comment]
This update will require translating the string `Top releases` to all supported languages, as that's how the content is currently detected. See here:
https://github.com/sigma67/ytmusicapi/blob/d9f9fcc1477ead219e7c06c593574ba8cc13fe52/ytmusicapi/parsers/i18n.py#L18-L23

**Comment by sigma67** [comment]
Seems pretty experimental to me still. On my main account I'm now getting `Discography` for Ed Sheeran, with a `More` link to a new page with filters for `Albums` and `Songs`.

**Comment by sigma67** [comment]
I'm not seeing `Discography` or `Top releases` anymore. Maybe the feature was cancelled? Are you seeing it still?
