### ISSUE TITLE
get_artist() not always getting albums & singles

### ISSUE THREAD

**Issue by Noiyy** [sigma67/ytmusicapi#393]
**Describe the bug**
Sometimes, for some reason, when I try to `get_artist()`, it will return a dictionary without "albums"
and "singles" and then I end up getting `KeyError: "albums"` or `"singles"` when I try to access them.

**To Reproduce**
1. get `artistID` with `.search(query, "artists", limit=1)[0]["browseId"]`
2. get `artist` with `.get_artist(artistID)`
3. try to access `artist["albums"]` or `artist["singles"]`

**Additional context**
*Also, I don't think `limit` in `search()` works, since it returns more than 1 artist*

`get_artist()` dictionary
*Without KeyError*
![Screenshot 2023-05-13 103936](https://github.com/sigma67/ytmusicapi/assets/83555059/a4ee90a0-6985-44e2-9b2f-4ed3abc3414a)
*With KeyError*
![Screenshot 2023-05-13 105700](https://github.com/sigma67/ytmusicapi/assets/83555059/34656ee1-7434-408b-a932-fc5e79a9c99a)

**Comment by sigma67** [comment]
Likely related to #392 

Regarding limit: https://ytmusicapi.readthedocs.io/en/stable/faq.html#why-is-ytmusicapi-returning-more-results-than-requested-with-the-limit-parameter

**Comment by Noiyy** [comment]
Nope, I don't have "Top Releases" there.

**Comment by sigma67** [comment]
Are you sure you are using the same account as your instance of `YTMusic`? Are you passing credentials to `YTMusic` that belong to the same account?

**Comment by Noiyy** [comment]
I'm using it unauthenticated, since I don't have any need to do that.

**Comment by sigma67** [comment]
Ah alright. I suppose A/B testing would do that when you're not signed in. Please follow #392 for updates.
