### ISSUE TITLE
Add proxy configuration

### ISSUE THREAD

**Issue by OzymandiasTheGreat** [sigma67/ytmusicapi#40]
I've written a Mopidy extension for Youtube Music, using this library, but to be compliant with Mopidy extension guidelines I'd
have to respect global proxy config which is currently not possible.

ytmusicapi seems to use requests under the hood and Mopidy provides proxy config formatted for use with requests,
so all I'd need would be an extra `__init__()` param for YTMusic to pass proxy config to requests.

**Comment by sigma67** [comment]
I have no experience with proxies and personally don't use them. However, I'm open to including an optional constructor parameter. Since I personally can't really test it, you're welcome to submit a pull request!

**Comment by OzymandiasTheGreat** [comment]
Will do, probably tomorrow.
I don't really have experience with proxies either, but for my use case it's not really needed.
Mopidy provides proxy object in format requests expect, so I just need to treat it as opaque object and pass it around.
As for how to make proxy object, requests have plenty of documentation for other use cases, so I don't think there needs to any documentation beyond "proxy object in requests format".

P.S. This is totally unrelated, but my extension depends on fixes made in the past 2 days that are still unreleased to pypi.
Mind sharing when you plan to release next version?

**Comment by sigma67** [comment]
Hey, thanks for the PR. I merged it earlier. I will publish a minor release later today or tomorrow, since I'd like to get some internationalization stuff in as well
