### ISSUE TITLE
[1.1.1] Error on `ytmusic.get_library_upload_songs`

### ISSUE THREAD

**Issue by markmandel** [sigma67/ytmusicapi#406]
**Describe the bug**

Getting the following error when attempting to run `ytmusic.get_library_upload_songs(...)`

```
Traceback (most recent call last):
  File "/home/mark/workspace/ytmusic/./music.py", line 22, in <module>
    uploads = ytmusic.get_library_upload_songs(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mark/workspace/ytmusic/ytmusicapi/mixins/uploads.py", line 49, in get_library_upload_songs
    songs = parse_uploaded_items(results['contents'][1:])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mark/workspace/ytmusic/ytmusicapi/parsers/uploads.py", line 11, in parse_uploaded_items
    entityId = nav(data, MENU_ITEMS)[-1]['menuNavigationItemRenderer']['navigationEndpoint'][
               ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'menuNavigationItemRenderer'
```

**To Reproduce**

```python3
from ytmusicapi import YTMusic

ytmusic = YTMusic("oauth.json")
uploads = ytmusic.get_library_upload_songs(
        order="recently_added",
        limit=500,
)
```

**Additional context**
Just to make sure, I updated my version to 1.1.1, but unfortunately that didn't fix the issue. Wondering if YouTube changed their API surface on uploads.

**Comment by sigma67** [comment]
Hi, this seems to be a Google A/B test currently, so your quick fix won't do it. For me it's failing with this change, while it works on current master.

**Comment by markmandel** [comment]
Aaaah, I had a wonder. 

So will need to redo it as a search rather than a specified number. Sounds like that would be a better option long term anyway.

**Comment by sigma67** [comment]
Are you still seeing this issue?

**Comment by markmandel** [comment]
I've been running my locally edited version, and it's been fine - but as you said, looks like I'm in an A/B, in which case if you want to close this PR, please feel free.

If I run into it again, I'll redo it to make it a search based implementation, so it's future proof (or at least as close as it can be).
