### ISSUE TITLE
Library Podcasts

### ISSUE THREAD

**Issue by sigma67** [sigma67/ytmusicapi#415]
Podcasts are currently rolling out: https://9to5google.com/2023/07/13/youtube-music-podcasts-internationals

We should introduce a new function `get_library_podcasts`, which will be tracked in this issue. Please comment if you want to help! Requirement is obviously that you have access to this new feature.

**Comment by NotLawson** [comment]
yes, we need this

**Comment by MarkhorDev** [comment]
Podcasts also occasionally show up on artist pages 'Videos' section [(example)](https://music.youtube.com/channel/UCD14H15GYNnPRmAwkTnlPHg). When calling get_artist for this artist, a key error is raised. Not sure why this happens though.

**Comment by sigma67** [comment]
@NotLawson are you working on this?

@MarkhorDev I don't see any podcasts under your link. See here for the issue tracking artist page podcast issues https://github.com/sigma67/ytmusicapi/issues/460#issuecomment-1806858037

**Comment by NotLawson** [comment]
Had to have a break during new year/Christma, but am having a look into it now

**Comment by NotLawson** [comment]
Sorry, things are getting a bit busy and this is way down my list. Odds are, I probably won't be coming back to this because I found something different for the job. Sorry all!
