### ISSUE TITLE
KeyError exception when searching community_playlists or featured_playlists with scope = library

### ISSUE THREAD

**Issue by nick42d** [sigma67/ytmusicapi#420]
G'day,

Noticed that the function parsers.search._get_param_2 does not handle "community_playlists" or "featured_playlists".
However, parsers.search.get_search_params calls this function with these parameters when scope is set to "library" and therefore we get a KeyError.

Happy to raise a PR if you are able to advise if this should be handled with a documented exception or alternative params sent to innertube.

Cheers Nick

**To Reproduce**
call YTMusic.search('xxx', 'community_playlists', 'library').
result "KeyError: 'community_playlists'"

**Comment by sigma67** [comment]
I see that appropriate tests are missing as well. https://github.com/sigma67/ytmusicapi/blob/master/tests/test.py#L129

Feel free to fix and add tests :)

**Comment by nick42d** [comment]
Issued PR, please let me know if you see any issues!
