### ISSUE TITLE
'charmap' codec can't encode characters

### ISSUE THREAD

**Issue by periip** [sigma67/ytmusicapi#428]
# Hello and thanks for using ytmusicapi! Please fill out the issue template below. Issues not following this template will be closed without comment. If you have a question only, please use GitHub discussions or gitter (linked in README).
~~~~~~~~~~~~~
**Describe the bug**
A clear and concise description of what the bug is.

I get the exception when calling get_playlist() on playlists with Japanese or Chinese song names:
'charmap' codec can't encode characters in position 2249-2253: character maps to <undefined>

**To Reproduce**
Steps to reproduce the behavior:
PlaylistIDs with Japanese in song titles don't work: PLPK7133-0ahmzknIfvNUMNJglX-O1rTd2
Only English song titles appear to work: PL3-sRm8xAzY8LhlTyJ2uf-EcQSm_vzSqw

If there is a workaround to this, please let me know as I am new to Python.

Thanks

**Comment by sigma67** [comment]
I cannot reproduce this, the playlist you posted works just fine. Must be some issue with your local setup.

What Python version are you running? What is your code?

**Comment by periip** [comment]
Thanks for the quick reply!
I'm running the most up-to-date python version,  3.11.5.
As for the code, I'm making a basic API call, unauthenticated. I'm reading stdin from Node.js using `input()` and printing it back. 
I've tried reinstalling python made sure the values are read fine from input() since I've tested with basic `print()` statements.

```python
from ytmusicapi import YTMusic
import json
# import pafy

url = input()

yt = YTMusic()
try:
    songs = yt.get_playlist(playlistId=url)
    print(songs)
except Exception as e:
    print("Error:", e)
```
