### ISSUE TITLE
Missing videoType and duration_seconds in unavailable tracks

### ISSUE THREAD

**Issue by MishchenkoYuriy** [sigma67/ytmusicapi#430]
ytmusicapi version: 1.2.1

Hi, 

I was fetching tracks with YTMusic.get_playlist() and I found that all unavailable tracks (`'isAvailable': False`) have `'videoType': None` and in some cases missing the `duration_seconds`. I can still access some of this data with YTMusic.get_song() (`musicVideoType` and `durationSeconds` fields).

get_playlist:
```
{'videoId': 'v4um7JFr-SY',
 'title': 'We Can Live Like Maddie and David',
 'artists': [{'name': 'Bebopovsky And The Orkestry Podyezdov', 'id': None}],
 'album': {'name': 'Pink Flamingo Detective Agency', 'id': None},
 'likeStatus': None,
 'thumbnails': [{'url': 'https://lh3.googleusercontent.com/h1hJEQnmaZ9zyRlEU8C0tsyo-HySjc2ADY6NrBXF6znA6O7R6afQt1XItJcrUKK0M_CUzn3UePqKWIR9qg=w60-h60-l90-rj',
   'width': 60,
   'height': 60},
  {'url': 'https://lh3.googleusercontent.com/h1hJEQnmaZ9zyRlEU8C0tsyo-HySjc2ADY6NrBXF6znA6O7R6afQt1XItJcrUKK0M_CUzn3UePqKWIR9qg=w120-h120-l90-rj',
   'width': 120,
   'height': 120}],
 'isAvailable': False,
 'isExplicit': False,
 'videoType': None,
 'setVideoId': 'D1BE74B44EB19F38'}
```

Is this behaviour intentional?

**Comment by sigma67** [comment]
Which tracks? Please list search terms. IIRC this information is simply not provided on the website

**Comment by MishchenkoYuriy** [comment]
```
response = yt.get_playlist(playlist_id, limit=None)
```
The `playlist_id` of my private playlist won't help you. To replicate this problem you can take the `videoId` from my script above, add the track to a new playlist and get the playlist items with YTMusic.get_playlist(). Hope this helps.

**Comment by sigma67** [comment]
So yes, as I mentioned above, YTMusic does not return this data. So there is no way for us to retrieve it.

Check out this playlist: https://music.youtube.com/playlist?list=PLQwVIlKxHM6pdInp9jDol7a2gK17FxEF2

If you hover, there is no Play button nor a duration. In the data the ID is also missing, else it would be parsed correctly.
