### ISSUE TITLE
'videoId': None

### ISSUE THREAD

**Issue by MishchenkoYuriy** [sigma67/ytmusicapi#431]
Hi, I keep exploring the API and found that some unavailable videos have `'videoId': None`.
```
response = yt.get_playlist('PLDcPimbLEWH_w_l05-0Yt25qP2pjqv9Z4', limit=None)
print(response['tracks'][18])
print(response['tracks'][63])
```

```
{'videoId': None,
 'title': 'Royalty Free Music - Very Low Note - Horror - Kevin MacLeod',
 'artists': [{'name': 'Free Royalty Archive', 'id': None}],
 'album': None,
 'likeStatus': None,
 'thumbnails': [{'url': 'https://i.ytimg.com/vi/-IaRXQziS9I/sddefault.jpg?sqp=-oaymwEWCJADEOEBIAQqCghqEJQEGHgg6AJIWg&rs=AMzJL3llfhCmfL2z8YDqLK-_U1lxbpaotQ',
   'width': 400,
   'height': 225}],
 'isAvailable': False,
 'isExplicit': False,
 'videoType': None,
 'duration': '1:24',
 'duration_seconds': 84}
```

However, these videos are available on YouTube and have ids. Is there a way to get these ids with ytmusicapi?

**Comment by sigma67** [comment]
![image](https://github.com/sigma67/ytmusicapi/assets/16363825/04674377-b7fb-4935-b0b7-dcb6fb4edae9)

see #430

Please don't create multiple issues on the same topic

**Comment by sigma67** [comment]
Here is proof that it's not available. This is the raw data provided by the server:

![image](https://github.com/sigma67/ytmusicapi/assets/16363825/1e45ecd1-d236-489c-98b3-d95e45a1fb4f)
