### ISSUE TITLE
Add song to history feature don't work now

### ISSUE THREAD

**Issue by maxrave-dev** [sigma67/ytmusicapi#432]
**Describe the bug**
Add song to history feature don't work now

**To Reproduce**
1. Run this code
```
import ytmusicapi
from ytmusicapi import YTMusic

# ytmusicapi.setup(filepath='oauth.json')
ytmusic = YTMusic("oauth.json")
ytmusic.add_history_item(ytmusic.get_song("4SYW7TrMWOg"))
```
3. Go to [YouTube Music History](https://music.youtube.com/history)
5. Don't see track with this "4SYW7TrMWOg" videoId in history lists

**Comment by maxrave-dev** [comment]
Always response code 400

**Comment by sigma67** [comment]
Check your credentials, I'm getting 204 as usual via `add_history_item`

**Comment by maxrave-dev** [comment]
My credentials are okay, other references work perfectly, only add_history_item doesn't work. I don't know why

**Comment by maxrave-dev** [comment]
@sigma67 here is my oauth.json
![image](https://github.com/sigma67/ytmusicapi/assets/113747128/98c0b4f1-652b-4be3-aec8-74044559a48a)

**Comment by maxrave-dev** [comment]
I resolved with my credentials, thanks @sigma67
