### ISSUE TITLE
Documentation update - get all albums not just 10 from artist page.

### ISSUE THREAD

**Issue by MarshallARoss** [sigma67/ytmusicapi#433]
Documentation update -> Using "channel Id of the artist" only returns 10 albums from get_artist_albums method.

Solution: is to use the "browseID" from the "albums" key of the get_artist response. This will return all the albums from the youtube music albums page.

**Comment by sigma67** [comment]
Tbh it seems quite obvious from my point of view. Where would you like to see this information added?

**Comment by sigma67** [comment]
It's actually right there in the docstring for `get_artist`....
