### ISSUE TITLE
get_charts is having KeyError

### ISSUE THREAD

**Issue by ankydv** [sigma67/ytmusicapi#436]
### [1.2.1/1.1.1] get_charts is having KeyError: -

**To Reproduce**
1. Comment this section in explore.py since it's having KeyError, I'm unable to figure out.. Hence to avoid this error:-
```
charts['countries']['options'] = list(
             filter(None, [
                 nav(m, ['payload', 'musicFormBooleanChoice', 'opaqueToken'], True)
                 for m in nav(response, FRAMEWORK_MUTATIONS)
             ]))
```
1. Call the get_charts function (auth or without auth).

**Additional context**
With some analysis I've figured out that youtube returns different response for different videos.
It appears to only occurs in 'videos' section. Not 'trending'.

**Cause
The NAVIGATION_VIDEO_ID in navigation.py is not sufficient to cover all types of responses from Youtube as the reponse of Youtube is inconsistent.

Expected structure of response:-
```
'navigationEndpoint':  {
					"clickTrackingParams": "CL0JEKCzAhgAIhMImaOrk6rAgQMVq8JzAR3dbAig",
					"watchEndpoint": {
						"videoId": "RLzC55ai0eo",
						"playlistId": "PL4fGSI1pDJn40WjZ6utkIuj2rNg-7iGsq",
						"loggingContext": {
							"vssLoggingContext": {
								"serializedContextData": "GiJQTDRmR1NJMXBESm40MFdqWjZ1dGtJdWoyck5nLTdpR3Nx"
							}
						},
						"watchEndpointMusicSupportedConfigs": {
							"watchEndpointMusicConfig": {
								"musicVideoType": "MUSIC_VIDEO_TYPE_OMV"
							}
						}
					}
```
In some cases, the response is like: -
```
'navigationEndpoint': {
					"clickTrackingParams": "CLEJEKCzAhgBIhMImaOrk6rAgQMVq8JzAR3dbAig",
					"browseEndpoint": {
						"browseId": "MPEDVAdGW7QDJiU",
						"params": "ggMnmgEkCiJQTDRmR1NJMXBESm40MFdqWjZ1dGtJdWoyck5nLTdpR3Nx",
						"browseEndpointContextSupportedConfigs": {
							"browseEndpointContextMusicConfig": {
								"pageType": "MUSIC_PAGE_TYPE_NON_MUSIC_AUDIO_TRACK_PAGE"
							}
						}
					}
				}


				}
```
**Possible solution**

In those cases, the video ID exists somewhere else, not  in 'navigationEndpoint', the navigation should be like: -
NAVIGATION_VIDEO_ID_2 = ['menu','menuRenderer','items',0,'menuServiceItemRenderer','serviceEndpoint','queueAddEndpoint','queueTarget','videoId']

Hence we could fix it by excepting the KeyError with this nav instead.

[Error.txt](https://github.com/sigma67/ytmusicapi/files/12706190/Error.txt)

**Comment by sigma67** [comment]
Which region are you looking at? Please specify the failing call in more detail. If it's the default region for you please figure out which one that is.

**Comment by ankydv** [comment]
I checked for default region as well as my region ('IN"). In both the cases there was the same issue.

**Comment by Arnavop** [comment]
I am also facing the same issue,
for "ZZ" region as well as for "IN" region its giving keyError.

**Comment by ankydv** [comment]
I've the solution, I could raise a pull request.

**Comment by Arnavop** [comment]
> I've the solution, I could raise a pull request.

Yes please PR it 
also whats the solution to this?

**Comment by ankydv** [comment]
> > I've the solution, I could raise a pull request.
> 
> Yes please PR it also whats the solution to this?

I've Created a PR. You could view it.
