### ISSUE TITLE
Getting music videos

### ISSUE THREAD

**Issue by grray** [sigma67/ytmusicapi#44]
Thank you for this wonderful library. I can get music audios, i can get music videos for artist, but is there any way to get music videos bound to albums? I mean get album tracks, and replace music audio with music videos, if they exists. Like in android application, when you play album, or on youtube website — https://www.youtube.com/user/twentyonepilots/playlists this page have "albums" section (if always have it if it's artist channel), and it has music videos. Maybe you can advise some other library for parsing regular youtube pages?

**Comment by sigma67** [comment]
I think this would be difficult to implement without a way to do this in the web UI.

**Comment by sigma67** [comment]
I just saw you can get the playlists on that page with the [YouTube Data API](https://developers.google.com/youtube/v3/docs/playlists/list?apix_params=%7B%22part%22%3A%5B%22contentDetails%22%2C%22id%22%2C%22snippet%22%2C%22status%22%5D%2C%22channelId%22%3A%22UCBQZwaNPFfJ1gZ1fLZpAEGw%22%2C%22maxResults%22%3A30%7D)

There's no way to pick a specific shelf, but you can filter out the music videos based on the description (the albums include the term iTunes with a link)
