### ISSUE TITLE
get_artist doesn't return music videos for some artists

### ISSUE THREAD

**Issue by grray** [sigma67/ytmusicapi#45]
Code to reproduce
```python
import os, json
from ytmusicapi import YTMusic

conf_file = os.path.dirname(__file__)+'/headers_auth.json'
ytmusic = YTMusic(conf_file)

result = ytmusic.get_artist('UCBQZwaNPFfJ1gZ1fLZpAEGw')     
print(json.dumps(result, indent=2)) 
```
doesn't have "videos" section, although youtube music page and android app have it.

**Comment by sigma67** [comment]
Not quite sure, for me it doesn't have a videos section. I see Albums, Singles, Featured On and Fans Might Also Like. Can you post a screenshot of your page?

**Comment by grray** [comment]
Yes, sure. https://imgur.com/a/1kj7TTk My country is Ukraine.

**Comment by grray** [comment]
It shows the same sections even if I'm not logged in. Its weird, perhaps it's region restriction, but why then python script on my machine see it differently?

**Comment by sigma67** [comment]
It might be related to the GL variable configured in context.json. Can you please check your request in browser and report what is used for the GL variable? It should be there in the network tab of your browser under request details.

![grafik](https://user-images.githubusercontent.com/16363825/87541839-3ede9e80-c6a2-11ea-83fa-bcce25a4a2ad.png)

**Comment by grray** [comment]
I have `gl: UA` I tried to change gl in context.json, but it doesn't affect the output, it stays the same. But copying json from browser into context.json solved issue! I found a line, which did trick, it `"browseId": "UCnX0L9QiftAcWdzeBx31xCw"` at json top level.

**Comment by sigma67** [comment]
I don't think it's the browseId, that is being set by the API as well. Can you post your full `context.json` here?

**Comment by grray** [comment]
Oops, i just figured out, that UCnX0L9QiftAcWdzeBx31xCw and UCBQZwaNPFfJ1gZ1fLZpAEGw are two different pages for the same artist and first have videos, while second don't. Don't know whats happening :)

**Comment by sigma67** [comment]
Yes, seems to be a server-side duplicate. Can we consider this issue resolved?

**Comment by grray** [comment]
Yes, thank you. For your information, first one is [Twenty One Pilots - Topic](https://www.youtube.com/channel/UCnX0L9QiftAcWdzeBx31xCw) channel on youtube, [second](https://www.youtube.com/channel/UCBQZwaNPFfJ1gZ1fLZpAEGw) is their official channel, and seems like it should be the same for other artists, which have official youtube channels. They have both the same browseId's for albums, so no luck for me here about getting music videos)
