### ISSUE TITLE
'setvideoid' error on .get_history()

### ISSUE THREAD

**Issue by AsukoRin** [sigma67/ytmusicapi#450]
`ytmusic = ytmusicapi.YTMusic(os.environ["browserjson"])
history = ytmusic.get_history()
last_listened_song = history[0] if history else {}`

history = ytmusic.get_history() gives a KeyError: 'setVideoId' even though it isn't editing or moving playlist items. A couple days ago the code worked normally with no errors and now it doesn't. I have tried to refresh the browser.json file (firefox) and object is created correctly:
`<ytmusicapi.ytmusic.YTMusic object at 0x7fd50a96ea10>`
However code still gives a key error, occasionally changing to Error: 'none'

Larger Snippet:
`def get_last_listened_song():
    global last_listened_song
    while True:
        try:
            history = ytmusic.get_history()
            print(history)
            last_listened_song = history[0] if history else {}
            print('done')
            time.sleep(5)
        except Exception as e:
            print("Error:", str(e))`

My first time writing a bug report so sorry if I did something wrong :p

**Comment by sigma67** [comment]
Please follow the standard issue bug template. Have you noticed any unusual changes in the web UI of your history?

music.youtube.com/history

**Comment by AsukoRin** [comment]
It seems about the same, but there might have been some small change that I haven't noticed. I am still signed in as well

**Comment by joulev** [comment]
Same here too, the following stopped working with the exact same error

```py
import os
import json
from http.server import BaseHTTPRequestHandler
from ytmusicapi import YTMusic, setup

auth = setup(headers_raw=os.environ['YTMUSIC_HEADERS_RAW'])
ytmusic = YTMusic(auth)


class handler(BaseHTTPRequestHandler):
    def do_GET(self):
        self.send_response(200)
        self.send_header('Content-type', 'application/json')
        self.end_headers()
        first_history = ytmusic.get_history()[0]
        message = {
            'videoId': first_history['videoId'],
            'title': first_history['title'],
            'artists': first_history['artists']
        }
        self.wfile.write(json.dumps(message).encode())
        return
```

Web UI of YouTube Music history page looks the same.

**Comment by joulev** [comment]
Without any changes to the code, it suddenly works again at least from today.

**Comment by AsukoRin** [comment]
Still having the same issue

**Comment by sigma67** [comment]
closing this in favor of #462
