### ISSUE TITLE
`KeyError: 'contents'` when searching for a song

### ISSUE THREAD

**Issue by hamza1311** [sigma67/ytmusicapi#451]
**Describe the bug**
Searching for a song fails with `KeyError: 'contents'`

**To Reproduce**

```python
from ytmusicapi import YTMusic

ytmusic = YTMusic('browser.json')

ytmusic.search('end of a life', filter='songs', scope='library', ignore_spelling=True)
```

**Stacktrace**

```
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    ytmusic.search('end of a life', filter='songs', scope='library', ignore_spelling=True)
  File "venv/lib/python3.11/site-packages/ytmusicapi/mixins/search.py", line 178, in search
    results = nav(results, SECTION_LIST)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/ytmusicapi/navigation.py", line 83, in nav
    raise err
  File "venv/lib/python3.11/site-packages/ytmusicapi/navigation.py", line 77, in nav
    root = root[k]
           ~~~~^^^
KeyError: 'contents'
```

**Comment by sigma67** [comment]
This is library search, can you please post a screenshot of what that search result looks like for you in the Web UI.

And a JSON of the server response, if possible.

**Comment by hamza1311** [comment]
Can you provide the code to make a fetch request for the endpoint that's being called? I can make the fetch request from the console and give you the response.

If the request is something the UI makes, Firefox lets you copy the request as fetch from the network tab in the dev tools

**Comment by sigma67** [comment]
You can just replicate the search request on the Web UI and copy the response as you would when copying auth credentials (though response, not request headers in this case).

https://ytmusicapi.readthedocs.io/en/stable/setup/browser.html#copy-authentication-headers

**Comment by hamza1311** [comment]
It must've been some weird A/B thing google did? I just tried again and now it works. Thanks for the help and making this library
