### ISSUE TITLE
feedbackTokens add and remove are swapped

### ISSUE THREAD

**Issue by adamhl8** [sigma67/ytmusicapi#454]
It seems like the `add` and `remove` keys are swapped in `feedbackTokens`.
```python
yt = YTMusic("oauth.json")
tracks = yt.get_library_songs(500)
remove_token = tracks[0].get("feedbackTokens").get("remove")
response = yt.edit_song_library_status([remove_token])
print(response)
```
```
...
{'responseText': {'runs': [{'text': 'Added to library'}]}
```

As you can see I get `Added to library`. I also checked YTM and the track is still there.

If I instead get the `add` token:
```python
yt = YTMusic("oauth.json")
tracks = yt.get_library_songs(500)
add_token = tracks[0].get("feedbackTokens").get("add")
response = yt.edit_song_library_status([add_token])
print(response)
```
```
...
{'responseText': {'runs': [{'text': 'Removed from library'}]}
```

Which does actually remove the track from YTM.

**Comment by sigma67** [comment]
That must be a bug. Are you sure that's what's happening and not some problem with your code?

For reference, this function has been unchanged for two years.

https://github.com/sigma67/ytmusicapi/blob/05a5fb81533089716ce38516dafcdda50c606917/ytmusicapi/parsers/songs.py#L65-L79

**Comment by adamhl8** [comment]
I posted my code verbatim. What's the purpose of swapping the tokens on `71`? I assume that's what's causing the behavior I'm seeing.

**Comment by sigma67** [comment]
Yeah sorry this was buggy. I also added a `inLibrary` flag now to indicate the current status
