### ISSUE TITLE
get_liked_songs works incorrectly or maybe yt music api doesnt return all data

### ISSUE THREAD

**Issue by veber88** [sigma67/ytmusicapi#455]
I call `get_liked_songs` for my Liked playlist. Playlist has 6055 songs, but i receive 5750 songs. Seems this is an issue.

Same problem when I use
`ytmusic.get_playlist('LM', 100000)`

**Comment by sigma67** [comment]
IIRC 5k songs is the official limit of YTMusic playlists, so I'm not surprised there are oddities above that limit

https://www.reddit.com/r/YoutubeMusic/comments/gl0wvw/songs_limits/fquxowq/

**Comment by veber88** [comment]
But i dont receive 5000 as max, i receive 5750. Therefore i think issue isnt related to limit.

**Comment by veber88** [comment]
Ok, thanks for answer!

**Comment by veber88** [comment]
I think this could be related to songs that became unavailable.
I found for test 1 unavailable song and it wasnt returned to me via ytmusicapi.
But yt music app shows this song in its list (as unavailable song but it is in list)

**Comment by sigma67** [comment]
You could try to open the entire playlist on the web (keep scrolling down) and count the unavailable ones?

Although the function used for `get_liked_songs` is able to parse unavailable songs correctly, i.e. if you fetch a playlist with unavailable songs they show up in the result.
