### ISSUE TITLE
get background music metainfo

### ISSUE THREAD

**Issue by poly000** [sigma67/ytmusicapi#459]
**Is your feature request related to a problem? Please describe.**
Videos' titles need some ugly workaround (like [`/(?:[[({【]([^\])}】]+)[\])}】]\s*)*([^[({【「\])}】」\-/]+)(?:[[({【]([^\])}】]+)[\])}】]\s*)*/g;`](https://github.com/organization/alspotron/blob/cc25e4f47cfb461e3aeec0293e42329138c7df0b/example/alspotron-plugin/index.js#L1) in [Alspotron](https://github.com/organization/alspotron)) to produce an effective lyric query keyword (although we could get subtitles from youtube, there are not always)

**Describe the solution you'd like**
Find related api from youtube

**Describe alternatives you've considered**
Create a BrowserWindow and read background music metainfo with DOM (in electron)
In python running a webDriver is considered much more expensive

**Additional context**
![image](https://github.com/sigma67/ytmusicapi/assets/34085039/fbae8ef5-488e-4817-ba46-e98e2fdc0695)

**Comment by sigma67** [comment]
>  Find related api from youtube

I'm confused, what are you requesting? Please be more precise

**Comment by poly000** [comment]
> > Find related api from youtube
> 
> I'm confused, what are you requesting? Please be more precise

ok, it's orginally required by https://github.com/th-ch/youtube-music/issues/1323
we need to get background music information from youtube

**Comment by sigma67** [comment]
OK, that's cool, but that's a JS project? This is a fan-made Python API, not Google support

**Comment by poly000** [comment]
> OK, that's cool, but that's a JS project? This is a fan-made Python API, not Google support

I thought this API lib has no idea to background music too
While there's no related youtube data api
