### ISSUE TITLE
get_artist_albums/singles: support pagination

### ISSUE THREAD

**Issue by H3adsho0ot** [sigma67/ytmusicapi#461]
If you try to get a lot of albums the first request won't contain all entries. Roughly the first 110 albums get returned. If there are more youtube seems to use some kind of paging/lazy loading. 

For example here: https://music.youtube.com/browse/MPADUC6LfFqHnWV8iF94n54jwYGw

Youtube seems to send a next request to browse with type next on such pages:
![image](https://github.com/sigma67/ytmusicapi/assets/8555086/21b500e2-1deb-46f3-b887-7344d50c1831)

Would be nice to have a parameter to get all or something

**Comment by sigma67** [comment]
`get_artist_albums` supports the `limit` parameter since 1.5.0, somehow I missed this issue

f2be19416bccb762ba27d1c72d4fb7a6f0ada664
