### ISSUE TITLE
Setting a custom timeout does not work...

### ISSUE THREAD

**Issue by TheWicklowWolf** [sigma67/ytmusicapi#464]
**Describe the bug**
Setting a custom timeout has no effect and I still get `('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))`

Also in the docs it states `ytm = YTMusic(session=s)` however, `session`is incorrect. I think it should be `requests_session`.

**To Reproduce**
```
from ytmusicapi import YTMusic
import requests
import functools
import time

s = requests.Session()
s.request = functools.partial(s.request, timeout=600)
ytmusic = YTMusic(requests_session=s)
search_results = ytmusic.search(query="random", filter="songs", limit=5)
time.sleep(300)
search_results = ytmusic.search(query="random", filter="songs", limit=5)
```

**Comment by sigma67** [comment]
Is your error even timeout related? It basically just takes your session and uses it:

https://github.com/sigma67/ytmusicapi/blob/05a5fb81533089716ce38516dafcdda50c606917/ytmusicapi/ytmusic.py#L76-L77

Where did you see the wrong part in the docs? Please provide a link

**Comment by TheWicklowWolf** [comment]
https://github.com/sigma67/ytmusicapi/blob/05a5fb81533089716ce38516dafcdda50c606917/ytmusicapi/ytmusic.py#L53C1-L55C37

**Comment by TheWicklowWolf** [comment]
> Is your error even timeout related? It basically just takes your session and uses it:

I'm not sure, I thought if I set the session timeout then the connection should still be open. Maybe not, what else could cause this error?

**Comment by sigma67** [comment]
Good catch on the docs issue.

Here's some info on your error: https://stackoverflow.com/questions/61303351/why-does-requests-session-get-raise-an-requests-exceptions-connectionerror-in

It's not an issue with the ytmusicapi implementation, you'll need to handle the error on your end

**Comment by sigma67** [comment]
Feel free to submit a PR if you want

**Comment by TheWicklowWolf** [comment]
> It's not an issue with the ytmusicapi implementation, you'll need to handle the error on your end

Ok, thanks for the clarification!
