### ISSUE TITLE
Top Result doesn't have an ID?

### ISSUE THREAD

**Issue by polvallverdu** [sigma67/ytmusicapi#466]
# Hello and thanks for using ytmusicapi! Please fill out the issue template below. Issues not following this template will be closed without comment. If you have a question only, please use GitHub discussions or gitter (linked in README).
~~~~~~~~~~~~~
**Describe the bug**
When searching, top result doesn't contain the browseId for Albums. 

```json
{
    "category": "Top result",
    "resultType": "album",
    "title": "DONDE QUIERO ESTAR",
    "artists": [
      {
        "name": "Quevedo",
        "id": "UC7PL9aor5qNRhvhWWVXyOqA"
      }
    ],
    "thumbnails": [
      {
        "url": "https://lh3.googleusercontent.com/hzdd5VEdCJC9gfcTimpjiZO2KZAo2_dVdU_cS4enWqkfvaHQVAsRI9bbFMbQMsTKD-PXoJbQOSZo-g=w60-h60-l90-rj",
        "width": 60,
        "height": 60
      },
      {
        "url": "https://lh3.googleusercontent.com/hzdd5VEdCJC9gfcTimpjiZO2KZAo2_dVdU_cS4enWqkfvaHQVAsRI9bbFMbQMsTKD-PXoJbQOSZo-g=w120-h120-l90-rj",
        "width": 120,
        "height": 120
      },
      {
        "url": "https://lh3.googleusercontent.com/hzdd5VEdCJC9gfcTimpjiZO2KZAo2_dVdU_cS4enWqkfvaHQVAsRI9bbFMbQMsTKD-PXoJbQOSZo-g=w226-h226-l90-rj",
        "width": 226,
        "height": 226
      },
      {
        "url": "https://lh3.googleusercontent.com/hzdd5VEdCJC9gfcTimpjiZO2KZAo2_dVdU_cS4enWqkfvaHQVAsRI9bbFMbQMsTKD-PXoJbQOSZo-g=w544-h544-l90-rj",
        "width": 544,
        "height": 544
      }
    ]
  }
```

**To Reproduce**
Search an album, and check that top result doesn't have a browseId

**Comment by sigma67** [comment]
This should be fixed? https://github.com/sigma67/ytmusicapi/issues/448

**Comment by polvallverdu** [comment]
That's solved, sorry. My issue is a bit related, not with how this library works, but with ytmusic. I always filter for albums, since from there I can get all the songs of the albums + the one I want. The thing is, I just found a few songs that are singles, that in theory should have or be an album, but aren't. For example, try searching `Antidepresivos Saiko` with the library and with ytmusic. It's a single, and it even says it, but not even in the app you can find it with albums filter (you can find any other single as an album). I needed to investigate further and I don't think you can do anything about it, that's why I'm closing the issue.
