### ISSUE TITLE
Get album information from `get_song` method

### ISSUE THREAD

**Issue by lukekh** [sigma67/ytmusicapi#468]
**Is your feature request related to a problem? Please describe.**
I've been trying to use this to scrape playlists and filtering (e.g. filter playlist for songs that are released in the last calendar year). I've been using
```python
song = ytmusic.get_song(videoID)
date = song['microformat']['microformatDataRenderer']['publishDate']
```
but this is fairly unreliable. Is there any information that can trace this back to the album? Is it possible to infer this somehow and make a method to get the album given the song's videoID?

**Describe the solution you'd like**
I would like a method that allows me to get an album's information given I have the id of a song from the album.

**Describe alternatives you've considered**
I've attempted using other bits of metadata to trace this back but I've been unsuccesful.

**Comment by sigma67** [comment]
You can use 

```
watch_playlist = get_watch_playlist(videoId)
album = get_album(watch_playlist['tracks'][0]['album']['id'])
year = album['year']
```
