### ISSUE TITLE
`get_album_browse_id()` not working for some URLs

### ISSUE THREAD

**Issue by bharat-nair** [sigma67/ytmusicapi#470]
**Describe the bug**
While using `get_album_browse_id()` , some playlist URLs do not give any `browse_id`

**To Reproduce**
`YTMusic().get_album_browse_id("OLAK5uy_nbMYyrfeg5ZgknoOsOGBL268hGxtcbnDM")` will give an empty string.

**Additional context**
Upon checking the page source for this particular playlist, (https://music.youtube.com/playlist?list=OLAK5uy_nbMYyrfeg5ZgknoOsOGBL268hGxtcbnDM) the `browseId` seems to be there but in this string unescaped form:
`...x22:\x7b\x22browseId\x22:\x22MPREb_scJdtUCpPE2\x22,\x22b...`

**Comment by bharat-nair** [comment]
Going through the implementation, ([L344](https://github.com/sigma67/ytmusicapi/blob/2d2ab999a283200c89cf5a13a3ccf854b3dcc7f2/ytmusicapi/mixins/browsing.py#L344)) perhaps another regex can be added like: `re.findall(r"\\x22MPRE.+?\\x22", response.text)`

**Comment by sigma67** [comment]
Some unicode shenanigans going on, will fix in a moment
