### ISSUE TITLE
OpenAPI spec?

### ISSUE THREAD

**Issue by rcourtna** [sigma67/ytmusicapi#471]
**Is your feature request related to a problem? Please describe.**
I would like to allow OpenAI GPTs to interact with the ytmusicapi

**Describe the solution you'd like**
GPT Actions can interact with any AI having an OpenAPI specification 

**Describe alternatives you've considered**
No alternatives considered

**Additional context**
na

**Comment by sigma67** [comment]
This is not a REST API. This merely emulates the Web Client's requests to the innertube API

innertube API is not officially supported by Google

What you're looking for is probably the YouTube Data API, which is officially supported and has a specification, although limited support for YouTube Music

If you wanted you could probably build a server-wrapper around ytmusicapi, providing your own REST API centered around YouTube Music's functions. I know there's quite a few apps out there that use ytmusicapi in their backend
