### ISSUE TITLE
Get_search_suggestions KeyError: 'searchSuggestionRenderer'

### ISSUE THREAD

**Issue by nick42d** [sigma67/ytmusicapi#472]
**Describe the bug**
Google seems to have added history type suggestions to the search suggestions (example below from the app) at some point. These are under a different key to regular search suggestions so the current implementation will fail if history exists (example below of the JSON structure).
![image](https://github.com/sigma67/ytmusicapi/assets/133559267/8da6618d-2a72-4075-86ad-8f22b0e1bd07)
![image](https://github.com/sigma67/ytmusicapi/assets/133559267/078d458a-126b-4696-a531-e4e68828471d)

Proposal:
get_search_suggestions revised to:
1. look at historySuggestionRenderer if searchSuggestionRenderers not in the list of contents.
2. return suggestion type as well as the suggestions themselves.

**To Reproduce**
1. Setup a new Oauth session
2. Run get_search_suggestions twice in a row (first time adds it to your history).
4. KeyError: 'searchSuggestionRenderer'

**Additional notes**
From the screenshot, seems there is also a way to delete search history suggestions, this could be a future enhancement

**Comment by sigma67** [comment]
was addressed in #495

the future enhancement to delete search suggestions is tracked in #497
