### ISSUE TITLE
OAuth Error

### ISSUE THREAD

**Issue by gro-david** [sigma67/ytmusicapi#475]
**Describe the bug**
Even though the YTMusic class is authenticated (_check_auth returns True), upload_song raises the "Provide authentication" error.

**To Reproduce**
1. Create and oauth.json
2. pass it into a YTMusic class
3. test upload_song

**Additional context**
I am on Arch Linux with python 3.11.
I think the problem is at uploads:197. after commenting line 197 and 198 out i got the error that x-goog-authuser is not a valid key.

**Comment by sigma67** [comment]
https://ytmusicapi.readthedocs.io/en/stable/setup/index.html

OAuth doesn't work for uploads
