### ISSUE TITLE
Missing songs in get_artist clarification.

### ISSUE THREAD

**Issue by Schtenk** [sigma67/ytmusicapi#479]
Sorry for opening another issue but I just wanted to clarify what I wanted to get across in the last issue: #477 

The reason I created the last issue was because saw this comment in mixins/browsing.py 
`if 'musicShelfRenderer' in results[0]:  # API sometimes does not return songs`
and thought that what I discussed in #477  might be the issue.

**Comment by sigma67** [comment]
As you can see by the links I provided in the discussion, the content provided by the server is simply different.

Please only create an issue when you know specifically that there is a bug in the project, not because you're confused about how YouTube Music works. That's for Q&A/discussions.
