### ISSUE TITLE
get_playlist(playlist_id) throws an error at line 112 due to structural page changes

### ISSUE THREAD

**Issue by marcuma** [sigma67/ytmusicapi#481]
**Describe the bug**
When attempting to get the songs from a playlist, a Key Error is thrown when attempting to get the playlistId from the nav result. 

```
Traceback (most recent call last):
  File "/Users/marcuma/Documents/VSCode Workspace/ytapitest/ytapitest.py", line 28, in <module>
    songs = ytmusic.get_playlist(playlist_id, 1)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/ytmusicapi/mixins/playlists.py", line 112, in get_playlist
    playlist = {'id': results['playlistId']}
                      ~~~~~~~^^^^^^^^^^^^^^
KeyError: 'playlistId'
```

In the reference docs, under get_artist it says to call get_playlist with the browseId, but uder get_playlist and the function header it says to use playlistId, so I tried it with both. b browseId returns a 404 and playlistId throws the above error. 

I could be doing something wrong, but from what I can tell, it looks like the data structure being returned from nav isn't as expected and the key can't be located. 

Here is the client code that produced the error (Note that the channel ID is hard coded). 

```python
from ytmusicapi import YTMusic
import json

ytmusic = YTMusic()

artists = ytmusic.search("Red", "artists")

for artist in artists:
    print(artist)
    print("\r\r")


artist = ytmusic.get_artist("UCxZlJwRYVVaZSqRS4RArrhw")

params = artist["albums"]["params"]
albums = ytmusic.get_artist_albums(artist["channelId"], params)

for album in albums:
    playlist_id = album["playlistId"]
    browse_id = album["browseId"]
    print("Title: ", album["title"])
    print("playlist_id = ", playlist_id)
    print("browse_id = ", browse_id)
    print("\r\r")
  
songs = ytmusic.get_playlist(playlist_id, 1)
```

**Comment by marcuma** [comment]
I looked at this for a little bit. It looks like they changed the format of the page/json. Some keys were removed and some added, and the track data is much deeper. Most of playlist.py after the response returns would have to be rewritten to accommodate the change.

**Comment by sigma67** [comment]
You're using `get_playlist` to retrieve an album, of course it's not working. 

Use `get_album_browse_id` to retrieve the `browseId` belonging to a `audioPlaylistId`, then call `get_album`.
