### ISSUE TITLE
get_library_upload_songs() returns empty result even though the library contains one song

### ISSUE THREAD

**Issue by fischcode** [sigma67/ytmusicapi#482]
**Describe the bug**
get_library_upload_songs() returns an empty result

**To Reproduce**
with my login, get_library_upload_songs() in mixins/uploads of ytmusicapi version 1.3.2
obtains the following response on line 45:
[get_library_update_songs_response.json](https://github.com/sigma67/ytmusicapi/files/13573645/get_library_update_songs_response.json)

on line 49, an empty array is returned, mainly because the (only) song of the result is contained in results['contents'][0] and thus excluded when filtering results['contents'][1:] - apparently the response follows a different pattern than expected.

**Comment by sigma67** [comment]
For me it looks like this, that's why the first item is excluded:

![image](https://github.com/sigma67/ytmusicapi/assets/16363825/f4d5c662-37d5-446c-bf70-b7eccefcd753)

What does it look like for you?

**Comment by fischcode** [comment]
Hi

 

This is what I see with https://music.youtube.com/library/uploaded_songs when filtering for titles:

 



 

Without any filter, I see this:

 



 

Does this help you?

 

Best regards

 

 

Von: sigma67 ***@***.***> 
Gesendet: Mittwoch, 6. Dezember 2023 10:35
An: sigma67/ytmusicapi ***@***.***>
Cc: fischcode ***@***.***>; Author ***@***.***>
Betreff: Re: [sigma67/ytmusicapi] get_library_upload_songs() returns empty result even though the library contains one song (Issue #482)

 

For me it looks like this, that's why the first item is excluded:

image.png (view on web) <https://github.com/sigma67/ytmusicapi/assets/16363825/f4d5c662-37d5-446c-bf70-b7eccefcd753> 

What does it look like for you?

**Comment by sigma67** [comment]
Images via email didn't work.

PR welcome

**Comment by sigma67** [comment]
fixed in [8f7970b](https://github.com/sigma67/ytmusicapi/commit/8f7970b2643379c26f2cfcc739df69b31baabd7b)
