### ISSUE TITLE
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 12-13

### ISSUE THREAD

**Issue by ccyang2019** [sigma67/ytmusicapi#5]
a little issue at request body which is not default `Latin-1` encoded. 
add `body = body.encode(encoding='utf-8')` after line 453 of ytmusic.py could solve my problem.

**Comment by sigma67** [comment]
Thanks for the report. It seems this is only the case when a string is passed to the requests parameter `body`, so the other functions using `json` are not affected.
