### ISSUE TITLE
OAuth Login Broken in 

### ISSUE THREAD

**Issue by danielfullerton** [sigma67/ytmusicapi#501]
**Describe the bug**
After running `ytmusicapi oauth` on version 1.4.0 (freshly installed via pip), and performing the auth flow as usual, I get the following error:

![image](https://github.com/sigma67/ytmusicapi/assets/22799770/4260383e-e577-4cc6-bda0-cc448e83ea7e)

After reverting to the previous release (1.3.2), I did not encounter this bug, so it seems like a regression defect.

**To Reproduce**
1. `pip install ytmusicapi`
2. `ytmusicapi oauth`

**Additional context**
- Python v3.12.1
- pip v23.2.1
- Windows 11
- Powershell 7.x

Hope this helps.

**Comment by sigma67** [comment]
Hi, sorry that this is happening. Please verify that the PR fixes your issue:

``pip install git+https://github.com/sigma67/ytmusicapi@fix-501``
