### ISSUE TITLE
KeyError in get_mood_playlists function 

### ISSUE THREAD

**Issue by JDFraire-P** [sigma67/ytmusicapi#507]
When using the get_mood_playlists function I get the following KeyError:

```
>>> yt.get_mood_categories()['Genres'][23]
{'title': 'Regional Mexican', 'params': 'ggMPOg1uX2hmQXdqbHBjT3Zw'}

>>> yt.get_mood_playlists("ggMPOg1uX2hmQXdqbHBjT3Zw")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jd-fraire/.local/lib/python3.11/site-packages/ytmusicapi/mixins/explore.py", line 87, in get_mood_playlists
    playlists += parse_content_list(results, parse_playlist)
  File "/home/jd-fraire/.local/lib/python3.11/site-packages/ytmusicapi/parsers/browsing.py", line 49, in parse_content_list
    contents.append(parse_func(result[key]))
KeyError: 'musicTwoRowItemRenderer'

```

**Comment by sigma67** [comment]
What is your location? And/or `location` param to `YTMusic`? I don't have any "Regional Mexican" genres, and can't request your param using `get_mood_playlists` without getting error 500

**Comment by JDFraire-P** [comment]
This is my YTMusic object:
`yt = YTMusic("JDFraire.json", location="MX")`

**Comment by sigma67** [comment]
I honestly don't know why that one would be any different. Can you visit the page using the web UI?

https://music.youtube.com/moods_and_genres

What does it look like?

**Comment by JDFraire-P** [comment]
It seems to be an internal YouTube error 

![IMG_20240107_150756](https://github.com/sigma67/ytmusicapi/assets/78577166/038b8883-28bb-46c2-89fc-673347ed1b31)
![IMG_20240107_150730](https://github.com/sigma67/ytmusicapi/assets/78577166/86f48476-d130-41b6-9c95-778dbbdd12b1)
