### ISSUE TITLE
get_library_playlists returns at most 25 playlists

### ISSUE THREAD

**Issue by Blefish** [sigma67/ytmusicapi#514]
**Describe the bug**
I recently made some new playlists and noticed that the API is not detecting some playlists anymore. After fiddling around with `limit=` parameter, it seems like at most, 25 playlists are always returned, regardless of what the limit is.

**To Reproduce**

Create more than 25 playlists in YouTube Music.

```python
from ytmusicapi import YTMusic

ytmusic = YTMusic('oauth.json')
print(len(ytmusic.get_library_playlists(limit=None)))
```

```console
./python test.py
25
```

ytmusicapi 1.4.2

**Comment by Blefish** [comment]
After more digging, this actually seems broken on website client aswell :exploding_head: . When scrolling down in https://music.youtube.com/library/playlists , it will show loading infinitely. The problem does not appear when going through YouTube interface, but I guess there is no way to fix this on this library side then ¯\_(ツ)_/¯

**Comment by sigma67** [comment]
Thanks for cross-checking. I assume it's a server-side problem that will probably be solved in a few days.

Don't hesitate to pester Google support about it 😉
