### ISSUE TITLE
ytmusicapi doesn't handle playlists appearing in top results

### ISSUE THREAD

**Issue by fischcode** [sigma67/ytmusicapi#524]
During tests of YTMusic.search() I ran across a query 'fdsfsfsd' returning a playlist as a top result. However the method parse_top_result() of the search parser fails to handle playlists. In this particular case, the following addition extracts some useful data:

    if result_type in ['playlist']:
        search_result['browseId'] = nav(data, MENU_PLAYLIST_ID)
        search_result['title'] = nav(data, TITLE_TEXT)
        runs = nav(data, ['subtitle', 'runs'])[2:]
        search_result['artists'] = parse_song_artists_runs(runs)

Unfortunately, I don't have any other examples to test this code against, but maybe other users have experienced similar cases and can test the code against theirs?

**Comment by sigma67** [comment]
PR welcome

**Comment by fischcode** [comment]
Hi @sigma67
Managed to test a few more cases and realized that the above code returns the playlist creator as a standard 'artists' array (with 'name's and 'id's) while ytmusicapi renders playlist creators as an 'author' dict with 'name' and 'id' in the case of get_playlist() and as an 'author' string object in the case of search(): As I find this quite tedious to handle downstream, I wonder if I should really write code to extract the playlist creator's name and return it as a string instead of leaving the 'artists' array: Is there a particular reason for these differences?

**Comment by sigma67** [comment]
Because playlist creators can also be user channels

**Comment by fischcode** [comment]
Hi @sigma67
Managed to test a few more cases and realized that the above code returns the playlist creator as a standard 'artists' array (with 'name's and 'id's) while ytmusicapi renders playlist creators as an 'author' dict with 'name' and 'id' in the case of get_playlist() and as an 'author' string object in the case of search(): As I find this quite tedious to handle downstream, I wonder if I should really write code to extract the playlist creator's name and return it as a string instead of leaving the 'artists' array: Is there a particular reason for these differences?
