### ISSUE TITLE
Autocompletion API

### ISSUE THREAD

**Issue by AgentSmith0** [sigma67/ytmusicapi#533]
**Is your feature request related to a problem? Please describe.**
For giving autocomplete suggestions while searching for a song, this would be useful.

**Describe the solution you'd like**
A method that returns possible autocomplete suggestions and song/artist ids.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by sigma67** [comment]
https://ytmusicapi.readthedocs.io/en/stable/reference.html#ytmusicapi.YTMusic.get_search_suggestions
