### ISSUE TITLE
The songs search not limit the results

### ISSUE THREAD

**Issue by DavidGarzonV** [sigma67/ytmusicapi#534]
**Describe the bug**

When i search songs with a filter query like the code below, and sending the limit, i'm getting always 20 results, instead of 10:
```python
search_song_results = ytmusic.search(
    query=f"{title} {artist}",
    filter="songs",
    scope=None,
    limit=10,
    ignore_spelling=False
)
```

**To Reproduce**
1. Create the YTMusic object
2. Call the method search, sendig all the params
3. Print the len of the resulting list: `print(len(results))`
4. See error when the len is 20 instead the limit value

**Additional context**
- In other scenary, if i put the limit on 30, i get 40 results in the list.

**Comment by sigma67** [comment]
https://ytmusicapi.readthedocs.io/en/stable/faq.html#why-is-ytmusicapi-returning-more-results-than-requested-with-the-limit-parameter
