### ISSUE TITLE
TypeError: RefreshingToken.__init__() got an unexpected keyword argument 'filepath'

### ISSUE THREAD

**Issue by linsomniac** [sigma67/ytmusicapi#538]
**Describe the bug**
I haven't used my session in days or more, and I believe it's going to refresh the token, but (with version 1.5.2 and also experienced on 1.4.2), I'm getting the following traceback:

```python
Traceback (most recent call last):
  File "/home/sean/.cache/pypoetry/virtualenvs/spotify2ytmusic--SB_8d7f-py3.10/bin/s2yt_list_playlists", line 6, in <module>
    sys.exit(list_playlists())
  File "/home/sean/projects/spotify_to_ytmusic/spotify2ytmusic/cli.py", line 22, in list_playlists
    yt = backend.get_ytmusic()
  File "/home/sean/projects/spotify_to_ytmusic/spotify2ytmusic/backend.py", line 27, in get_ytmusic
    return YTMusic("oauth.json")
  File "/home/sean/.cache/pypoetry/virtualenvs/spotify2ytmusic--SB_8d7f-py3.10/lib/python3.10/site-packages/ytmusicapi/ytmusic.py", line 139, in __init__
    self._token = RefreshingToken(
TypeError: RefreshingToken.__init__() got an unexpected keyword argument 'filepath'
```

The RefreshingToken() is getting created with a `self._input_dict` that contains a "filepath": "oauth.json" element.

If I remove the filepath from the dict, it seems to succeed, but I don't know the code well enough to know if that's a bit naive.

Adding above the "RefreshingToken" above (ytmusic.py line 139) which reads:

```python
if 'filepath' in self._input_dict:
    del(self._input_dict['filepath'])
```

Seemed to work for me.

**To Reproduce**
1. Login with ytmusicapi.
2. Wait for oauth to time out.
3. Do `YTMusic("oauth.json")`

**Comment by sigma67** [comment]
`_input_dict` is what you're passing in via `oauth.json`

Fix your `oauth.json` to not contain `filepath` and you're good to go

**Comment by linsomniac** [comment]
There is no "filepath" in my "oauth.json", and if there were it is not something that I would have put in there, I created it with "ytmusicapi oauth".

**Comment by sigma67** [comment]
#536
