### ISSUE TITLE
method to fetch current playing song

### ISSUE THREAD

**Issue by TAMILVIP007** [sigma67/ytmusicapi#549]
**Is your feature request related to a problem? Please describe.**
I was wondering for any method to get current playing song using this api

**Describe the solution you'd like**
It'd be nice if this library has any methods to fetch the current song

**Describe alternatives you've considered**
sorry, i didn't come across any alternatives

**Additional context**
well... nope nothing more than this

**Comment by sigma67** [comment]
it's not possible, this is not spotify

please use search: https://github.com/sigma67/ytmusicapi/issues?q=is%3Aissue+playing+song
