### ISSUE TITLE
'YTMusic' object has no attribute 'get_song'

### ISSUE THREAD

**Issue by humbleirc** [sigma67/ytmusicapi#55]
Firstly thank you for your great work with ytmusicapi. According to the [documentation](https://ytmusicapi.readthedocs.io/en/latest/reference.html#ytmusicapi.YTMusic.get_song), I should be able to get metadata about a video, but it seems like that endpoint does not exist in the source code.

`AttributeError: 'YTMusic' object has no attribute 'get_song'`

I'm currently using ytmusicapi-0.9.1.
Thank you for your attention.

**Comment by scrimshander** [comment]
Are you using an authenticated or unauthenticated instance of the class? I have found that some calls (I'm pretty sure `get_song` is one of them) do not work when authenticated, and require an unauthenticated instance. Potential enhancement to handle this gracefully.

**Comment by humbleirc** [comment]
It worked using an authenticated instance of `ytmusicapi.YTMusic`. Thanks for your answer :)
