### ISSUE TITLE
create a *get_album_playlist_id* function

### ISSUE THREAD

**Issue by spystrach** [sigma67/ytmusicapi#553]
**Is your feature request related to a problem? Please describe.**
Hello, for a personal project, i use a lot the *get_album_browse_id* function that map for an album, the *AudioPlaylistId* to the *BrowseId*.
But there is not a reciprocal function.

**Describe the solution you'd like**
I would need to use a new function named **get_album_playlist_id** that would map the *BrowseId* to the *AudioPlaylistId*.

**Describe alternatives you've considered**
I could run the `get_album(browse_id)['audioPlaylistId']` to extract all the album info and keep only the playlist id, but i would like to keep things clean.

**Additional context**
I already created this function that leverage the redirect from *https://music.youtube.com/browse/browse_id*.
I could do a pull-request.
![test_success](https://github.com/sigma67/ytmusicapi/assets/100165613/043bf8bf-8254-468b-8d49-49eae631c94e)

**Comment by sigma67** [comment]
don't need a function for that ;)

https://ytmusicapi.readthedocs.io/en/stable/faq.html#what-is-a-browseid

**Comment by sigma67** [comment]
What's the issue with `get_album(browse_id)['audioPlaylistId']` ?

Feel free to write your own `YTMusic` class inheriting from `YTMusic` & add a wrapper around it, if you think it's too verbose.
