### ISSUE TITLE
[Artist] - Dict Key Params is missing

### ISSUE THREAD

**Issue by ToniDarodda** [sigma67/ytmusicapi#568]
**Describe the bug**
artist_details = ytmusic.get_artist(artist_id)
print(artist_details['params']) // error occur dict Key does not exist

**Additional context**
using:  ytmusicapi-1.6.0
MacOs

**Comment by sigma67** [comment]
why do you think that key should exist?

**Comment by ToniDarodda** [comment]
<img width="718" alt="Screenshot 2024-03-26 at 01 19 35" src="https://github.com/sigma67/ytmusicapi/assets/158978450/85aec46d-2ee6-4eff-9fee-beea9021522d">

Hmm, following the documentation says it should, am i wrong?

**Comment by sigma67** [comment]
It clearly says it's a function parameter, not part of the return value. Check the function linked at `Returns` for the return dict format
