### ISSUE TITLE
oauth.json cannot be used for authenticated requests

### ISSUE THREAD

**Issue by Abbotta4** [sigma67/ytmusicapi#572]
**Describe the bug**
`oauth.json` files cannot be used for authenticated API calls, but `browser.json` can.

**To Reproduce**

1. `$ ytmusicapi oauth`
2. follow the link and authorize the application
3. use `ytmusic = YTMusic("oauth.json")` and try to upload a song with `ytmusic.upload_song("test.flac")`

```
$ python /home/drew/ytmusicapi/upload.py 01\ -\ Washed\ Away.flac
Traceback (most recent call last):
  File "/home/drew/ytmusicapi/upload.py", line 13, in <module>
    r = ytmusic.upload_song(f)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/drew/ytmusicapi/lib/python3.11/site-packages/ytmusicapi/mixins/uploads.py", line 198, in upload_song
    raise Exception("Please provide authentication before using this function")
Exception: Please provide authentication before using this function
```

**Additional context**
`ytmusic.upload()` works when authenticating with browser authentication

**Comment by sigma67** [comment]
Guard already exists...

It's impossible to get your error message if you really provided credentials to your ytmusic instance
