### ISSUE TITLE
SAPISIDHASH isn't correctly calculating

### ISSUE THREAD

**Issue by powerball123** [sigma67/ytmusicapi#576]
Hi,

The SAPISIDHASH isn't correctly calculating so when getMainPage run I get the following error 'could not find "ytcfg". Are you sure SID, HSID, SSID, APISID, SAPISID are correct?'

I have to relog into my youtube studio and then add my cookies and session token back in. I think its because SAPISIDHASH  isn't calculating correctly after youtube studio refreshes it?

**Comment by powerball123** [comment]
sorry it's correctly calculating but when i try call it again, I can't get the VISITOR_DATA variable

**Comment by sigma67** [comment]
I'm not sure what you're doing, but this library does not work with YouTube studio
