### ISSUE TITLE
Need support binary package

### ISSUE THREAD

**Issue by duongnguyenty88** [sigma67/ytmusicapi#584]
**Is your feature request related to a problem? Please describe.**
I really enjoy using this library and would like to be able to use it as a binary package, similar to https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp. However, the library does not currently support this feature.

**Describe the solution you'd like**
Your support with a binary package would be greatly appreciated and beneficial for me.

**Comment by sigma67** [comment]
why not? https://ytmusicapi.readthedocs.io/en/stable/faq.html#how-do-i-package-ytmusicapi-with-pyinstaller
