### ISSUE TITLE
rate_playlist() returning 404 "Requested entity was not found."

### ISSUE THREAD

**Issue by jonathanbell** [sigma67/ytmusicapi#585]
**Describe the bug**

Version 1.7.0 - calling `rate_playlist()` with a valid `browseId` results in a 404 error/exception. 

**To Reproduce**

Steps to reproduce the behaviour: 

1. Create a simple call to `rate_playlist()`

```python
def test():
    print("Start...")
    ytmusicapi.rate_playlist(
        "VLRDCLAK5uy_nKfNEHo6Yu1lao4pamzirHgatT0liBhzY", "LIKE"
    )
    print("...End")
```

2. and call it.
3. Expect "Feelin' Good in the '80s" playlist to be added to library. 
4. Actually, see this error:

```
File "/<redacted>/lib/python3.11/site-packages/ytmusicapi/ytmusic.py", line 241, in _send_request
    raise Exception(message + error)
Exception: Server returned HTTP 404: Not Found.
Requested entity was not found.
```

**Additional context**

This seems to happen for both playlists and albums. I haven't tried `INDIFFERENT` or `DISLIKE`. If I find some time, I might be able to dig deeper and submit and PR. Thanks for your attention!

**Comment by jonathanbell** [comment]
Possibly related: https://github.com/sigma67/ytmusicapi/issues/362

**Comment by sigma67** [comment]
You are using a `browseId`, not a `playlistId`.

https://ytmusicapi.readthedocs.io/en/stable/faq.html#what-is-a-browseid

**Comment by sigma67** [comment]
If you figure out how without extra requests, sure. AFAIK search only returns browseIds.

For albums, the playlistId starts with `OLA..`.
