### ISSUE TITLE
parsers/browsing.py:parse_album() gives incorrect value for "year"

### ISSUE THREAD

**Issue by ryanopily** [sigma67/ytmusicapi#588]
When using a YTMusic object authenticated with browser headers, a call to get_home() incorrectly fills the "year" key in an album with the artist name.

EXAMPLE:
```
ytmusic = YTMusic("headers.json")
print(json.dumps(ytmusic.get_home()))
```

RESULT:
```
[
  ...
  {
    "title": "Alexisonfire",
    "type": "Album",
    "year": "Alexisonfire",
    "artists": [
      {
        "id": "UC9gdUSsa_3TWMYou9nUIJPQ",
        "name": "Alexisonfire"
      }
    ],
    "browseId": "MPREb_TmfcXr7KaYu",
    "audioPlaylistId": null,
    "thumbnails": [
      {
        "url": "https://lh3.googleusercontent.com/TKcFRAFiGVfydrImrgdpZa_c_YqldAJFAU9OgxWrHublr7lV7tLpB-hDvmjKZuNngMgFDo675gSc2ePz-g=w226-h226-l90-rj",
        "width": 226,
        "height": 226
      },
      {
        "url": "https://lh3.googleusercontent.com/TKcFRAFiGVfydrImrgdpZa_c_YqldAJFAU9OgxWrHublr7lV7tLpB-hDvmjKZuNngMgFDo675gSc2ePz-g=w544-h544-l90-rj",
        "width": 544,
        "height": 544
      }
    ],
    "isExplicit": true
  },
  ...
]
```
As you can see above; **"year": "Alexisonfire"**. This happens with every album included in the result.
I couldn't find the actual field for album's year in the raw json returned from youtube. Maybe it's not included in the response.

**Comment by sigma67** [comment]
Cannot reproduce home page issues without response data

**Comment by ryanopily** [comment]
I included a partial result of the parsed response data returned by YTMusic.get_home() showcasing the issue. I just couldn't find the correct value ("2002") in the raw, unparsed JSON returned by the website. Not sure what else I should include.

**Comment by sigma67** [comment]
Yes, you included a partial result. I'm asking for the full response data returned from the server.

You can get it by navigating there in the browser and grabbing it from the network request

![image](https://github.com/sigma67/ytmusicapi/assets/16363825/6c5781a5-a0e0-472d-8ef8-0d4ce5bbc234)

A screenshot of your home page containing the problematic record would also be helpful

**Comment by ryanopily** [comment]
[music.youtube-home.json](https://github.com/sigma67/ytmusicapi/files/15443801/music.youtube-home.json)
![music youtube-home](https://github.com/sigma67/ytmusicapi/assets/35015177/82b90f9d-0266-4885-a008-da23ee7526d8)

**Comment by sigma67** [comment]
Thanks for the report and details!
