### ISSUE TITLE
get_artist only returns about 10 songs and 10 albums at max

### ISSUE THREAD

**Issue by Hai567** [sigma67/ytmusicapi#600]
**Describe the bug**
`get_artist` only returns about 10 songs and 10 albums at max

**To Reproduce**
`ytm.get_artist("UCssBfJCRXeODsKVUqym80fA")`

**Additional context**
I have no idea if this is a bug or a '''feature''', is there any option to get all the songs from an artist. Thank you!

**Comment by sigma67** [comment]
I think the documentation is pretty clear on this topic: https://ytmusicapi.readthedocs.io/en/stable/reference.html#ytmusicapi.YTMusic.get_artist
