### ISSUE TITLE
keyError when using get_playlist()

### ISSUE THREAD

**Issue by soreikomori** [sigma67/ytmusicapi#604]
**Describe the bug**
When attempting to run `yt.get_playlist()`, the program goes through all of the steps until it lands in line 97 of navigation.py, where it errors out:
```
root = root[k]
           ~^^^
KeyError: 'singleColumnBrowseResultsRenderer'
```
Just a moment ago, YTM seems to have pushed an update that makes playlists look different on browser. This random change might have caused some internal issue in the Google TV API that ytmusicapi fails to handle appropriately.

**To Reproduce**
1. Use `yt.get_playlist()`, for example by running `yt.get_playlist(id, None)` where id is the ID of a playlist (string).
2. Get the error.

**Additional context**
Here's how the entire error looks like for me.
```
Traceback (most recent call last):
  File "c:\Users\sorei\OneDrive\Miscellaneous\Applications\ReplayMix+\user_console.py", line 323, in <module>
    initialize()
  File "c:\Users\sorei\OneDrive\Miscellaneous\Applications\ReplayMix+\user_console.py", line 60, in initialize
    update()
  File "c:\Users\sorei\OneDrive\Miscellaneous\Applications\ReplayMix+\user_console.py", line 282, in update
    cE.loadAllPlaylists()
  File "c:\Users\sorei\OneDrive\Miscellaneous\Applications\ReplayMix+\compendium_engine.py", line 43, in loadAllPlaylists
    purgedPls = purgeFetchedPlaylist(yt.get_playlist(id, None)["tracks"]) # type: ignore
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sorei\.pyenv\pyenv-win\versions\3.11.0b4\Lib\site-packages\ytmusicapi\mixins\playlists.py", line 109, in get_playlist
    results = nav(response, SINGLE_COLUMN_TAB + SECTION_LIST_ITEM + ["musicPlaylistShelfRenderer"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sorei\.pyenv\pyenv-win\versions\3.11.0b4\Lib\site-packages\ytmusicapi\navigation.py", line 103, in nav
    raise err
  File "C:\Users\sorei\.pyenv\pyenv-win\versions\3.11.0b4\Lib\site-packages\ytmusicapi\navigation.py", line 97, in nav
    root = root[k]
           ~~~~^^^
KeyError: 'singleColumnBrowseResultsRenderer'
```

**Comment by sigma67** [comment]
Can you please provide screenshots of the playlist format and response data (copy JSON response from network requests tab, from request to the playlist endpoint)

**Comment by sigma67** [comment]
Please tell which version of ytmusicapi you are using in case it isn't latest

**Comment by scrimshander** [comment]
I was using 1.3.0 for the above. Didn't realize I was so far out of date. I just upgraded and am dealing with an issue that must be in my code but I will try to get it working and see what happens with the latest version.

**Comment by JohnHKoh** [comment]
Ran into the same issue using 0.25.2. Update to the latest version (1.7.3) and now receiving the following error:

```
Traceback (most recent call last):
  File "C:\Users\asdf\AppData\Local\Programs\Python\Python311\Lib\site-packages\ytmusicapi\helpers.py", line 64, in to_int
    int_value = locale.atoi(number_string)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asdf\AppData\Local\Programs\Python\Python311\Lib\locale.py", line 342, in atoi
    return int(delocalize(string))
           ^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''
```

**Comment by soreikomori** [comment]
I tried on 1.5.2 and 1.6.0 and got the same error on both. Upgrading to 1.7.3 seems to have fixed it fortunately. I'll leave the issue open for now though given what @JohnHKoh reported above.

**Comment by JohnHKoh** [comment]
https://github.com/sigma67/ytmusicapi/blob/11823d638719d76456ec58a6d7b76133368e5f1a/ytmusicapi/mixins/playlists.py#L214-L215

These seem to be the offending lines. I don't know what it looked like before, but `second_subtitle_runs[has_views + 0]["text"]` is "`트랙 100개`" `song_count[0]` now returns "트랙" (track) instead of "100개". This seems to be a localization issue, as when I change the language from Korean ("`ko`") to English ("`en`"), ``second_subtitle_runs[has_views + 0]["text"]`` is "`100 tracks`", and so `song_count[0]` now gets the correct value.

**Comment by sigma67** [comment]
I'm impressed that there are still people on 0.25. As it's fixed on latest I will close this thread.

**Comment by sigma67** [comment]
@JohnHKoh please create a separate issue as it is likely not directly related
