### ISSUE TITLE
signatureCipher when requesting for get_song method

### ISSUE THREAD

**Issue by ne-al** [sigma67/ytmusicapi#605]
So I'm working on a music app with Flutter for myself and decided to use this as my backend API. While doing so, I stuck at signaturecipher and didn't have the proper knowledge to decrypt it to get the actual song to play.

**Describe the solution you'd like**
I would like to get any method or any library which can decrypt my issue

**Describe alternatives you've considered**
I have tested something from website but it hasn't worked

**Additional context**
Please resolve my issue thankyou
Im using the latest version, 1.7.3

**Comment by sigma67** [comment]
See i.e. https://github.com/KoljaWindeler/ytube_music_player

**Comment by ne-al** [comment]
hey @sigma67 its been 2days since you had replied me and since then, I've been looking in this repository and didn't understand how I could decode the signaturecipher ?? I'm new to python and only using it on my backend using FastApi. I'm a flutter developer so it would be  helpful if you could tell me how to decode it. It would mean a lot for me and save me a lot of time and effort Thank you for your help and contributions to the community

**Comment by sigma67** [comment]
Hey man, I'm not being paid to support your private or for profit project nor do I have any intent to do so. 

Kindly figure it out yourself. This software is provide for free without warranty or support

**Comment by ne-al** [comment]
Anyway, thankyou for the response
