### ISSUE TITLE
get_playlist doen't return info about playlist author

### ISSUE THREAD

**Issue by kutermak** [sigma67/ytmusicapi#611]
**Describe the bug**

In previous versions of the library **'get_playlist'** method returned playlist author info as well. Looked like:

                "author": [
                    {
                        "name": "redditEDM",
                        "id": "UCaTrZ9tPiIGHrkCe5bxOGwA"
                    }
                    
But in newest version I can't get it by this method. There are just nothing about author 

Am I doing something wrong?

**To Reproduce**

1. call get_playlist for any existing playlist
2. try to get author info author_name = result['author']
3. See error

**Comment by sigma67** [comment]
Please include the error message
