### ISSUE TITLE
KeyError: 'thumbnails' when using `get_playlist`

### ISSUE THREAD

**Issue by abhishekmj303** [sigma67/ytmusicapi#625]
**Describe the bug**
`thumbnails` for the playlist is not retrieved when using `get_playlist`. 

**To Reproduce**
1. Create a `YTMusic()` object
2. Call `playlist = get_playlist(playlist_id, limit=None)`
3. Access `playlist['thumbnails']`
4. KeyError: 'thumbnails'

**Comment by sigma67** [comment]
Please provide the playlist id

**Comment by abhishekmj303** [comment]
This is the playlist_id:
```
RDCLAK5uy_n17q7_2dwfDqWckpccDyTTkZ-g03jXuII
```

This is the response: https://pastebin.com/n1CtXTX7
