### ISSUE TITLE
"KeyError: navigationEndpoint" with get_album() using certain browseIDs

### ISSUE THREAD

**Issue by ClintGreen5150** [sigma67/ytmusicapi#629]
Good day :) 

I keep getting a "KeyError: navigationEndpoint" when using get_album() with some browseIDs.

Steps to reproduce the behavior (I am using Python):

some browseIDs that raise the error:

# browse_id = 'MPREb_6Su0FBvTUoc'
# browse_id = 'MPREb_3QkMjuZjA2M'
# browse_id = 'MPREb_961nHuiyMGu'

#        #working browseID:
# browse_id = 'MPREb_C2GToaFlHuJ'

**Comment by sigma67** [comment]
What version of ytmusicapi are you using - probably not latest
