### ISSUE TITLE
playlist_replace_items method

### ISSUE THREAD

**Issue by Loukious** [sigma67/ytmusicapi#639]
**Is your feature request related to a problem? Please describe.**
When trying to keep a playlist synced, it's too much work to always fetch the playlist items then remove outdated tracks and add new ones (to save bandwidth and avoid being rate limited). Emptying the entire playlist and refilling isn't that efficient.

**Describe the solution you'd like**
I want a method that is similar to spotipy's playlist_replace_items. More details [here](https://spotipy.readthedocs.io/en/latest/#spotipy.client.Spotify.playlist_replace_items)

**Comment by sigma67** [comment]
We're limited by what the YouTube Music API provides. Unless there is an endpoint that does what you want, I doubt this is possible
