### ISSUE TITLE
v1.8.0 makes no songs to be found

### ISSUE THREAD

**Issue by robtekky** [sigma67/ytmusicapi#640]
**Describe the bug**
After upgrading from v1.7.5 to v1.8.0, no songs are now found using the YTMusicAPI client.

**To Reproduce**
1. Upgrade to v1.8.0 of YTMusicAPI.
2. Use browser authentication
3. Get client instance
4. Use `get_library_upload_songs` method
5. No songs are returned, although I have more than one thousand songs uploaded.

**Additional context**
If I use v1.7.5 or earlier, I have no problems at all.

**Comment by sigma67** [comment]
You probably don't have a Downloads button here?

![image](https://github.com/user-attachments/assets/1c5c712b-d2db-4b54-b93b-ba46b2fefa48)

What's your region?

**Comment by robtekky** [comment]
> You probably don't have a Downloads button here?

No, I do not.


> What's your region?

Spain

**Comment by apastel** [comment]
I'm assuming the Downloads feature is only available to Premium users. So this means users on the free tier cannot retrieve uploads, currently. Not complaining, I'm just stating it for clarity & posterity.

**Comment by sigma67** [comment]
I acknowledged the bug, just haven't got around to fixing it. Fix should be simple enough

**Comment by sigma67** [comment]
@robtekky @apastel could either of you please test with the linked PR

**Comment by apastel** [comment]
It's working for me :+1: . Was able to find uploads for both my premium account and my free account.
