### ISSUE TITLE
Upload crashes on the large file: KeyError: 'x-goog-upload-url'

### ISSUE THREAD

**Issue by ptabor** [sigma67/ytmusicapi#647]
When trying to upload large file (>300MB audiobook):

The library is crashing with: 
```
# Traceback (most recent call last):
# File "/yt-music/upload.py", line 40, in run
# result = ytmusic.upload_song(file)
# ^^^^^^^^^^^^^^^^^^^^^^^^^
# File "/home/nonroot/.local/lib/python3.12/site-packages/ytmusicapi/mixins/uploads.py", line 237, in upload_song
# upload_url = response.headers["X-Goog-Upload-URL"]
# ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
# File "/home/nonroot/.local/lib/python3.12/site-packages/requests/structures.py", line 52, in __getitem__
# return self._store[key.lower()][1]
# ~~~~~~~~~~~^^^^^^^^^^^^^
# KeyError: 'x-goog-upload-url'
#
# During handling of the above exception, another exception occurred:
```

Expected output: The upload function should return a failed result.

**Comment by sigma67** [comment]
Hi @ptabor , thanks for the report. Unfortunately the traceback is truncated so it's hard to find out what's going wrong. 

However I suspect that you have hit the upload size limit, which seems to be around 300MB

https://www.reddit.com/r/YoutubeMusic/comments/gizdjz/upload_size_limit/

We could implement a check that prevents uploads larger than 300 MB.
