### ISSUE TITLE
`parse_duration` fails for very long videos

### ISSUE THREAD

**Issue by abhishekmj303** [sigma67/ytmusicapi#660]
**Describe the bug**
`get_playlist` fails when the playlist contains very long videos like [this](https://www.youtube.com/watch?v=hHW1oY26kxQ&list=PLfuGZPdCf-K_65ebc5u1yc5WonSf5HOXk&index=264&pp=iAQB8AUB). These are basically streams converted to videos.

The above mentioned duration is: `13,165:23:44`

**To Reproduce**
1. Call `get_playlist("PLfuGZPdCf-K_65ebc5u1yc5WonSf5HOXk")`
2. Get error:
```
/lib/python3.11/site-packages/ytmusicapi/parsers/_utils.py", line 71, in <genexpr>
    seconds = sum(multiplier * int(time) for multiplier, time in mapped_increments)
                               ^^^^^^^^^
ValueError: invalid literal for int() with base 10: '13,165'
```

**Comment by sigma67** [comment]
Wow... that's certainly an edge case I didn't expect
