### ISSUE TITLE
Library search songs have missing properties

### ISSUE THREAD

**Issue by MarkhorDev** [sigma67/ytmusicapi#669]
**Describe the bug**
When using search with a library scope, `duration` and `year` are always None, and `duration_seconds` is not present. The documentation does not mention this anywhere, so I am assuming it is a bug. However, the information is also not visible on ytm when searching the library, so I am not sure if it is even possible for this information to be given. If the latter, I think this should be added to the docs. 

**To Reproduce**
1. Search with `scope` as `library` and `filter` as `songs`
2. Check first result for `duration` or `year` properties

**Additional Information**
ytmusicapi version: 1.8.2
Request response: `{'category': None, 'resultType': 'song', 'title': 'Thinking About You', 'album': {'name': 'Pablo Honey', 'id': 'MPREb_DciERiuADkS'}, 'videoId': '2jsPEOiMNaA', 'videoType': 'MUSIC_VIDEO_TYPE_ATV', 'duration': None, 'year': None, 'artists': [{'name': 'Radiohead', 'id': 'UCr_iyUANcn9OX_yy9piYoLw'}], 'isExplicit': True, 'thumbnails': [{'url': 'https://lh3.googleusercontent.com/U7k2oSmy45dhhj8ACdsUr1hQAvoY1IcOlHI_ZwU2rckJte1UEcTyrBUPUGr6Q-HT9-zeY0BwJ05xlOOJ=w60-h60-l90-rj', 'width': 60, 'height': 60}, {'url': 'https://lh3.googleusercontent.com/U7k2oSmy45dhhj8ACdsUr1hQAvoY1IcOlHI_ZwU2rckJte1UEcTyrBUPUGr6Q-HT9-zeY0BwJ05xlOOJ=w120-h120-l90-rj', 'width': 120, 'height': 120}]}`

**Comment by sigma67** [comment]
The info is simply missing, not much else to say. Try searching on the web in your library, there is no such info on the titles.

![image](https://github.com/user-attachments/assets/54a272d7-8b4e-47e0-927e-fa3d047ff5c3)
