### ISSUE TITLE
Error calling get_watch_playlist

### ISSUE THREAD

**Issue by murraypaul** [sigma67/ytmusicapi#67]
When making call: yt.get_watch_playlist()
Error is:
Traceback (most recent call last):
  File "ytm-tool.py", line 175, in <module>
    main()
  File "ytm-tool.py", line 170, in main
    do_list(yt,args)
  File "ytm-tool.py", line 44, in do_list
    do_list_queue(yt,args)
  File "ytm-tool.py", line 108, in do_list_queue
    history = yt.get_watch_playlist()
  File "/home/pi/.local/lib/python3.7/site-packages/ytmusicapi/mixins/watch.py", line 59, in get_watch_playlist
    results = response['contents']['singleColumnMusicWatchNextResultsRenderer']['playlist'][
KeyError: 'contents'

Dumping the response output gives:
{'responseContext': {'serviceTrackingParams': [{'params': [{'key': 'c',
                                                            'value': 'WEB_REMIX'},
                                                           {'key': 'cver',
                                                            'value': '0.1'},
                                                           {'key': 'yt_li',
                                                            'value': '1'},
                                                           {'key': 'GetMusicWatchNext_rid',
                                                            'value': '0xac85e24a918052a1'}],
                                                'service': 'CSI'},
                                               {'params': [{'key': 'logged_in',
                                                            'value': '1'},
                                                           {'key': 'e',
                                                            'value': '23925759,23931789,23918597,23927190,23940210,23901082,23939002,23934594,9473386,23874981,23899758,23897263,23898478,23927096,23911226,23934047,23925550,23709532,23904038,23857970,9473407,23862025,23927089,23896666,23790586,23861666,23882884,23905281,23910680,23932754,23914966,23921357,23884386,23932567,23937103,23897257,23841635,23908862,23789385,23857949,23937161,23755966,23794339,23932955,23935723,23937384,23884998,23907445,23935184,23898321,23865206,23839597,23927102,23939162,23935178,23934344,23918474,23745613,23921982,23940773,1714252,23936487,23921644,23935545,23837886,23896704,23902702,23910764,23923643,23934322,23797973,23899760,23900854,23934624,39320819,23834232,23864523,23904600,23931540,23919306,23801987,23897295,23862294,23915985,23934014,23884593,23854276,23880323,23919047,23897503,23919917,23899696,23921377,23804281,23832002,24650112,23860381,23934970,23744176,23933618,23928204,23899762,23927208,23894009,23923390,23911301,23928679,23862065,23915932,23836115,23874337,23866675,23936409,23862582,23932706,23932792,23919025,23919895,23938891,23932188,23858564,23933563,23871729,23937610,23862346,23901962,23892622,23918657,23895139,23897872,23935296,23874051,23928508,23853114,23937416,23882125,23935842,23938768,23842638,23886777,23907384,23902008,23856479,23938461,23842233,23872595,23754764,23932183,23925265,23859025,23899764,23936023,9473369,24590231,23934570,23930220,23936677,23911055,23923862,23882685,23868136,23900376,23874940,23900829,23933139,23939497,23939014,23884697,23885639,23811985,23841299,23816681,23910775,23890891,23932752,23865230,23854352,23925932,23927284,23935261,23921992,23938619,23916053,23915032,23929653,23891344,23907436'}],
                                                'service': 'GFEEDBACK'},
                                               {'params': [{'key': 'client.version',
                                                            'value': '0.1'},
                                                           {'key': 'client.name',
                                                            'value': 'WEB_REMIX'}],
                                                'service': 'ECATCHER'}],
                     'visitorData': <hex string>},
 'trackingParams': <hex string>}

**Comment by sigma67** [comment]
Did you pass any parameters to get_watch_playlist?

**Comment by murraypaul** [comment]
No, no parameters, just calling
history = yt.get_watch_playlist()

**Comment by sigma67** [comment]
That would be your issue then. You need to provide a videoId
