### ISSUE TITLE
get_podcast method doesn't provide thumbnails.

### ISSUE THREAD

**Issue by Utkarsh-vishnoi** [sigma67/ytmusicapi#670]
**Is your feature request related to a problem? Please describe.**
Yes, the data returned by `get_podcast` doesn't have thumbnails data. 

**Describe the solution you'd like**
I would try to implement it myself as a pull-request but the documentation is lacking the instructions for development setup.
I installed PDM and installed the dependencies for the project but that's it. How do I debug and all? If you could guide me, or provide basic setup instructions for the dev environment. I am currently using VS Code for as the preferred IDE for python. On the other hand if you would implement this that would be awesome.

**Describe alternatives you've considered**
Tried googling and using other unofficial API's that can provide thumbnails details for podcasts but no luck!!!

**Additional context**
Not Applicable....

**Comment by sigma67** [comment]
Do you mean the podcast itself? The episodes have thumbnails.

Instructions are here for contributing: https://github.com/sigma67/ytmusicapi/blob/main/CONTRIBUTING.rst

**Comment by Utkarsh-vishnoi** [comment]
Yes, the podcast itself......

**Comment by sigma67** [comment]
Well that one was an easy fix. I guess I just forgot because I didn't think people would actually use the podcasts..
