### ISSUE TITLE
Getting 401 error while creating playlist

### ISSUE THREAD

**Issue by FaizAlam** [sigma67/ytmusicapi#680]
I am exploring ytmusicapi and facing issue while creating playlist. I am using browser authentication and I have stored the json in a file named `browser.json`. The format of the content is same as provided in the manual file creation documentation. But when I try to search for songs using the same object, it works perfectly fine. So I don't think its an issue related to Cookie. 

**Describe the bug**
Getting `ytmusicapi.exceptions.YTMusicServerError: Server returned HTTP 401: Unauthorized.` while creating playlist.
Code:
![Screenshot 2024-11-17 125619](https://github.com/user-attachments/assets/06787481-1cd5-4c85-9695-60bb62357f82)

browser.json:
`{
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0",
    "Accept": "*/*",
    "Accept-Language": "en-US,en;q=0.5",
    "Content-Type": "application/json",
    "X-Goog-AuthUser": "0",
    "x-origin": "https://music.youtube.com",
    "Cookie" : "<COOKIE GOES HERE>"
}`

Respose:
![Screenshot 2024-11-17 125750](https://github.com/user-attachments/assets/58fb5a5f-629f-4d40-bcc2-6ae121a5d89a)

**To Reproduce**
Try the code provided in the above screenshot

Please let me know how can i resolve this, I am working on my personal project and would love any kind of help. Thanks a lot

**Comment by sigma67** [comment]
Please re-authenticate. Your credentials are not/no longer working
