### ISSUE TITLE
get_history() failing with menuServiceItemRenderer key error

### ISSUE THREAD

**Issue by scrimshander** [sigma67/ytmusicapi#687]
Suddenly getting this get_history() key error - anybody else seeing this?

`KeyError: "Unable to find 'menuServiceItemRenderer' using path ['menu', 'menuRenderer', 'items', -1, 'menuServiceItemRenderer', 'serviceEndpoint', 'feedbackEndpoint', 'feedbackToken'] on {'toggleMenuServiceItemRenderer': {'defaultText': {'runs': [{'text': 'Pin to Listen again'}]}, 'defaultIcon': {'iconType': 'KEEP'}, 'defaultServiceEndpoint': {'clickTrackingParams': 'CMkdEP7eChgLIhMI9cbppJGjigMVhsQ_BB3MQj3U', 'feedbackEndpoint': {'feedbackToken': 'AB9zfpKhbnIq66OMlFo0ZSzIx_9FEQUf-wVpv_2xls_U4siSA5yK6LR4siuHeV0aPMYH28LCLuV3X8aX0Uu2qk4ifHVw1MRrMM1rRW34hXh6vHxe2kAAgwc'}}, 'toggledText': {'runs': [{'text': 'Unpin from Listen again'}]}, 'toggledIcon': {'iconType': 'KEEP_OFF'}, 'toggledServiceEndpoint': {'clickTrackingParams': 'CMkdEP7eChgLIhMI9cbppJGjigMVhsQ_BB3MQj3U', 'feedbackEndpoint': {'feedbackToken': 'AB9zfpKzUkY64IETMpyHBdV5Dp8eOFuebK8czAFRVyTO_PLHBYnoH0nfaQ8qZl5kUwN9z338S_drNzCw-HkeWiEutsp0497cVz9_RfaVo37gIY5EIlgaKb4'}}, 'trackingParams': 'CMkdEP7eChgLIhMI9cbppJGjigMVhsQ_BB3MQj3U'}}, exception: 'menuServiceItemRenderer'"`

upon calling get_history(), logged in via headers json. No problems until this morning (Dec 12).

Here's the full trace:

```
~/Documents/PythonEnvironments/ytmusic/lib/python3.8/site-packages/ytmusicapi/mixins/library.py in get_history(self)
    300                 raise Exception(error)
    301             menu_entries = [[-1, *MENU_SERVICE, *FEEDBACK_TOKEN]]
--> 302             songlist = parse_playlist_items(data, menu_entries)
    303             for song in songlist:
    304                 song["played"] = nav(content["musicShelfRenderer"], TITLE_TEXT)

~/Documents/PythonEnvironments/ytmusic/lib/python3.8/site-packages/ytmusicapi/parsers/playlists.py in parse_playlist_items(results, menu_entries, is_album)
     52             continue
     53         data = result[MRLIR]
---> 54         song = parse_playlist_item(data, menu_entries, is_album)
     55         if song:
     56             songs.append(song)

~/Documents/PythonEnvironments/ytmusic/lib/python3.8/site-packages/ytmusicapi/parsers/playlists.py in parse_playlist_item(data, menu_entries, is_album)
    150     if menu_entries:
    151         for menu_entry in menu_entries:
--> 152             song[menu_entry[-1]] = nav(data, MENU_ITEMS + menu_entry)
    153 
    154     return song

~/Documents/PythonEnvironments/ytmusic/lib/python3.8/site-packages/ytmusicapi/navigation.py in nav(root, items, none_if_absent)
    108         if none_if_absent:
    109             return None
--> 110         raise type(e)(f"Unable to find '{k}' using path {items!r} on {root!r}, exception: {e}")
    111     return root
    112
```

**Comment by sigma67** [comment]
You're not the only one: https://github.com/sigma67/ytmusicapi/discussions/686

PR welcome
