### ISSUE TITLE
No play/view counts in get_playlist_info

### ISSUE THREAD

**Issue by asegret** [sigma67/ytmusicapi#701]
All the views are null when calling get_playlist_info()

The views are available when clicking "show all" on the artist channel page (it's displayed when the artist has more than 5 songs (I guess it is 5 because it only shows 5 on the channel page))

https://music.youtube.com/channel/UCZn4r7heNOPY-C43YIywnVA

All the songs of the channel are listed in a playlist, and the views/plays are displayed 

https://music.youtube.com/playlist?list=OLAK5uy_nI8GFXPiq15Yp6hiTSgp2Y5-4J5fD3W44

I think it changed with this commit : 

ytmusicapi/parsers/playlists.py 
def parse_playlist_item
line 171

https://github.com/sigma67/ytmusicapi/commit/d2cbe538dedbb73a8a34820ef2c5fe13a453076a#diff-3df5031030978f7252957f4155230cbbd431d129df20b745e12cd54723bd1c94L108

minus :
views = get_item_text(data, 2) if flex_column_count == 4 or is_album else None

plus :
views = get_item_text(data, 2) if is_album else None

I added this locally and it worked for my use case :

    views = get_item_text(data, 2) if len(data["flexColumns"]) == 4 or is_album else None
    if views is not None:
        views = views.split(" ")[0]

**To Reproduce**

    ytmusic = YTMusic()

    playlist = ytmusic.get_playlist("OLAK5uy_nI8GFXPiq15Yp6hiTSgp2Y5-4J5fD3W44")

    for index, track in enumerate(playlist.get('tracks', []), start=1):
        views = track.get('views', '')
        print(f"Views: {views}")

**Additional context**

I'm only using ytmusicapi to get stream numbers, I don't know the impact of that

I don't know if it use to work or not, I don't know anything about python and I'm using an LLM to help code some simple things in python, I'm absolutely not qualified to seriously code something in this language and do pull requests (I do java)

**Comment by sigma67** [comment]
Please try to follow the bug report template or I'm forced to close this one because I only understand about half of what you're trying to tell

**Comment by ImpenetrableNoble** [comment]
@sigma67 I think I understand what they're saying, so to explain, they’ve been using the `ytmusicapi` library and noticed something weird. When they call `get_playlist_info()`, the `views` field for tracks in the playlist is always `null`, even though they can see the views just fine when checking the playlist manually on YouTube Music (like [this one](https://music.youtube.com/playlist?list=OLAK5uy_nI8GFXPiq15Yp6hiTSgp2Y5-4J5fD3W44).

They think this might’ve started happening after a specific commit in the library’s codebase, where the logic for parsing the `views` field was changed. Originally, it was `views = get_item_text(data, 2) if flex_column_count == 4 or is_album else None`, but now it’s `views = get_item_text(data, 2) if is_album else None`. 

They ended up tweaking the code locally to use `views = get_item_text(data, 2) if len(data["flexColumns"]) == 4 or is_album else None` and added a little cleanup for the views string, and that fixed it for them. But they’re not sure if this is a new issue or if it ever worked correctly in the first place. They’re not super familiar with Python or contributing to open-source projects—they mostly work with Java and rely on an LLM to help with Python scripting. 

Anyway, they just wanted to flag this in case it’s helpful. They’re not really in a position to submit a pull request themselves, but they’re hoping someone can look into it and get the `views` field working properly in `get_playlist_info()`.

**Comment by sigma67** [comment]
You are using `get_playlist` for an album. Use `get_album_browse_id` and `get_album` instead.

There is also a PR here that could make it work for you: https://github.com/sigma67/ytmusicapi/pull/696
