### ISSUE TITLE
OAuth Web client does not work

### ISSUE THREAD

**Issue by pranavbhandari24** [sigma67/ytmusicapi#708]
**Issue**
When using the client ID and client secret for Oauth, if the client ID is a webclient `ytmusicapi oauth` fails with
```
ytmusicapi.auth.oauth.exceptions.BadOAuthClient: OAuth client failure. Most likely client_id and client_secret mismatch or YouTubeData API is not enabled.
```

I also tried to create `oauth.json` manually (by generating the access token but I get 401 Unauthorized error
```
Traceback (most recent call last):
  File "/Users/pranavbhandari/PycharmProjects/MoveMusic/youtube_music.py", line 117, in <module>
    result = ytmusic.get_library_songs(limit=library_limit)
  File "/Users/pranavbhandari/PycharmProjects/MoveMusic/.venv/lib/python3.9/site-packages/ytmusicapi/mixins/library.py", line 81, in get_library_songs
    response = parse_func(request_func(None))
  File "/Users/pranavbhandari/PycharmProjects/MoveMusic/.venv/lib/python3.9/site-packages/ytmusicapi/mixins/library.py", line 69, in <lambda>
    request_func = lambda additionalParams: self._send_request(endpoint, body)
  File "/Users/pranavbhandari/PycharmProjects/MoveMusic/.venv/lib/python3.9/site-packages/ytmusicapi/ytmusic.py", line 278, in _send_request
    raise YTMusicServerError(message + error)
ytmusicapi.exceptions.YTMusicServerError: Server returned HTTP 401: Unauthorized.
You must be signed in to perform this operation.
```

**To Reproduce**
Create a Web OAuth client and use that in `ytmusicapi oauth`

**Note**: If the client is a TV client, everything works as expected. I need a web client to specify callback urls

**Comment by pranavbhandari24** [comment]
Oh, this was my mistake. I was not adding the "expires_at" and "expires_in" to the manually created oauth.json. Once I added those the requests worked as expected. 

`ytmusicapi oauth` still fails when using web oauth client though.

**Comment by sigma67** [comment]
> ytmusicapi oauth still fails when using web oauth client though.

Could you elaborate?

**Comment by pranavbhandari24** [comment]
> > ytmusicapi oauth still fails when using web oauth client though.
> 
> Could you elaborate?

`ytmusicapi oauth` command fails when I provide  Web OAuth client, but works as expected when I provide a TV Oauth client

**Comment by sigma67** [comment]
@pranavbhandari24 that is expected, hence the advice in the documentation to create TV credentials

https://ytmusicapi.readthedocs.io/en/stable/setup/oauth.html
