### ISSUE TITLE
"get_song(self, videoId: str) -> Dict: " returns empty dict

### ISSUE THREAD

**Issue by maigag** [sigma67/ytmusicapi#77]
Hi,

Since Latest commit "get_song(self, videoId: str) -> Dict:" in browsing.py returns only empty dictionary to me.

Maybe it is me not doing something correctly - but i wanted to be sure to highlight this.
Best,
Guido

ytmusicapi version v0.9.2

**Comment by sigma67** [comment]
Works fine for me. What videoId are you using?

**Comment by maigag** [comment]
Hi,

thanks for the quick answer.
Even smth simple like this 

from ytmusicapi import YTMusic
ytmusic = YTMusic()
video = ytmusic.get_song('N2DglZjKvBU')
print(video)

returns me {}.

Is this not the case for you?
It was not the case a couple of days ago.

Best,
Guido

**Comment by sigma67** [comment]
No, it should work fine. Both on 0.9.2 and latest master.

Running the above code prints the video Dict as it should. What's your OS/Python version?

**Comment by maigag** [comment]
Thanks for the answer.
I am running this on python 3.6 - from VSCode. Windows 10.
Best,
Guido

**Comment by sigma67** [comment]
It must be related to your setup. I also tried with Python 3.6.9 and it works fine. Did you install using pip3? Or are you using the source code?
