### ISSUE TITLE
Is it possible to download a song?

### ISSUE THREAD

**Issue by lukas4haus** [sigma67/ytmusicapi#78]
Hi,
I am migrating from gmusicapi.
I am missing one essential feature that initially made me subscribe to Google Play Music instead of Spotify, which is the ability to download songs/albums using the api.

I have no idea if this was ever intended to be public, but I have been using this api for the last years to in a simple to use streaming client used by my children.

Did I miss this function in the documentation?
If not, is there any chance for it to be added in the near future?

Best regards,
Lukas

**Comment by sigma67** [comment]
Yes, you can download any video/song using its videoId and [youtube-dl](https://github.com/ytdl-org/youtube-dl). 

`get_song` also provides the streaming URLs provided by the YouTube API.

**Comment by lukas4haus** [comment]
I am sorry to bother you again, but I do not get it.

get_song does only provide me with an url for the thumbnails.

As far as I understand, the signatureCipher of one of the streams has to be somehow converted to retrieve the download url. 
Is it therefore necessary that the converting library also has valid credentials for youtube? 

youtube-dl has issues accepting my login and also reports that it is unable to extract the video data. 

Could you provide a short example of how to download a song with / without youtube-dl?

Best regards,
Lukas
