### ISSUE TITLE
get_uploaded_songs() fails

### ISSUE THREAD

**Issue by beville** [sigma67/ytmusicapi#8]
Thanks for this amazing API!  I've been uploading my personal music library using the upload_song function, and it's way more convenient than the web UI.

But I've noticed that if I try to run get_uploaded_songs(), I get an error:

```
Traceback (most recent call last):
  File "./ytmusic.py", line 46, in <module>
    main()
  File "./ytmusic.py", line 39, in main
    songs = ytmusic.get_uploaded_songs(1)  
  File "/usr/local/lib/python3.7/dist-packages/ytmusicapi/ytmusic.py", line 607, in get_uploaded_songs
    results = nav(response, SINGLE_COLUMN_TAB + SECTION_LIST + [1] + ITEM_SECTION)['musicShelfRenderer']
  File "/usr/local/lib/python3.7/dist-packages/ytmusicapi/helpers.py", line 19, in nav
    for k in items: root = root[k]
IndexError: list index out of range
```

Maybe something on the server side changed since you implemented this?

**Comment by sigma67** [comment]
I'm having no issues with my account, so it should still work provided you have uploaded songs. Could you attempt to debug this and post the API response (l. 610 of ytmusic.py) here?

**Comment by beville** [comment]
I've got probably 1000 songs up so far, and the first one alphabetically has the title "(Am I Just) Fooling Myself"

OK, after these lines:
```
    endpoint = 'browse'
    body = {"browseId": "FEmusic_library_privately_owned_tracks"}
    response = self.__send_request(endpoint, body)
```
I added this:
```
    print(json.dumps(response,indent=2))
```
My call is:
```
    songs = ytmusic.get_uploaded_songs(limit=1)
```

Output was rather voluminous:
[response.txt](https://github.com/sigma67/ytmusicapi/files/4499804/response.txt)

**Comment by sigma67** [comment]
Thanks, that it was quite helpful. It seems that for you the Carousel up top with the "Last played" entries is not being returned with the request. This can be fixed by looking for the 'itemSectionRenderer' entry instead of a fixed index.

Before I push a fix, could you please check if the same issue appears with `get_playlists`? It currently uses the same JSON path with a fixed index.

**Comment by beville** [comment]
Looks like I do, in fact, get the same error with `get_playlists`:

```
Traceback (most recent call last):
  File "./ytmusic.py", line 34, in <module>
    main()
  File "./ytmusic.py", line 26, in main
    playlists = ytmusic.get_playlists()  
  File "/usr/local/lib/python3.7/dist-packages/ytmusicapi/ytmusic.py", line 363, in get_playlists
    results = nav(response, SINGLE_COLUMN_TAB + SECTION_LIST + [1] + ITEM_SECTION)['gridRenderer']['items']
  File "/usr/local/lib/python3.7/dist-packages/ytmusicapi/helpers.py", line 19, in nav
    for k in items: root = root[k]
IndexError: list index out of range
```

**Comment by sigma67** [comment]
Hey, I've attempted to fix this in 826a72c.  Please try the latest version with `pip install git+https://github.com/sigma67/ytmusicapi` and reopen if you still have issues.

**Comment by beville** [comment]
So, the call to get_playlists now works for me, but when I call get_uploaded_songs, there is now a different error:

```
Traceback (most recent call last):
  File "./ytmusic.py", line 36, in <module>
    main()
  File "./ytmusic.py", line 30, in main
    songs = ytmusic.get_uploaded_songs(limit=1)  
  File "/usr/local/lib/python3.7/dist-packages/ytmusicapi/ytmusic.py", line 622, in get_uploaded_songs
    songs.extend(parse_uploaded_items(results['contents'][1:]))
  File "/usr/local/lib/python3.7/dist-packages/ytmusicapi/parsers.py", line 68, in parse_uploaded_items
    entityId = nav(data, MENU_ITEMS)[-1]['menuNavigationItemRenderer']['navigationEndpoint'][
  File "/usr/local/lib/python3.7/dist-packages/ytmusicapi/parsers.py", line 139, in nav
    for k in items: root = root[k]
KeyError: 'menu'
```

**Comment by sigma67** [comment]
Hey, I think this happened because you had a song processing while you requested your tracks. I'll push a fix shortly.

**Comment by beville** [comment]
OK, I did `sudo pip3 install git+https://github.com/sigma67/ytmusicapi -U`, and have the latest from github.

The function now succeeds!  But oddly, I'm getting 25 results, even though the limit is set to 1.  Not really an issue for me, since I was only setting that for test purposes. 

[I'll probably post a question in the future as I pursue my goal of generating playlists of shuffled-by-album (picking a list of random albums, and playing each album in order).  I implemented this with the gmusicapi, and am looking ahead in case it all gets deprecated.]

**Comment by sigma67** [comment]
Good point. YoutubeMusic only returns data in 25 increments. Since the API is fetching the data anyway, I thought it may be useful to just return it. It would be trivial though to cut the results to the limit (by subsetting the result list).

Great that you're working with the library, it definitely needs testing from other users. Just to let you know, I'm currently working on the rest of the library functionality. This includes getting library artists and albums, in case you need that for your app.
