### ISSUE TITLE
Is it possible to get most played songs from YTMusic account?

### ISSUE THREAD

**Issue by fijar-lazuardy** [sigma67/ytmusicapi#81]
I wanted to make a simple analysis on my TYMusic account, simply i want to find the most played songs. I got an idea to count for songs I've played from my history, but from get_history(), all songs are appear only once so I can't count how many times songs played from my history, any alternative?

**Comment by sigma67** [comment]
No, it's not possible. The history page tracks your played songs, but each song there is unique. Meaning if you play it again, it only shows up once in the list. You can track it yourself using last.FM for example, or by monitoring the history page continuously like @akraus53 seems to be doing.
