### ISSUE TITLE
Is there anyway i can make the search feature more quick?

### ISSUE THREAD

**Issue by default-303** [sigma67/ytmusicapi#82]
Hey, I'm using your module to get artist name and track name from youtube titles. So far its really good, works perfectly.But the problem is it just takes up a lot of time(around 1 sec for each title). So, if i have a playlist of 200 songs itll take around 200 seconds. So is there any way this can be done faster ?? I'm looking at multi threading as an option. Is there any other option?

Thanks

**Comment by sigma67** [comment]
The API is not that fast unfortunately. You can try parallelizing, but I don't think you should overdo it (might get flagged as abuse).

**Comment by default-303** [comment]
thanks for reply, so you rely on the official api to get details on track names and artists??

**Comment by sigma67** [comment]
No, in my project https://github.com/sigma67/spotifyplaylist_to_gmusic I use ytmusicapi, precisely because 100 searches is not enough to transfer playlists. I developed ytmusicapi for this reason in the first place. It does take a few minutes to transfer playlists with a few hundred items

**Comment by default-303** [comment]
nice, may i know how exactly you are getting details like artist and track name??

**Comment by sigma67** [comment]
See here: https://github.com/sigma67/spotifyplaylist_to_gmusic/blob/6bd5e6ec73ac2950b590dce4f706c1c2d61a7efb/YouTube.py#L64-L76

**Comment by default-303** [comment]
thanks for specifying. I like this repo a lot tbh. I plan on contributing asap(i'm still a beginner btw).

**Comment by sigma67** [comment]
Sure, make sure to check out [CONTRIBUTING.rst](https://github.com/sigma67/ytmusicapi/blob/master/CONTRIBUTING.rst)
