### ISSUE TITLE
Getting entityId after using upload_son (request not an issue)

### ISSUE THREAD

**Issue by IrishDMR** [sigma67/ytmusicapi#86]
I know the standard response from a request is simply the http code/text, and Im aware you can use the song title to look up the entityId afterwards, Is it possible to predict/determine the entityId without having to query the title which you may or not know after uploading.

**Comment by sigma67** [comment]
Since uploads are processed asynchronously, the only way to get the entityId is to retrieve your uploads using the library functions or the uploads search. As far as I'm aware, at least.

**Comment by IrishDMR** [comment]
That's what I figured, the workaround is a modification of my current use, which you mentioned, and that is to search afterwards.

For my usecase I will probably add ability to read the meta tags and search for that, or the filename itself if those are blank.

Thanks for all your work 👍
