### ISSUE TITLE
continuationContents error

### ISSUE THREAD

**Issue by vzaliva** [sigma67/ytmusicapi#87]
My [script](https://github.com/vzaliva/scripts_and_configs/blob/master/scripts/rmsongs.py) using API stopped working:

```
Traceback (most recent call last):
  File "./rmsongs.py", line 32, in <module>
    artists = yt.get_library_upload_artists(limit=1000)
  File "/home/lord/tmp/ytmusicapi/ytmusicapi/mixins/uploads.py", line 111, in get_library_upload_artists
    request_func, parse_func))
  File "/home/lord/tmp/ytmusicapi/ytmusicapi/parsers/utils.py", line 55, in get_continuations
    results = response['continuationContents'][continuation_type]
KeyError: 'continuationContents'
```

It was working 10 mins ago and now just stopped.

**Comment by vzaliva** [comment]
I will be glad to provide additional debug info. just tell me what you need. Thanks!

**Comment by sigma67** [comment]
I assume this was just a temporary error? Sometimes the YouTube API will not provide continuation_contents, presumably due to a backend error.

**Comment by vzaliva** [comment]
It is still happening.  I was using the script to delete some uploaded songs and now it could not even get the list of songs.

**Comment by sigma67** [comment]
I can't reproduce this. Is it still happening? Can you provide some context as to the contents of your script and the exact ytmusicapi function calls?

**Comment by vzaliva** [comment]
It is still happening for me.
Here is the script:

https://github.com/vzaliva/scripts_and_configs/blob/master/scripts/rmsongs.py

This is the trace:

```
$ ./rmsongs.py
Loading lists of artists...
Traceback (most recent call last):
  File "./rmsongs.py", line 32, in <module>
    artists = yt.get_library_upload_artists(limit=1000)
  File "/home/lord/tmp/ytmusicapi/ytmusicapi/mixins/uploads.py", line 111, in get_library_upload_artists
    request_func, parse_func))
  File "/home/lord/tmp/ytmusicapi/ytmusicapi/parsers/utils.py", line 55, in get_continuations
    results = response['continuationContents'][continuation_type]
KeyError: 'continuationContents'
```

It is happening in `get_library_upload_artists` call.

**Comment by sigma67** [comment]
How many songs have you uploaded? Does the error also happen when you set the limit to a lower number (100, 200, 500)?

**Comment by vzaliva** [comment]
I have a lot of songs (1000+) but the script was working initially then broke. I just pulled changes from git repo and tried agan and the error is different:

```
~/t/ytmusicapi (master|…) $ ./rmsongs.py
Traceback (most recent call last):
  File "./rmsongs.py", line 18, in <module>
    yt = YTMusic('headers_auth.json')
  File "/home/lord/tmp/ytmusicapi/ytmusicapi/ytmusic.py", line 97, in __init__
    response = self._send_request('guide', {})
  File "/home/lord/tmp/ytmusicapi/ytmusicapi/ytmusic.py", line 107, in _send_request
    + self.headers['origin'])
KeyError: 'origin'
```

Changing limit to 100 does not help either.

**Comment by sigma67** [comment]
That is a different error related to my latest commits. Try changing x-origin to origin in your headers file.

**Comment by vzaliva** [comment]
After the pull:

```
$ ./rmsongs.py
Loading lists of artists...
Traceback (most recent call last):
  File "./rmsongs.py", line 32, in <module>
    artists = yt.get_library_upload_artists(limit=1000)
  File "/home/lord/tmp/ytmusicapi/ytmusicapi/mixins/uploads.py", line 96, in get_library_upload_artists
    results = find_object_by_key(nav(response, SINGLE_COLUMN_TAB + SECTION_LIST),
  File "/home/lord/tmp/ytmusicapi/ytmusicapi/parsers/utils.py", line 137, in nav
    raise err
  File "/home/lord/tmp/ytmusicapi/ytmusicapi/parsers/utils.py", line 131, in nav
    root = root[k]
KeyError: 'contents'
```

**Comment by sigma67** [comment]
Can you check if this is still happening with 0.10.2?

**Comment by vzaliva** [comment]
Just checked with the latest git master. Still getting ````KeyError: 'contents' ```

```

**Comment by vzaliva** [comment]
Just checked with the latest git master. Still getting ````KeyError: 'contents' ```

**Comment by sigma67** [comment]
I assume that you actually have upload artists on the YT Premium account you're using here. Do you have brand accounts or just using a single account?

Can you please post the full contents of the response variable as JSON? If you're using an IDE like PyCharm you can set a breakpoint and json.dumps the variable contents. Alternatively you can insert a line of code in the project.

**Comment by sigma67** [comment]
Closed due to no reply.
