### ISSUE TITLE
'remove_playlist_items()' does not work nor does it produce an error when 'videoId' and 'setVideoId' == None

### ISSUE THREAD

**Issue by trekk9** [sigma67/ytmusicapi#88]
https://github.com/sigma67/ytmusicapi/blob/bdbaada36ab339024ed583e66d1071f3796dd3eb/ytmusicapi/mixins/playlists.py#L244

My local solution is to add a `continue` to my iteration when removing tracks from a playlist where 'videoId' and 'setVideoId' == None.

Example:

```
if (tracks[x]['videoId'] == None) or (tracks[x]['setVideoId'] == None):
    continue
```

Here is a sample album with a couple of tracks that were removed.

https://music.youtube.com/playlist?list=OLAK5uy_m9fhpjoINvcfPzPibD7EMBXxpG_8txoGM

**Comment by sigma67** [comment]
I'd say this is working as intended, but I think we can do better than that. My proposed solution would be to remove all items from the list which are missing either videoId or setVideoId, before sending the request. This would replace the following lines:

https://github.com/sigma67/ytmusicapi/blob/bdbaada36ab339024ed583e66d1071f3796dd3eb/ytmusicapi/mixins/playlists.py#L254-L256

Would this fix your issue?
