### ISSUE TITLE
`get_artist()` not providing albums->params

### ISSUE THREAD

**Issue by The-Judge** [sigma67/ytmusicapi#89]
In the [docs for get_artist_albums](https://ytmusicapi.readthedocs.io/en/latest/reference.html#ytmusicapi.YTMusic.get_artist_albums), info on parameter `params` is described to be found in return of `get_artist()`. An example on how to use this is provided in the [tests](https://github.com/sigma67/ytmusicapi/blob/bdbaada36ab339024ed583e66d1071f3796dd3eb/tests/test.py#L55).

This seems to be not working; at least not in all cases; here is an example in which `get_artist()` is not providing `['albums']['params']`:

```python
from ytmusicapi import YTMusic
yt = YTMusic()
song = yt.get_song('YGpmxFj0yd4')
artist = yt.get_artist(song['channelId'])
artist['albums']['params']
Traceback (most recent call last):
  File "<input>", line 1, in <module>
KeyError: 'params'
```

This way, it seems to be impossible to use `get_artist_albums()` for this artist.

**Comment by sigma67** [comment]
Yes, that's because it is in fact impossible. If you check out that artist on YTM, you'll find that they only have 5 albums. If there are <= 5 albums, no params will be provided, because all relevant data can be shown directly on the artist page (and retrieved with get_artist in this project). 

https://music.youtube.com/channel/UCYWHe0UWcznS1v7iwgOCHhA

**Comment by The-Judge** [comment]
Thanks for the reply!
I do not really get that; what means "all relevant data can be shown directly on the artist page"?
How would the task, to get a list of artist records, look like for <= 5 albums - artists?

**Comment by sigma67** [comment]
See the documentation here: https://ytmusicapi.readthedocs.io/en/latest/reference.html#ytmusicapi.YTMusic.get_artist

```python
result = ytm.get_artist('...')
albums = result.albums.results
```

get_artist provides all data shown on the artist page.
