### ISSUE TITLE
No way to disable YouTube Music's autocomplete of search terms

### ISSUE THREAD

**Issue by osum4est** [sigma67/ytmusicapi#91]
Hello!

For example, try searching for `Martin Stig Andersen - Deteriation`

The top of the page shows this:
<img width="727" alt="image" src="https://user-images.githubusercontent.com/6581972/96541490-5e670380-125d-11eb-9a12-4b327ff4adcb.png">

The search list does not show the correct song, and using ytmusicapi to search produces the same result. You have to click `Search instead for ...` to get the correct result. 

This can be fixed by optionally including the `QgIIAQ%3D%3D` param when sending the search request, which will disable the autocomplete. Or by making `param3 = 'MABCAggBagoQBBADEAkQBRA'` when including a filter.

I am currently working on a pull request that will add an optional `ignore_spelling` argument to the search function :)

**Comment by sigma67** [comment]
Great suggestion, and awesome that you're working on a PR 👍

**Comment by sigma67** [comment]
I see you've added a commit, feel free to submit the PR when you think it's ready.
