### ISSUE TITLE
`get_history()` does not return uploaded songs 

### ISSUE THREAD

**Issue by scrimshander** [sigma67/ytmusicapi#92]
It appears that `get_history()` does not include plays of uploaded songs. Possibly just a bug/non-feature of YTM.

**Comment by sigma67** [comment]
No, it does. At least for me. Can you post a screenshot of your history page (while hovering the uploaded song so I can see the link) and the results returned by get_history?

**Comment by scrimshander** [comment]
I should have checked this first: these songs do not appear in the YTM
history display either. I just re-tested across a few different
albums/songs. It's very strange that your history contains them. Is there
any setting/upload method I should know about?

**Comment by sigma67** [comment]
I just checked with differented uploaded songs and it works for all of them. Must be a YouTube bug if it doesn't show up on the web page either, definitely not related to this API.

**Comment by scrimshander** [comment]
@sigma67 Just to close the loop in case it ever comes up again, I reuploaded songs and they now appear in history when I play them. Clearly a temporary YTM bug at some point. Sorry for posting as an issue here.

**Comment by sigma67** [comment]
Not your fault, obviously. It's unfortunate that the API is plagued by so many bugs, certainly doesn't make this project any easier.
