### ISSUE TITLE
More than 20 results from a search?

### ISSUE THREAD

**Issue by natumbri** [sigma67/ytmusicapi#94]
Any interest in returning more than 20 results from a search?

I've had a go, and it seems to work: https://github.com/natumbri/ytmusicapi/tree/fix/more-results

Let me know if you'd like a pull request.  I haven't tested it with authorisation.

**Comment by sigma67** [comment]
Yes, this is one thing I didn't get around to implementing. Great that you've gone ahead with it. 

I looked at your code and it looks good, I have just a few suggestions for improvement. Please submit a PR and I will comment there

**Comment by natumbri** [comment]
Great - I'll try to make a PR. 

I'm pretty hopeless at them, particularly keeping the automatic linting tools under control, and I haven't been able to make the unittests work at all. But I'll have a crack and we'll see how it goes...
