### ISSUE TITLE
Duration unavailable for uploaded songs

### ISSUE THREAD

**Issue by chrislewisdev** [sigma67/ytmusicapi#96]
Hello, and thanks for this neat library!

It does not seem possible with the existing information from the API to find out the duration of an uploaded song. This is similar to #64 except in this case I was hoping the duration would be available as part of the output of `get_library_upload_songs()`.

My use case: I am making a little tool to generate random playlists of a given length, for example, I can request a playlist for 45 minutes and it will create one for me. Obviously knowing the duration of a song is key here, and I would like to include uploaded songs in these playlists but cannot do so at the moment.

It looks like the duration is available in the response content from `/browse` that is currently used to parse uploaded song info, here's a snippet containing the duration:
```
"fixedColumns": [
                                    {
                                      "musicResponsiveListItemFixedColumnRenderer": {
                                        "text": {
                                          "runs": [
                                            {
                                              "text": "4:15"
                                            }
                                          ]
                                        },
                                        "displayPriority": "MUSIC_RESPONSIVE_LIST_ITEM_COLUMN_DISPLAY_PRIORITY_HIGH",
                                        "size": "MUSIC_RESPONSIVE_LIST_ITEM_FIXED_COLUMN_SIZE_SMALL"
                                      }
                                    }
                                  ],
```

Let me know if you think it's possible for this information to be included in the API. If time permits I may have a crack at a PR but if you had some free time to add this it would be highly appreciated. Thanks!

**Comment by sigma67** [comment]
Good point, this should defnitely be added. Feel free to submit a PR!

**Comment by chrislewisdev** [comment]
Thanks a bunch for adding this @sigma67 :)
